%% batch_validate_matlab.m
% Read the 20 JSON scenarios generated by run_batch_validation.py,
% run MATLAB ADMM on each, and compare timing with Python.
%
% Usage: run from warehouse root after running:
%   python python_port/run_batch_validation.py
%
% Output: prints a table of N / k / cost / T_matlab for each scenario.

clear all;

CONFIG_DIR = fullfile('python_port', 'configs');
files = dir(fullfile(CONFIG_DIR, 'scenario_*.json'));

if isempty(files)
    error('No scenario JSON files found in %s.\nRun run_batch_validation.py first.', CONFIG_DIR);
end

% ADMM parameters (must match Python)
rho1 = 1; rho2 = 1; max_iter = 50;
tol_r = 1e-2; tol_s = 1e-2;

IntSpaceDB = makeIntSpaceDB();

fprintf('%3s  %4s  %6s  %5s  %10s  %10s\n', '#', 'N', 'seed', 'k', 'cost', 'T_mat(s)');
fprintf('%s\n', repmat('-', 1, 55));

T_list = [];

for fi = 1:numel(files)
    fpath = fullfile(files(fi).folder, files(fi).name);
    raw   = jsondecode(fileread(fpath));

    N      = raw.N;
    Dt     = raw.Dt;
    seed   = 0;   % seed not stored in JSON; just for display

    % ── Reconstruct Python-format data in MATLAB ─────────────────────
    alpha_tilde = cell(N, 1);
    deadline    = cell(N, 1);
    for n = 1:N
        alpha_tilde{n} = raw.alpha_tilde(n);
        deadline{n}    = raw.deadline(n);
    end

    % agent_chains: 1-indexed
    pathInfo_agent_chain = cell(1, N);
    for n = 1:N
        ch = raw.agent_chains{n};
        if ~iscell(ch), ch = num2cell(ch); end
        pathInfo_agent_chain{n} = {double([ch{:}])};
    end

    pathInfo_c = cell(1, N);
    for n = 1:N
        c = raw.path_c{n};
        if ~iscell(c), c = num2cell(c); end
        pathInfo_c{n} = {double([c{:}])};
    end

    % agent_participation: 9 agents x N (terminal = all true)
    ap_raw = raw.agent_participation;   % 8 x N
    agent_participation = cell(9, 1);
    for ag = 1:8
        agent_participation{ag} = double(ap_raw(ag, :)');
    end
    agent_participation{9} = ones(N, 1);

    % Pack const
    const.N = N; const.Dt = Dt;
    const.rho1 = rho1; const.rho2 = rho2;
    const.max_iter = max_iter;
    const.tol_r = tol_r; const.tol_s = tol_s;
    const.alpha_tilde = alpha_tilde;
    const.deadline    = deadline;
    const.pathInfo_agent_chain = pathInfo_agent_chain;
    const.pathInfo_c = pathInfo_c;
    const.IntSpaceDB = IntSpaceDB;
    const.weight = 1.5;
    const.use_pruning = true;
    const.useTBound = true;
    const.timeout_int_s = 30;

    % ── Run ADMM ─────────────────────────────────────────────────────
    t0 = tic;
    [x_prev, ~, ~, ~, delay_costs, k_conv] = run_admm_seq(const, agent_participation, N);
    T_mat = toc(t0);

    cost = delay_costs(k_conv);
    T_list(end+1) = T_mat; %#ok<AGROW>

    fprintf('%3d  %4d  %6s  %5d  %10.4f  %10.2f\n', ...
        fi, N, '---', k_conv, cost, T_mat);
end

fprintf('%s\n', repmat('-', 1, 55));
fprintf('Average MATLAB T_solve: %.2f s\n', mean(T_list));
fprintf('Max     MATLAB T_solve: %.2f s\n', max(T_list));


% =========================================================================
% Embedded sequential ADMM (from MAIN_Sequential_Debug.m)
% =========================================================================
function [x_prev, y_prev, LocalTreeCache, residual_r, delay_costs, k] = ...
        run_admm_seq(const, agent_participation, N)

    rho1 = const.rho1; rho2 = const.rho2;
    max_iter = const.max_iter;
    tol_r_val = const.tol_r; tol_s_val = const.tol_s;
    Dt   = const.Dt;
    alpha_tilde = const.alpha_tilde;
    deadline    = const.deadline;
    pathInfo_agent_chain = const.pathInfo_agent_chain;
    pathInfo_c  = const.pathInfo_c;
    IntSpaceDB  = const.IntSpaceDB;
    weight = const.weight;
    kn = 1;

    % Init x_prev, y_prev
    [x_prev, y_prev] = initEarliestXYPrev_fromChain( ...
        alpha_tilde, pathInfo_agent_chain, pathInfo_c, Dt, N);

    x_prev_bar = x_prev; y_prev_bar = y_prev;

    a_x = cell(9, 1); a_y = cell(9, 1);
    for ag = 1:9
        a_x{ag} = cell(N, 1); a_y{ag} = cell(N, 1);
        for n = 1:N
            a_x{ag}{n} = 0; a_y{ag}{n} = 0;
        end
    end

    LocalTreeCache = cell(9, 1);
    residual_r = zeros(max_iter, 1);
    residual_s = zeros(max_iter, 1);
    delay_costs = zeros(max_iter, 1);

    for k = 1:max_iter
        x_last = x_prev; y_last = y_prev;
        a_x_new = a_x; a_y_new = a_y;

        % Step 1: dual update + bar
        for n = 1:N
            chain = pathInfo_agent_chain{n}{kn};
            ag0 = chain(1);
            if ~isempty(x_prev{ag0}{n})
                x_prev_bar{ag0}{n}(kn) = x_prev{ag0}{n}(kn) / 2;
            end
            for pos = 2:length(chain)
                prev_ag = chain(pos-1);
                curr_ag = chain(pos);
                xc = x_prev{curr_ag}{n};
                yp = y_prev{prev_ag}{n};
                if isempty(xc) || isempty(yp), continue; end
                a_x_new{curr_ag}{n}(kn) = a_x{curr_ag}{n}(kn) + rho1*(xc(kn)-yp(kn));
                x_prev_bar{curr_ag}{n}(kn) = (xc(kn)+yp(kn))/2;
                a_y_new{prev_ag}{n}(kn) = a_y{prev_ag}{n}(kn) + rho1*(yp(kn)-xc(kn));
                if prev_ag < 9
                    y_prev_bar{prev_ag}{n}(kn) = (yp(kn)+xc(kn))/2;
                end
            end
        end

        % Step 2: agent updates (intersection, road, terminal)
        r_local = 0;
        for ag = 1:4
            entries = agent_participation{ag}';
            valid   = find(entries);
            if isempty(valid), continue; end
            [x_new, y_new, ba, bg, ~, ~, LocalTreeCache{ag}] = INi_Admm_DecisionTree( ...
                ag, entries, x_prev, y_prev, ...
                x_prev_bar{ag}, y_prev_bar{ag}, ...
                valid, a_x_new{ag}, a_y_new{ag}, const, LocalTreeCache{ag});
            for n = valid
                x_prev{ag}{n}(kn) = x_new(n);
                y_prev{ag}{n}(kn) = y_new(n);
                if ~isempty(ba{n}) && ~isempty(bg{n})
                    r_local = r_local + (x_new(n)-ba{n})^2 + (y_new(n)-bg{n})^2;
                end
            end
        end
        for ag = 5:8
            entries = agent_participation{ag}';
            valid   = find(entries);
            if isempty(valid), continue; end
            [xr, yr] = updateRoadAgent(ag, entries, valid, ...
                x_prev{ag}, y_prev{ag}, x_prev_bar{ag}, y_prev_bar{ag}, ...
                a_x_new{ag}, a_y_new{ag}, const);
            for n = valid
                x_prev{ag}{n}(kn) = xr(n);
                y_prev{ag}{n}(kn) = yr(n);
            end
        end
        [x9, dc] = updateAgent9(x_prev{9}, x_prev_bar{9}, a_x_new{9}, const);
        for n = 1:N
            x_prev{9}{n}(kn) = x9(n);
        end
        delay_costs(k) = dc;

        % Step 3: residuals
        r_val = r_local;
        s_val = 0;
        for n = 1:N
            chain = pathInfo_agent_chain{n}{kn};
            for pos = 2:length(chain)
                pa = chain(pos-1); ca = chain(pos);
                xc = x_prev{ca}{n}; yp = y_prev{pa}{n};
                xl = x_last{ca}{n}; yl = y_last{pa}{n};
                if ~isempty(xc) && ~isempty(yp)
                    r_val = r_val + (xc(kn)-yp(kn))^2;
                end
                if ~isempty(xc) && ~isempty(xl)
                    s_val = s_val + (xc(kn)-xl(kn))^2;
                end
                if ~isempty(yp) && ~isempty(yl) && pa < 9
                    s_val = s_val + (yp(kn)-yl(kn))^2;
                end
            end
        end
        for n = 1:N
            x9c = x_prev{9}{n}; x9l = x_last{9}{n};
            if ~isempty(x9c) && ~isempty(x9l)
                s_val = s_val + (x9c(kn)-x9l(kn))^2;
            end
        end
        residual_r(k) = r_val;
        residual_s(k) = s_val;
        a_x = a_x_new; a_y = a_y_new;

        if r_val < tol_r_val && s_val < tol_s_val
            break;
        end
    end
    residual_r = residual_r(1:k);
    delay_costs = delay_costs(1:k);
end
