// Interactive decision-tree data — 10r_S10
// Auto-generated by export_interactive_tree.m
window.ALL_INTERACTIVE_TREES = window.ALL_INTERACTIVE_TREES || {};
window.ALL_INTERACTIVE_TREES["10r_S10"] = {
  "numInt": 4,
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":21,"tw":22.899,"f":0.01,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 0.01,
          "vehicles": [
            {"veh":2,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[1.0000,2.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":3,"k":1,"t0":4.0000,"tf":4.7854,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[1.0000],"segStart":[4.0000],"segEnd":[4.7854]},
            {"veh":4,"k":2,"t0":6.0027,"tf":8.3589,"genTime":6.0037,"actualGenTime":6.0046,"spaces":[2.0000,5.0000,4.0000],"segStart":[6.0027,6.7881,7.5735],"segEnd":[6.7881,7.5735,8.3589]},
            {"veh":7,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[4.0000,1.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":9,"k":2,"t0":6.7882,"tf":8.7882,"genTime":6.7892,"actualGenTime":6.7901,"spaces":[2.0000,3.0000],"segStart":[6.7882,7.7882],"segEnd":[7.7882,8.7882]},
            {"veh":10,"k":2,"t0":4.7854,"tf":7.1416,"genTime":4.7854,"actualGenTime":4.7854,"spaces":[3.0000,5.0000,1.0000],"segStart":[4.7854,5.5708,6.3562],"segEnd":[5.5708,6.3562,7.1416]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":19,"tw":25.253,"f":0.68,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 0.68,
          "vehicles": [
            {"veh":3,"k":2,"t0":7.0206,"tf":7.8060,"genTime":6.7856,"actualGenTime":6.9044,"spaces":[4.0000],"segStart":[7.0206],"segEnd":[7.8060]},
            {"veh":4,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[2.0000,3.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":7,"k":2,"t0":6.0206,"tf":8.0206,"genTime":6.0134,"actualGenTime":6.0183,"spaces":[4.0000,1.0000],"segStart":[6.0206,7.0206],"segEnd":[7.0206,8.0206]},
            {"veh":9,"k":1,"t0":2.4292,"tf":4.7854,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[1.0000,5.0000,3.0000],"segStart":[2.4292,3.2146,4.0000],"segEnd":[3.2146,4.0000,4.7854]},
            {"veh":10,"k":3,"t0":9.1416,"tf":11.1416,"genTime":9.1416,"actualGenTime":9.1416,"spaces":[4.0000,1.0000],"segStart":[9.1416,10.1416],"segEnd":[10.1416,11.1416]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":15,"tw":24.467,"f":-0.00,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": -0.00,
          "vehicles": [
            {"veh":1,"k":1,"t0":2.0000,"tf":4.3562,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000,5.0000,1.0000],"segStart":[2.0000,2.7854,3.5708],"segEnd":[2.7854,3.5708,4.3562]},
            {"veh":5,"k":2,"t0":6.3562,"tf":8.3562,"genTime":6.3562,"actualGenTime":6.3562,"spaces":[4.0000,1.0000],"segStart":[6.3562,7.3562],"segEnd":[7.3562,8.3562]},
            {"veh":6,"k":2,"t0":8.3562,"tf":10.3562,"genTime":8.3562,"actualGenTime":8.3562,"spaces":[4.0000,1.0000],"segStart":[8.3562,9.3562],"segEnd":[9.3562,10.3562]},
            {"veh":8,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[2.0000,3.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":18,"tw":22.289,"f":0.36,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 0.36,
          "vehicles": [
            {"veh":2,"k":2,"t0":6.3562,"tf":8.3562,"genTime":6.0000,"actualGenTime":6.1781,"spaces":[1.0000,2.0000],"segStart":[6.3562,7.3562],"segEnd":[7.3562,8.3562]},
            {"veh":5,"k":1,"t0":2.0000,"tf":4.3562,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000,5.0000,1.0000],"segStart":[2.0000,2.7854,3.5708],"segEnd":[2.7854,3.5708,4.3562]},
            {"veh":6,"k":1,"t0":4.0000,"tf":6.3562,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[3.0000,5.0000,1.0000],"segStart":[4.0000,4.7854,5.5708],"segEnd":[4.7854,5.5708,6.3562]},
            {"veh":8,"k":2,"t0":6.0000,"tf":6.7854,"genTime":6.0000,"actualGenTime":6.0000,"spaces":[2.0000],"segStart":[6.0000],"segEnd":[6.7854]},
            {"veh":10,"k":1,"t0":2.0000,"tf":2.7854,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[4.0000],"segStart":[2.0000],"segEnd":[2.7854]}
          ],
          "numSpaces": 5
        }
      ]
    }
  }
};
