// Interactive decision-tree data — 25r_S1
// Auto-generated by export_interactive_tree.m
window.ALL_INTERACTIVE_TREES = window.ALL_INTERACTIVE_TREES || {};
window.ALL_INTERACTIVE_TREES["25r_S1"] = {
  "numInt": 4,
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":48,"tw":40.610,"f":2.30,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 2.30,
          "vehicles": [
            {"veh":4,"k":2,"t0":7.3562,"tf":9.7124,"genTime":7.3562,"actualGenTime":7.3562,"spaces":[2.0000,5.0000,4.0000],"segStart":[7.3562,8.1416,8.9270],"segEnd":[8.1416,8.9270,9.7124]},
            {"veh":8,"k":2,"t0":11.0000,"tf":11.7854,"genTime":11.0000,"actualGenTime":11.0000,"spaces":[3.0000],"segStart":[11.0000],"segEnd":[11.7854]},
            {"veh":9,"k":2,"t0":15.3095,"tf":16.0949,"genTime":15.3195,"actualGenTime":15.3162,"spaces":[3.0000],"segStart":[15.3095],"segEnd":[16.0949]},
            {"veh":10,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[1.0000,2.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":11,"k":1,"t0":6.0000,"tf":6.7854,"genTime":6.0000,"actualGenTime":6.0000,"spaces":[1.0000],"segStart":[6.0000],"segEnd":[6.7854]},
            {"veh":12,"k":1,"t0":10.0000,"tf":12.0000,"genTime":10.0000,"actualGenTime":10.0000,"spaces":[1.0000,2.0000],"segStart":[10.0000,11.0000],"segEnd":[11.0000,12.0000]},
            {"veh":16,"k":3,"t0":24.4988,"tf":26.4988,"genTime":24.4987,"actualGenTime":24.4988,"spaces":[3.0000,4.0000],"segStart":[24.4988,25.4988],"segEnd":[25.4988,26.4988]},
            {"veh":17,"k":2,"t0":5.7854,"tf":6.5708,"genTime":5.7854,"actualGenTime":5.7854,"spaces":[3.0000],"segStart":[5.7854],"segEnd":[6.5708]},
            {"veh":18,"k":2,"t0":9.7854,"tf":11.7854,"genTime":9.7854,"actualGenTime":9.7854,"spaces":[3.0000,4.0000],"segStart":[9.7854,10.7854],"segEnd":[10.7854,11.7854]},
            {"veh":22,"k":2,"t0":15.0949,"tf":17.0949,"genTime":15.0000,"actualGenTime":15.0492,"spaces":[2.0000,3.0000],"segStart":[15.0949,16.0949],"segEnd":[16.0949,17.0949]},
            {"veh":23,"k":1,"t0":2.4292,"tf":4.7854,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[4.0000,5.0000,2.0000],"segStart":[2.4292,3.2146,4.0000],"segEnd":[3.2146,4.0000,4.7854]},
            {"veh":24,"k":1,"t0":6.0000,"tf":8.0000,"genTime":6.0000,"actualGenTime":6.0000,"spaces":[4.0000,1.0000],"segStart":[6.0000,7.0000],"segEnd":[7.0000,8.0000]},
            {"veh":25,"k":1,"t0":11.7854,"tf":14.1416,"genTime":10.0000,"actualGenTime":10.0000,"spaces":[4.0000,5.0000,2.0000],"segStart":[11.7854,12.5708,13.3562],"segEnd":[12.5708,13.3562,14.1416]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":37,"tw":32.004,"f":1.57,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 1.57,
          "vehicles": [
            {"veh":2,"k":2,"t0":12.0000,"tf":14.0000,"genTime":11.0000,"actualGenTime":11.5001,"spaces":[3.0000,4.0000],"segStart":[12.0000,13.0000],"segEnd":[13.0000,14.0000]},
            {"veh":3,"k":2,"t0":15.0000,"tf":17.0000,"genTime":15.0000,"actualGenTime":15.0000,"spaces":[3.0000,4.0000],"segStart":[15.0000,16.0000],"segEnd":[16.0000,17.0000]},
            {"veh":4,"k":1,"t0":2.0000,"tf":4.3562,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[1.0000,5.0000,3.0000],"segStart":[2.0000,2.7854,3.5708],"segEnd":[2.7854,3.5708,4.3562]},
            {"veh":5,"k":1,"t0":6.0000,"tf":8.0000,"genTime":6.0000,"actualGenTime":6.0000,"spaces":[1.0000,2.0000],"segStart":[6.0000,7.0000],"segEnd":[7.0000,8.0000]},
            {"veh":6,"k":1,"t0":10.0000,"tf":12.0000,"genTime":10.0000,"actualGenTime":10.0000,"spaces":[1.0000,2.0000],"segStart":[10.0000,11.0000],"segEnd":[11.0000,12.0000]},
            {"veh":11,"k":2,"t0":10.1419,"tf":10.9273,"genTime":9.7854,"actualGenTime":9.9637,"spaces":[4.0000],"segStart":[10.1419],"segEnd":[10.9273]},
            {"veh":13,"k":2,"t0":8.1419,"tf":10.1419,"genTime":8.1419,"actualGenTime":8.1419,"spaces":[3.0000,4.0000],"segStart":[8.1419,9.1419],"segEnd":[9.1419,10.1419]},
            {"veh":15,"k":2,"t0":16.0000,"tf":18.3562,"genTime":15.7855,"actualGenTime":15.8928,"spaces":[3.0000,5.0000,1.0000],"segStart":[16.0000,16.7854,17.5708],"segEnd":[16.7854,17.5708,18.3562]},
            {"veh":20,"k":1,"t0":2.0000,"tf":2.7854,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[2.0000],"segStart":[2.0000],"segEnd":[2.7854]},
            {"veh":21,"k":1,"t0":6.0000,"tf":6.7854,"genTime":6.0000,"actualGenTime":6.0000,"spaces":[2.0000],"segStart":[6.0000],"segEnd":[6.7854]},
            {"veh":22,"k":1,"t0":10.0000,"tf":12.0000,"genTime":10.0000,"actualGenTime":10.0000,"spaces":[2.0000,3.0000],"segStart":[10.0000,11.0000],"segEnd":[11.0000,12.0000]},
            {"veh":24,"k":2,"t0":11.0000,"tf":11.7854,"genTime":11.0000,"actualGenTime":11.0000,"spaces":[4.0000],"segStart":[11.0000],"segEnd":[11.7854]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":3,"tw":2.785,"f":0.00,"isLeaf":false,"isRoot":false},
        {"id":3,"orig":4,"tw":3.571,"f":0.00,"isLeaf":false,"isRoot":false},
        {"id":4,"orig":48,"tw":31.326,"f":2.51,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [3,4]
      ],
      "optimalPath": [1,2,3,4],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2,3,4]
      ],
      "leafGantts": [
        {
          "fCost": 2.51,
          "vehicles": [
            {"veh":1,"k":1,"t0":2.0000,"tf":4.3562,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000,5.0000,1.0000],"segStart":[2.0000,2.7854,3.5708],"segEnd":[2.7854,3.5708,4.3562]},
            {"veh":2,"k":1,"t0":6.0000,"tf":8.0000,"genTime":6.0000,"actualGenTime":6.0000,"spaces":[3.0000,4.0000],"segStart":[6.0000,7.0000],"segEnd":[7.0000,8.0000]},
            {"veh":3,"k":1,"t0":10.0000,"tf":12.0000,"genTime":10.0000,"actualGenTime":10.0000,"spaces":[3.0000,4.0000],"segStart":[10.0000,11.0000],"segEnd":[11.0000,12.0000]},
            {"veh":5,"k":2,"t0":11.0062,"tf":11.7916,"genTime":11.0058,"actualGenTime":11.0067,"spaces":[1.0000],"segStart":[11.0062],"segEnd":[11.7916]},
            {"veh":6,"k":2,"t0":15.0001,"tf":17.0001,"genTime":15.0001,"actualGenTime":15.0001,"spaces":[1.0000,2.0000],"segStart":[15.0001,16.0001],"segEnd":[16.0001,17.0001]},
            {"veh":7,"k":2,"t0":8.0000,"tf":10.3562,"genTime":7.3562,"actualGenTime":7.6781,"spaces":[4.0000,5.0000,2.0000],"segStart":[8.0000,8.7854,9.5708],"segEnd":[8.7854,9.5708,10.3562]},
            {"veh":13,"k":1,"t0":2.7854,"tf":5.1416,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[2.0000,5.0000,4.0000],"segStart":[2.7854,3.5708,4.3562],"segEnd":[3.5708,4.3562,5.1416]},
            {"veh":14,"k":1,"t0":6.0000,"tf":8.0000,"genTime":6.0000,"actualGenTime":6.0000,"spaces":[2.0000,3.0000],"segStart":[6.0000,7.0000],"segEnd":[7.0000,8.0000]},
            {"veh":15,"k":1,"t0":10.4292,"tf":12.7854,"genTime":10.0000,"actualGenTime":10.0000,"spaces":[2.0000,5.0000,4.0000],"segStart":[10.4292,11.2146,12.0000],"segEnd":[11.2146,12.0000,12.7854]},
            {"veh":16,"k":1,"t0":14.0000,"tf":16.0000,"genTime":14.0000,"actualGenTime":14.0000,"spaces":[2.0000,3.0000],"segStart":[14.0000,15.0000],"segEnd":[15.0000,16.0000]},
            {"veh":19,"k":2,"t0":15.4293,"tf":17.7855,"genTime":15.0000,"actualGenTime":15.2147,"spaces":[4.0000,5.0000,2.0000],"segStart":[15.4293,16.2147,17.0001],"segEnd":[16.2147,17.0001,17.7855]},
            {"veh":20,"k":2,"t0":6.0000,"tf":8.0000,"genTime":5.7854,"actualGenTime":5.8928,"spaces":[1.0000,2.0000],"segStart":[6.0000,7.0000],"segEnd":[7.0000,8.0000]},
            {"veh":21,"k":2,"t0":9.7854,"tf":10.5708,"genTime":9.7854,"actualGenTime":9.7854,"spaces":[1.0000],"segStart":[9.7854],"segEnd":[10.5708]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":42,"tw":35.182,"f":0.64,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 0.64,
          "vehicles": [
            {"veh":7,"k":1,"t0":2.0000,"tf":4.3562,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000,5.0000,1.0000],"segStart":[2.0000,2.7854,3.5708],"segEnd":[2.7854,3.5708,4.3562]},
            {"veh":8,"k":1,"t0":6.0000,"tf":8.0000,"genTime":6.0000,"actualGenTime":6.0000,"spaces":[3.0000,4.0000],"segStart":[6.0000,7.0000],"segEnd":[7.0000,8.0000]},
            {"veh":9,"k":1,"t0":10.3303,"tf":12.3303,"genTime":10.0000,"actualGenTime":10.0000,"spaces":[3.0000,4.0000],"segStart":[10.3303,11.3303],"segEnd":[11.3303,12.3303]},
            {"veh":10,"k":2,"t0":6.9741,"tf":8.9741,"genTime":6.9849,"actualGenTime":6.9771,"spaces":[1.0000,2.0000],"segStart":[6.9741,7.9741],"segEnd":[7.9741,8.9741]},
            {"veh":12,"k":2,"t0":15.0000,"tf":17.0000,"genTime":15.0000,"actualGenTime":15.0000,"spaces":[1.0000,2.0000],"segStart":[15.0000,16.0000],"segEnd":[16.0000,17.0000]},
            {"veh":14,"k":2,"t0":11.0000,"tf":11.7854,"genTime":11.0000,"actualGenTime":11.0000,"spaces":[2.0000],"segStart":[11.0000],"segEnd":[11.7854]},
            {"veh":16,"k":2,"t0":19.1422,"tf":21.4984,"genTime":19.0000,"actualGenTime":19.0712,"spaces":[2.0000,5.0000,4.0000],"segStart":[19.1422,19.9276,20.7130],"segEnd":[19.9276,20.7130,21.4984]},
            {"veh":17,"k":1,"t0":2.0000,"tf":2.7854,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[4.0000],"segStart":[2.0000],"segEnd":[2.7854]},
            {"veh":18,"k":1,"t0":6.0000,"tf":6.7854,"genTime":6.0000,"actualGenTime":6.0000,"spaces":[4.0000],"segStart":[6.0000],"segEnd":[6.7854]},
            {"veh":19,"k":1,"t0":10.0000,"tf":12.0000,"genTime":10.0000,"actualGenTime":10.0000,"spaces":[4.0000,1.0000],"segStart":[10.0000,11.0000],"segEnd":[11.0000,12.0000]},
            {"veh":23,"k":2,"t0":7.9741,"tf":10.3303,"genTime":7.7857,"actualGenTime":7.8775,"spaces":[1.0000,5.0000,3.0000],"segStart":[7.9741,8.7595,9.5449],"segEnd":[8.7595,9.5449,10.3303]},
            {"veh":25,"k":2,"t0":17.1422,"tf":19.1422,"genTime":17.1420,"actualGenTime":17.1422,"spaces":[1.0000,2.0000],"segStart":[17.1422,18.1422],"segEnd":[18.1422,19.1422]}
          ],
          "numSpaces": 5
        }
      ]
    }
  }
};
