// Interactive decision-tree data — tr_10r_S1
// Auto-generated by export_interactive_tree.m
window.ALL_INTERACTIVE_TREES = window.ALL_INTERACTIVE_TREES || {};
window.ALL_INTERACTIVE_TREES["tr_10r_S1"] = {
  "numInt": 5,
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":28,"tw":39.146,"f":-0.00,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": -0.00,
          "vehicles": [
            {"veh":1,"k":1,"t0":12.2500,"tf":14.6062,"genTime":12.2500,"actualGenTime":12.2500,"spaces":[3.0000,5.0000,1.0000],"segStart":[12.2500,13.0354,13.8208],"segEnd":[13.0354,13.8208,14.6062]},
            {"veh":2,"k":1,"t0":14.2500,"tf":16.6062,"genTime":14.2500,"actualGenTime":14.2500,"spaces":[3.0000,5.0000,1.0000],"segStart":[14.2500,15.0354,15.8208],"segEnd":[15.0354,15.8208,16.6062]},
            {"veh":3,"k":2,"t0":16.0354,"tf":18.3915,"genTime":16.0354,"actualGenTime":16.0354,"spaces":[2.0000,5.0000,4.0000],"segStart":[16.0354,16.8208,17.6061],"segEnd":[16.8208,17.6061,18.3915]},
            {"veh":5,"k":3,"t0":21.0353,"tf":23.3915,"genTime":21.0353,"actualGenTime":21.0353,"spaces":[2.0000,5.0000,4.0000],"segStart":[21.0353,21.8207,22.6061],"segEnd":[21.8207,22.6061,23.3915]},
            {"veh":6,"k":3,"t0":23.0353,"tf":25.0353,"genTime":23.0353,"actualGenTime":23.0353,"spaces":[2.0000,3.0000],"segStart":[23.0353,24.0353],"segEnd":[24.0353,25.0353]},
            {"veh":9,"k":2,"t0":17.6061,"tf":18.3915,"genTime":17.6062,"actualGenTime":17.6061,"spaces":[1.0000],"segStart":[17.6061],"segEnd":[18.3915]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":14,"tw":19.368,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":3,"orig":15,"tw":19.516,"f":-0.09,"isLeaf":false,"isRoot":false},
        {"id":4,"orig":16,"tw":19.606,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":5,"orig":23,"tw":20.035,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":6,"orig":24,"tw":20.035,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":7,"orig":25,"tw":20.392,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":8,"orig":26,"tw":20.392,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":9,"orig":27,"tw":20.606,"f":1.00,"isLeaf":false,"isRoot":false},
        {"id":10,"orig":28,"tw":21.391,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":11,"orig":30,"tw":21.392,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":12,"orig":31,"tw":21.392,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":13,"orig":32,"tw":21.391,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":14,"orig":34,"tw":22.392,"f":1.14,"isLeaf":false,"isRoot":false},
        {"id":15,"orig":35,"tw":22.391,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":16,"orig":36,"tw":21.392,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":17,"orig":37,"tw":22.035,"f":0.79,"isLeaf":false,"isRoot":false},
        {"id":18,"orig":40,"tw":20.368,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":19,"orig":41,"tw":20.368,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":20,"orig":42,"tw":21.035,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":21,"orig":43,"tw":21.153,"f":0.76,"isLeaf":false,"isRoot":false},
        {"id":22,"orig":44,"tw":21.368,"f":0.12,"isLeaf":false,"isRoot":false},
        {"id":23,"orig":45,"tw":20.392,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":24,"orig":48,"tw":21.391,"f":0.12,"isLeaf":false,"isRoot":false},
        {"id":25,"orig":49,"tw":21.392,"f":0.12,"isLeaf":false,"isRoot":false},
        {"id":26,"orig":50,"tw":22.391,"f":0.12,"isLeaf":false,"isRoot":false},
        {"id":27,"orig":53,"tw":24.391,"f":4.90,"isLeaf":true,"isRoot":false},
        {"id":28,"orig":54,"tw":21.391,"f":0.12,"isLeaf":false,"isRoot":false},
        {"id":29,"orig":55,"tw":21.391,"f":0.12,"isLeaf":false,"isRoot":false},
        {"id":30,"orig":56,"tw":22.153,"f":1.88,"isLeaf":false,"isRoot":false},
        {"id":31,"orig":57,"tw":22.368,"f":2.88,"isLeaf":false,"isRoot":false},
        {"id":32,"orig":58,"tw":21.821,"f":1.55,"isLeaf":false,"isRoot":false},
        {"id":33,"orig":59,"tw":22.035,"f":2.55,"isLeaf":false,"isRoot":false},
        {"id":34,"orig":70,"tw":37.502,"f":0.18,"isLeaf":true,"isRoot":false},
        {"id":35,"orig":72,"tw":23.035,"f":0.79,"isLeaf":false,"isRoot":false},
        {"id":36,"orig":73,"tw":22.391,"f":0.79,"isLeaf":false,"isRoot":false},
        {"id":37,"orig":77,"tw":24.391,"f":5.57,"isLeaf":true,"isRoot":false},
        {"id":38,"orig":78,"tw":21.391,"f":0.88,"isLeaf":false,"isRoot":false},
        {"id":39,"orig":79,"tw":22.153,"f":0.88,"isLeaf":false,"isRoot":false},
        {"id":40,"orig":80,"tw":22.391,"f":0.88,"isLeaf":false,"isRoot":false},
        {"id":41,"orig":83,"tw":24.391,"f":5.66,"isLeaf":true,"isRoot":false},
        {"id":42,"orig":90,"tw":24.391,"f":5.93,"isLeaf":true,"isRoot":false},
        {"id":43,"orig":102,"tw":37.502,"f":2.36,"isLeaf":true,"isRoot":false},
        {"id":44,"orig":103,"tw":22.821,"f":4.98,"isLeaf":false,"isRoot":false},
        {"id":45,"orig":104,"tw":22.391,"f":2.55,"isLeaf":false,"isRoot":false},
        {"id":46,"orig":106,"tw":23.153,"f":5.64,"isLeaf":false,"isRoot":false},
        {"id":47,"orig":107,"tw":22.391,"f":2.88,"isLeaf":false,"isRoot":false},
        {"id":48,"orig":118,"tw":37.502,"f":2.90,"isLeaf":true,"isRoot":false},
        {"id":49,"orig":128,"tw":37.502,"f":3.57,"isLeaf":true,"isRoot":false},
        {"id":50,"orig":138,"tw":37.502,"f":3.93,"isLeaf":true,"isRoot":false},
        {"id":51,"orig":149,"tw":37.502,"f":4.41,"isLeaf":true,"isRoot":false},
        {"id":52,"orig":152,"tw":24.153,"f":5.40,"isLeaf":true,"isRoot":false},
        {"id":53,"orig":153,"tw":24.392,"f":5.93,"isLeaf":true,"isRoot":false},
        {"id":54,"orig":155,"tw":24.821,"f":6.41,"isLeaf":true,"isRoot":false},
        {"id":55,"orig":164,"tw":37.502,"f":5.19,"isLeaf":true,"isRoot":false},
        {"id":56,"orig":165,"tw":25.035,"f":6.86,"isLeaf":true,"isRoot":false},
        {"id":57,"orig":175,"tw":37.502,"f":5.33,"isLeaf":true,"isRoot":false},
        {"id":58,"orig":177,"tw":25.153,"f":7.40,"isLeaf":true,"isRoot":false},
        {"id":59,"orig":187,"tw":37.502,"f":5.66,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [4,5],
        [4,6],
        [5,7],
        [5,8],
        [7,9],
        [7,10],
        [10,11],
        [10,12],
        [8,13],
        [12,14],
        [12,15],
        [13,16],
        [13,17],
        [6,18],
        [6,19],
        [18,20],
        [18,21],
        [19,22],
        [19,23],
        [23,24],
        [24,25],
        [24,26],
        [26,27],
        [22,28],
        [20,29],
        [28,30],
        [28,31],
        [29,32],
        [29,33],
        [3,34],
        [17,35],
        [17,36],
        [36,37],
        [21,38],
        [38,39],
        [38,40],
        [40,41],
        [15,42],
        [9,43],
        [33,44],
        [33,45],
        [31,46],
        [31,47],
        [25,48],
        [16,49],
        [11,50],
        [32,51],
        [30,52],
        [14,53],
        [44,54],
        [39,55],
        [35,56],
        [45,57],
        [46,58],
        [47,59]
      ],
      "optimalPath": [1,2,3,34],
      "optimalLeaf": 2,
      "leafPaths": [
        [1,2,4,6,19,23,24,26,27],
        [1,2,3,34],
        [1,2,4,5,8,13,17,36,37],
        [1,2,4,6,18,21,38,40,41],
        [1,2,4,5,7,10,12,15,42],
        [1,2,4,5,7,9,43],
        [1,2,4,6,19,23,24,25,48],
        [1,2,4,5,8,13,16,49],
        [1,2,4,5,7,10,11,50],
        [1,2,4,6,18,20,29,32,51],
        [1,2,4,6,19,22,28,30,52],
        [1,2,4,5,7,10,12,14,53],
        [1,2,4,6,18,20,29,33,44,54],
        [1,2,4,6,18,21,38,39,55],
        [1,2,4,5,8,13,17,35,56],
        [1,2,4,6,18,20,29,33,45,57],
        [1,2,4,6,19,22,28,31,46,58],
        [1,2,4,6,19,22,28,31,47,59]
      ],
      "leafGantts": [
        {
          "fCost": 4.90,
          "vehicles": [
            {"veh":1,"k":2,"t0":22.3915,"tf":24.3915,"genTime":17.5570,"actualGenTime":17.5312,"spaces":[4.0000,1.0000],"segStart":[22.3915,23.3915],"segEnd":[23.3915,24.3915]},
            {"veh":2,"k":2,"t0":19.6062,"tf":20.3916,"genTime":19.6062,"actualGenTime":19.6062,"spaces":[4.0000],"segStart":[19.6062],"segEnd":[20.3916]},
            {"veh":3,"k":1,"t0":12.2500,"tf":13.0354,"genTime":12.2500,"actualGenTime":12.2500,"spaces":[3.0000],"segStart":[12.2500],"segEnd":[13.0354]},
            {"veh":4,"k":1,"t0":14.2500,"tf":16.2500,"genTime":14.2500,"actualGenTime":14.2500,"spaces":[3.0000,4.0000],"segStart":[14.2500,15.2500],"segEnd":[15.2500,16.2500]},
            {"veh":5,"k":2,"t0":16.0353,"tf":18.0353,"genTime":16.0354,"actualGenTime":16.0353,"spaces":[2.0000,3.0000],"segStart":[16.0353,17.0353],"segEnd":[17.0353,18.0353]},
            {"veh":6,"k":2,"t0":18.0353,"tf":20.0353,"genTime":18.0354,"actualGenTime":18.0354,"spaces":[2.0000,3.0000],"segStart":[18.0353,19.0353],"segEnd":[19.0353,20.0353]},
            {"veh":7,"k":2,"t0":17.2499,"tf":18.0353,"genTime":17.2500,"actualGenTime":17.2500,"spaces":[1.0000],"segStart":[17.2499],"segEnd":[18.0353]},
            {"veh":8,"k":2,"t0":19.3679,"tf":21.3679,"genTime":19.2500,"actualGenTime":19.3778,"spaces":[1.0000,2.0000],"segStart":[19.3679,20.3679],"segEnd":[20.3679,21.3679]},
            {"veh":9,"k":3,"t0":21.3915,"tf":23.3915,"genTime":21.3915,"actualGenTime":21.3915,"spaces":[4.0000,1.0000],"segStart":[21.3915,22.3915],"segEnd":[22.3915,23.3915]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 0.18,
          "vehicles": [
            {"veh":1,"k":2,"t0":17.5162,"tf":19.5162,"genTime":17.5570,"actualGenTime":17.5312,"spaces":[4.0000,1.0000],"segStart":[17.5162,18.5162],"segEnd":[18.5162,19.5162]},
            {"veh":2,"k":2,"t0":19.6062,"tf":20.3916,"genTime":19.6062,"actualGenTime":19.6062,"spaces":[4.0000],"segStart":[19.6062],"segEnd":[20.3916]},
            {"veh":3,"k":1,"t0":12.2500,"tf":13.0354,"genTime":12.2500,"actualGenTime":12.2500,"spaces":[3.0000],"segStart":[12.2500],"segEnd":[13.0354]},
            {"veh":4,"k":1,"t0":14.2500,"tf":16.2500,"genTime":14.2500,"actualGenTime":14.2500,"spaces":[3.0000,4.0000],"segStart":[14.2500,15.2500],"segEnd":[15.2500,16.2500]},
            {"veh":5,"k":2,"t0":16.0353,"tf":18.0353,"genTime":16.0354,"actualGenTime":16.0353,"spaces":[2.0000,3.0000],"segStart":[16.0353,17.0353],"segEnd":[17.0353,18.0353]},
            {"veh":6,"k":2,"t0":18.0353,"tf":20.0353,"genTime":18.0354,"actualGenTime":18.0354,"spaces":[2.0000,3.0000],"segStart":[18.0353,19.0353],"segEnd":[19.0353,20.0353]},
            {"veh":7,"k":2,"t0":17.2499,"tf":18.0353,"genTime":17.2500,"actualGenTime":17.2500,"spaces":[1.0000],"segStart":[17.2499],"segEnd":[18.0353]},
            {"veh":8,"k":2,"t0":19.5162,"tf":21.5162,"genTime":19.2500,"actualGenTime":19.3778,"spaces":[1.0000,2.0000],"segStart":[19.5162,20.5162],"segEnd":[20.5162,21.5162]},
            {"veh":9,"k":3,"t0":21.3915,"tf":23.3915,"genTime":21.3915,"actualGenTime":21.3915,"spaces":[4.0000,1.0000],"segStart":[21.3915,22.3915],"segEnd":[22.3915,23.3915]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 5.57,
          "vehicles": [
            {"veh":1,"k":2,"t0":22.3915,"tf":24.3915,"genTime":17.5570,"actualGenTime":17.5312,"spaces":[4.0000,1.0000],"segStart":[22.3915,23.3915],"segEnd":[23.3915,24.3915]},
            {"veh":2,"k":2,"t0":19.6062,"tf":20.3916,"genTime":19.6062,"actualGenTime":19.6062,"spaces":[4.0000],"segStart":[19.6062],"segEnd":[20.3916]},
            {"veh":3,"k":1,"t0":12.2500,"tf":13.0354,"genTime":12.2500,"actualGenTime":12.2500,"spaces":[3.0000],"segStart":[12.2500],"segEnd":[13.0354]},
            {"veh":4,"k":1,"t0":14.2500,"tf":16.2500,"genTime":14.2500,"actualGenTime":14.2500,"spaces":[3.0000,4.0000],"segStart":[14.2500,15.2500],"segEnd":[15.2500,16.2500]},
            {"veh":5,"k":2,"t0":16.0353,"tf":18.0353,"genTime":16.0354,"actualGenTime":16.0353,"spaces":[2.0000,3.0000],"segStart":[16.0353,17.0353],"segEnd":[17.0353,18.0353]},
            {"veh":6,"k":2,"t0":18.0353,"tf":20.0353,"genTime":18.0354,"actualGenTime":18.0354,"spaces":[2.0000,3.0000],"segStart":[18.0353,19.0353],"segEnd":[19.0353,20.0353]},
            {"veh":7,"k":2,"t0":17.2499,"tf":18.0353,"genTime":17.2500,"actualGenTime":17.2500,"spaces":[1.0000],"segStart":[17.2499],"segEnd":[18.0353]},
            {"veh":8,"k":2,"t0":20.0353,"tf":22.0353,"genTime":19.2500,"actualGenTime":19.3778,"spaces":[1.0000,2.0000],"segStart":[20.0353,21.0353],"segEnd":[21.0353,22.0353]},
            {"veh":9,"k":3,"t0":21.3915,"tf":23.3915,"genTime":21.3915,"actualGenTime":21.3915,"spaces":[4.0000,1.0000],"segStart":[21.3915,22.3915],"segEnd":[22.3915,23.3915]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 5.66,
          "vehicles": [
            {"veh":1,"k":2,"t0":22.3915,"tf":24.3915,"genTime":17.5570,"actualGenTime":17.5312,"spaces":[4.0000,1.0000],"segStart":[22.3915,23.3915],"segEnd":[23.3915,24.3915]},
            {"veh":2,"k":2,"t0":20.3679,"tf":21.1533,"genTime":19.6062,"actualGenTime":19.6062,"spaces":[4.0000],"segStart":[20.3679],"segEnd":[21.1533]},
            {"veh":3,"k":1,"t0":12.2500,"tf":13.0354,"genTime":12.2500,"actualGenTime":12.2500,"spaces":[3.0000],"segStart":[12.2500],"segEnd":[13.0354]},
            {"veh":4,"k":1,"t0":14.2500,"tf":16.2500,"genTime":14.2500,"actualGenTime":14.2500,"spaces":[3.0000,4.0000],"segStart":[14.2500,15.2500],"segEnd":[15.2500,16.2500]},
            {"veh":5,"k":2,"t0":16.0353,"tf":18.0353,"genTime":16.0354,"actualGenTime":16.0353,"spaces":[2.0000,3.0000],"segStart":[16.0353,17.0353],"segEnd":[17.0353,18.0353]},
            {"veh":6,"k":2,"t0":18.0353,"tf":20.0353,"genTime":18.0354,"actualGenTime":18.0354,"spaces":[2.0000,3.0000],"segStart":[18.0353,19.0353],"segEnd":[19.0353,20.0353]},
            {"veh":7,"k":2,"t0":17.2499,"tf":18.0353,"genTime":17.2500,"actualGenTime":17.2500,"spaces":[1.0000],"segStart":[17.2499],"segEnd":[18.0353]},
            {"veh":8,"k":2,"t0":19.3679,"tf":21.3679,"genTime":19.2500,"actualGenTime":19.3778,"spaces":[1.0000,2.0000],"segStart":[19.3679,20.3679],"segEnd":[20.3679,21.3679]},
            {"veh":9,"k":3,"t0":21.3915,"tf":23.3915,"genTime":21.3915,"actualGenTime":21.3915,"spaces":[4.0000,1.0000],"segStart":[21.3915,22.3915],"segEnd":[22.3915,23.3915]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 5.93,
          "vehicles": [
            {"veh":1,"k":2,"t0":22.3915,"tf":24.3915,"genTime":17.5570,"actualGenTime":17.5312,"spaces":[4.0000,1.0000],"segStart":[22.3915,23.3915],"segEnd":[23.3915,24.3915]},
            {"veh":2,"k":2,"t0":19.6062,"tf":20.3916,"genTime":19.6062,"actualGenTime":19.6062,"spaces":[4.0000],"segStart":[19.6062],"segEnd":[20.3916]},
            {"veh":3,"k":1,"t0":12.2500,"tf":13.0354,"genTime":12.2500,"actualGenTime":12.2500,"spaces":[3.0000],"segStart":[12.2500],"segEnd":[13.0354]},
            {"veh":4,"k":1,"t0":14.2500,"tf":16.2500,"genTime":14.2500,"actualGenTime":14.2500,"spaces":[3.0000,4.0000],"segStart":[14.2500,15.2500],"segEnd":[15.2500,16.2500]},
            {"veh":5,"k":2,"t0":16.0353,"tf":18.0353,"genTime":16.0354,"actualGenTime":16.0353,"spaces":[2.0000,3.0000],"segStart":[16.0353,17.0353],"segEnd":[17.0353,18.0353]},
            {"veh":6,"k":2,"t0":18.0353,"tf":20.0353,"genTime":18.0354,"actualGenTime":18.0354,"spaces":[2.0000,3.0000],"segStart":[18.0353,19.0353],"segEnd":[19.0353,20.0353]},
            {"veh":7,"k":2,"t0":17.2499,"tf":18.0353,"genTime":17.2500,"actualGenTime":17.2500,"spaces":[1.0000],"segStart":[17.2499],"segEnd":[18.0353]},
            {"veh":8,"k":2,"t0":20.3916,"tf":22.3916,"genTime":19.2500,"actualGenTime":19.3778,"spaces":[1.0000,2.0000],"segStart":[20.3916,21.3916],"segEnd":[21.3916,22.3916]},
            {"veh":9,"k":3,"t0":21.3915,"tf":23.3915,"genTime":21.3915,"actualGenTime":21.3915,"spaces":[4.0000,1.0000],"segStart":[21.3915,22.3915],"segEnd":[22.3915,23.3915]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 2.36,
          "vehicles": [
            {"veh":1,"k":2,"t0":18.6062,"tf":20.6062,"genTime":17.5570,"actualGenTime":17.5312,"spaces":[4.0000,1.0000],"segStart":[18.6062,19.6062],"segEnd":[19.6062,20.6062]},
            {"veh":2,"k":2,"t0":19.6062,"tf":20.3916,"genTime":19.6062,"actualGenTime":19.6062,"spaces":[4.0000],"segStart":[19.6062],"segEnd":[20.3916]},
            {"veh":3,"k":1,"t0":12.2500,"tf":13.0354,"genTime":12.2500,"actualGenTime":12.2500,"spaces":[3.0000],"segStart":[12.2500],"segEnd":[13.0354]},
            {"veh":4,"k":1,"t0":14.2500,"tf":16.2500,"genTime":14.2500,"actualGenTime":14.2500,"spaces":[3.0000,4.0000],"segStart":[14.2500,15.2500],"segEnd":[15.2500,16.2500]},
            {"veh":5,"k":2,"t0":16.0353,"tf":18.0353,"genTime":16.0354,"actualGenTime":16.0353,"spaces":[2.0000,3.0000],"segStart":[16.0353,17.0353],"segEnd":[17.0353,18.0353]},
            {"veh":6,"k":2,"t0":18.0353,"tf":20.0353,"genTime":18.0354,"actualGenTime":18.0354,"spaces":[2.0000,3.0000],"segStart":[18.0353,19.0353],"segEnd":[19.0353,20.0353]},
            {"veh":7,"k":2,"t0":17.2499,"tf":18.0353,"genTime":17.2500,"actualGenTime":17.2500,"spaces":[1.0000],"segStart":[17.2499],"segEnd":[18.0353]},
            {"veh":8,"k":2,"t0":20.6062,"tf":22.6062,"genTime":19.2500,"actualGenTime":19.3778,"spaces":[1.0000,2.0000],"segStart":[20.6062,21.6062],"segEnd":[21.6062,22.6062]},
            {"veh":9,"k":3,"t0":21.3915,"tf":23.3915,"genTime":21.3915,"actualGenTime":21.3915,"spaces":[4.0000,1.0000],"segStart":[21.3915,22.3915],"segEnd":[22.3915,23.3915]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 2.90,
          "vehicles": [
            {"veh":1,"k":2,"t0":20.3916,"tf":22.3916,"genTime":17.5570,"actualGenTime":17.5312,"spaces":[4.0000,1.0000],"segStart":[20.3916,21.3916],"segEnd":[21.3916,22.3916]},
            {"veh":2,"k":2,"t0":19.6062,"tf":20.3916,"genTime":19.6062,"actualGenTime":19.6062,"spaces":[4.0000],"segStart":[19.6062],"segEnd":[20.3916]},
            {"veh":3,"k":1,"t0":12.2500,"tf":13.0354,"genTime":12.2500,"actualGenTime":12.2500,"spaces":[3.0000],"segStart":[12.2500],"segEnd":[13.0354]},
            {"veh":4,"k":1,"t0":14.2500,"tf":16.2500,"genTime":14.2500,"actualGenTime":14.2500,"spaces":[3.0000,4.0000],"segStart":[14.2500,15.2500],"segEnd":[15.2500,16.2500]},
            {"veh":5,"k":2,"t0":16.0353,"tf":18.0353,"genTime":16.0354,"actualGenTime":16.0353,"spaces":[2.0000,3.0000],"segStart":[16.0353,17.0353],"segEnd":[17.0353,18.0353]},
            {"veh":6,"k":2,"t0":18.0353,"tf":20.0353,"genTime":18.0354,"actualGenTime":18.0354,"spaces":[2.0000,3.0000],"segStart":[18.0353,19.0353],"segEnd":[19.0353,20.0353]},
            {"veh":7,"k":2,"t0":17.2499,"tf":18.0353,"genTime":17.2500,"actualGenTime":17.2500,"spaces":[1.0000],"segStart":[17.2499],"segEnd":[18.0353]},
            {"veh":8,"k":2,"t0":19.3679,"tf":21.3679,"genTime":19.2500,"actualGenTime":19.3778,"spaces":[1.0000,2.0000],"segStart":[19.3679,20.3679],"segEnd":[20.3679,21.3679]},
            {"veh":9,"k":3,"t0":21.3916,"tf":23.3916,"genTime":21.3915,"actualGenTime":21.3915,"spaces":[4.0000,1.0000],"segStart":[21.3916,22.3916],"segEnd":[22.3916,23.3916]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 3.57,
          "vehicles": [
            {"veh":1,"k":2,"t0":20.3916,"tf":22.3916,"genTime":17.5570,"actualGenTime":17.5312,"spaces":[4.0000,1.0000],"segStart":[20.3916,21.3916],"segEnd":[21.3916,22.3916]},
            {"veh":2,"k":2,"t0":19.6062,"tf":20.3916,"genTime":19.6062,"actualGenTime":19.6062,"spaces":[4.0000],"segStart":[19.6062],"segEnd":[20.3916]},
            {"veh":3,"k":1,"t0":12.2500,"tf":13.0354,"genTime":12.2500,"actualGenTime":12.2500,"spaces":[3.0000],"segStart":[12.2500],"segEnd":[13.0354]},
            {"veh":4,"k":1,"t0":14.2500,"tf":16.2500,"genTime":14.2500,"actualGenTime":14.2500,"spaces":[3.0000,4.0000],"segStart":[14.2500,15.2500],"segEnd":[15.2500,16.2500]},
            {"veh":5,"k":2,"t0":16.0353,"tf":18.0353,"genTime":16.0354,"actualGenTime":16.0353,"spaces":[2.0000,3.0000],"segStart":[16.0353,17.0353],"segEnd":[17.0353,18.0353]},
            {"veh":6,"k":2,"t0":18.0353,"tf":20.0353,"genTime":18.0354,"actualGenTime":18.0354,"spaces":[2.0000,3.0000],"segStart":[18.0353,19.0353],"segEnd":[19.0353,20.0353]},
            {"veh":7,"k":2,"t0":17.2499,"tf":18.0353,"genTime":17.2500,"actualGenTime":17.2500,"spaces":[1.0000],"segStart":[17.2499],"segEnd":[18.0353]},
            {"veh":8,"k":2,"t0":20.0353,"tf":22.0353,"genTime":19.2500,"actualGenTime":19.3778,"spaces":[1.0000,2.0000],"segStart":[20.0353,21.0353],"segEnd":[21.0353,22.0353]},
            {"veh":9,"k":3,"t0":21.3916,"tf":23.3916,"genTime":21.3915,"actualGenTime":21.3915,"spaces":[4.0000,1.0000],"segStart":[21.3916,22.3916],"segEnd":[22.3916,23.3916]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 3.93,
          "vehicles": [
            {"veh":1,"k":2,"t0":20.3916,"tf":22.3916,"genTime":17.5570,"actualGenTime":17.5312,"spaces":[4.0000,1.0000],"segStart":[20.3916,21.3916],"segEnd":[21.3916,22.3916]},
            {"veh":2,"k":2,"t0":19.6062,"tf":20.3916,"genTime":19.6062,"actualGenTime":19.6062,"spaces":[4.0000],"segStart":[19.6062],"segEnd":[20.3916]},
            {"veh":3,"k":1,"t0":12.2500,"tf":13.0354,"genTime":12.2500,"actualGenTime":12.2500,"spaces":[3.0000],"segStart":[12.2500],"segEnd":[13.0354]},
            {"veh":4,"k":1,"t0":14.2500,"tf":16.2500,"genTime":14.2500,"actualGenTime":14.2500,"spaces":[3.0000,4.0000],"segStart":[14.2500,15.2500],"segEnd":[15.2500,16.2500]},
            {"veh":5,"k":2,"t0":16.0353,"tf":18.0353,"genTime":16.0354,"actualGenTime":16.0353,"spaces":[2.0000,3.0000],"segStart":[16.0353,17.0353],"segEnd":[17.0353,18.0353]},
            {"veh":6,"k":2,"t0":18.0353,"tf":20.0353,"genTime":18.0354,"actualGenTime":18.0354,"spaces":[2.0000,3.0000],"segStart":[18.0353,19.0353],"segEnd":[19.0353,20.0353]},
            {"veh":7,"k":2,"t0":17.2499,"tf":18.0353,"genTime":17.2500,"actualGenTime":17.2500,"spaces":[1.0000],"segStart":[17.2499],"segEnd":[18.0353]},
            {"veh":8,"k":2,"t0":20.3916,"tf":22.3916,"genTime":19.2500,"actualGenTime":19.3778,"spaces":[1.0000,2.0000],"segStart":[20.3916,21.3916],"segEnd":[21.3916,22.3916]},
            {"veh":9,"k":3,"t0":21.3916,"tf":23.3916,"genTime":21.3915,"actualGenTime":21.3915,"spaces":[4.0000,1.0000],"segStart":[21.3916,22.3916],"segEnd":[22.3916,23.3916]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 4.41,
          "vehicles": [
            {"veh":1,"k":2,"t0":20.0353,"tf":22.0353,"genTime":17.5570,"actualGenTime":17.5312,"spaces":[4.0000,1.0000],"segStart":[20.0353,21.0353],"segEnd":[21.0353,22.0353]},
            {"veh":2,"k":2,"t0":21.0353,"tf":21.8207,"genTime":19.6062,"actualGenTime":19.6062,"spaces":[4.0000],"segStart":[21.0353],"segEnd":[21.8207]},
            {"veh":3,"k":1,"t0":12.2500,"tf":13.0354,"genTime":12.2500,"actualGenTime":12.2500,"spaces":[3.0000],"segStart":[12.2500],"segEnd":[13.0354]},
            {"veh":4,"k":1,"t0":14.2500,"tf":16.2500,"genTime":14.2500,"actualGenTime":14.2500,"spaces":[3.0000,4.0000],"segStart":[14.2500,15.2500],"segEnd":[15.2500,16.2500]},
            {"veh":5,"k":2,"t0":16.0353,"tf":18.0353,"genTime":16.0354,"actualGenTime":16.0353,"spaces":[2.0000,3.0000],"segStart":[16.0353,17.0353],"segEnd":[17.0353,18.0353]},
            {"veh":6,"k":2,"t0":18.0353,"tf":20.0353,"genTime":18.0354,"actualGenTime":18.0354,"spaces":[2.0000,3.0000],"segStart":[18.0353,19.0353],"segEnd":[19.0353,20.0353]},
            {"veh":7,"k":2,"t0":17.2499,"tf":18.0353,"genTime":17.2500,"actualGenTime":17.2500,"spaces":[1.0000],"segStart":[17.2499],"segEnd":[18.0353]},
            {"veh":8,"k":2,"t0":19.3679,"tf":21.3679,"genTime":19.2500,"actualGenTime":19.3778,"spaces":[1.0000,2.0000],"segStart":[19.3679,20.3679],"segEnd":[20.3679,21.3679]},
            {"veh":9,"k":3,"t0":21.8207,"tf":23.8207,"genTime":21.3915,"actualGenTime":21.3915,"spaces":[4.0000,1.0000],"segStart":[21.8207,22.8207],"segEnd":[22.8207,23.8207]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 5.40,
          "vehicles": [
            {"veh":1,"k":2,"t0":20.3679,"tf":22.3679,"genTime":17.5570,"actualGenTime":17.5312,"spaces":[4.0000,1.0000],"segStart":[20.3679,21.3679],"segEnd":[21.3679,22.3679]},
            {"veh":2,"k":2,"t0":21.3679,"tf":22.1533,"genTime":19.6062,"actualGenTime":19.6062,"spaces":[4.0000],"segStart":[21.3679],"segEnd":[22.1533]},
            {"veh":3,"k":1,"t0":12.2500,"tf":13.0354,"genTime":12.2500,"actualGenTime":12.2500,"spaces":[3.0000],"segStart":[12.2500],"segEnd":[13.0354]},
            {"veh":4,"k":1,"t0":14.2500,"tf":16.2500,"genTime":14.2500,"actualGenTime":14.2500,"spaces":[3.0000,4.0000],"segStart":[14.2500,15.2500],"segEnd":[15.2500,16.2500]},
            {"veh":5,"k":2,"t0":16.0353,"tf":18.0353,"genTime":16.0354,"actualGenTime":16.0353,"spaces":[2.0000,3.0000],"segStart":[16.0353,17.0353],"segEnd":[17.0353,18.0353]},
            {"veh":6,"k":2,"t0":18.0353,"tf":20.0353,"genTime":18.0354,"actualGenTime":18.0354,"spaces":[2.0000,3.0000],"segStart":[18.0353,19.0353],"segEnd":[19.0353,20.0353]},
            {"veh":7,"k":2,"t0":17.2499,"tf":18.0353,"genTime":17.2500,"actualGenTime":17.2500,"spaces":[1.0000],"segStart":[17.2499],"segEnd":[18.0353]},
            {"veh":8,"k":2,"t0":19.3679,"tf":21.3679,"genTime":19.2500,"actualGenTime":19.3778,"spaces":[1.0000,2.0000],"segStart":[19.3679,20.3679],"segEnd":[20.3679,21.3679]},
            {"veh":9,"k":3,"t0":22.1533,"tf":24.1533,"genTime":21.3915,"actualGenTime":21.3915,"spaces":[4.0000,1.0000],"segStart":[22.1533,23.1533],"segEnd":[23.1533,24.1533]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 5.93,
          "vehicles": [
            {"veh":1,"k":2,"t0":21.3916,"tf":23.3916,"genTime":17.5570,"actualGenTime":17.5312,"spaces":[4.0000,1.0000],"segStart":[21.3916,22.3916],"segEnd":[22.3916,23.3916]},
            {"veh":2,"k":2,"t0":19.6062,"tf":20.3916,"genTime":19.6062,"actualGenTime":19.6062,"spaces":[4.0000],"segStart":[19.6062],"segEnd":[20.3916]},
            {"veh":3,"k":1,"t0":12.2500,"tf":13.0354,"genTime":12.2500,"actualGenTime":12.2500,"spaces":[3.0000],"segStart":[12.2500],"segEnd":[13.0354]},
            {"veh":4,"k":1,"t0":14.2500,"tf":16.2500,"genTime":14.2500,"actualGenTime":14.2500,"spaces":[3.0000,4.0000],"segStart":[14.2500,15.2500],"segEnd":[15.2500,16.2500]},
            {"veh":5,"k":2,"t0":16.0353,"tf":18.0353,"genTime":16.0354,"actualGenTime":16.0353,"spaces":[2.0000,3.0000],"segStart":[16.0353,17.0353],"segEnd":[17.0353,18.0353]},
            {"veh":6,"k":2,"t0":18.0353,"tf":20.0353,"genTime":18.0354,"actualGenTime":18.0354,"spaces":[2.0000,3.0000],"segStart":[18.0353,19.0353],"segEnd":[19.0353,20.0353]},
            {"veh":7,"k":2,"t0":17.2499,"tf":18.0353,"genTime":17.2500,"actualGenTime":17.2500,"spaces":[1.0000],"segStart":[17.2499],"segEnd":[18.0353]},
            {"veh":8,"k":2,"t0":20.3916,"tf":22.3916,"genTime":19.2500,"actualGenTime":19.3778,"spaces":[1.0000,2.0000],"segStart":[20.3916,21.3916],"segEnd":[21.3916,22.3916]},
            {"veh":9,"k":3,"t0":22.3916,"tf":24.3916,"genTime":21.3915,"actualGenTime":21.3915,"spaces":[4.0000,1.0000],"segStart":[22.3916,23.3916],"segEnd":[23.3916,24.3916]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 6.41,
          "vehicles": [
            {"veh":1,"k":2,"t0":20.0353,"tf":22.0353,"genTime":17.5570,"actualGenTime":17.5312,"spaces":[4.0000,1.0000],"segStart":[20.0353,21.0353],"segEnd":[21.0353,22.0353]},
            {"veh":2,"k":2,"t0":22.0353,"tf":22.8207,"genTime":19.6062,"actualGenTime":19.6062,"spaces":[4.0000],"segStart":[22.0353],"segEnd":[22.8207]},
            {"veh":3,"k":1,"t0":12.2500,"tf":13.0354,"genTime":12.2500,"actualGenTime":12.2500,"spaces":[3.0000],"segStart":[12.2500],"segEnd":[13.0354]},
            {"veh":4,"k":1,"t0":14.2500,"tf":16.2500,"genTime":14.2500,"actualGenTime":14.2500,"spaces":[3.0000,4.0000],"segStart":[14.2500,15.2500],"segEnd":[15.2500,16.2500]},
            {"veh":5,"k":2,"t0":16.0353,"tf":18.0353,"genTime":16.0354,"actualGenTime":16.0353,"spaces":[2.0000,3.0000],"segStart":[16.0353,17.0353],"segEnd":[17.0353,18.0353]},
            {"veh":6,"k":2,"t0":18.0353,"tf":20.0353,"genTime":18.0354,"actualGenTime":18.0354,"spaces":[2.0000,3.0000],"segStart":[18.0353,19.0353],"segEnd":[19.0353,20.0353]},
            {"veh":7,"k":2,"t0":17.2499,"tf":18.0353,"genTime":17.2500,"actualGenTime":17.2500,"spaces":[1.0000],"segStart":[17.2499],"segEnd":[18.0353]},
            {"veh":8,"k":2,"t0":19.3679,"tf":21.3679,"genTime":19.2500,"actualGenTime":19.3778,"spaces":[1.0000,2.0000],"segStart":[19.3679,20.3679],"segEnd":[20.3679,21.3679]},
            {"veh":9,"k":3,"t0":22.8207,"tf":24.8207,"genTime":21.3915,"actualGenTime":21.3915,"spaces":[4.0000,1.0000],"segStart":[22.8207,23.8207],"segEnd":[23.8207,24.8207]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 5.19,
          "vehicles": [
            {"veh":1,"k":2,"t0":21.1533,"tf":23.1533,"genTime":17.5570,"actualGenTime":17.5312,"spaces":[4.0000,1.0000],"segStart":[21.1533,22.1533],"segEnd":[22.1533,23.1533]},
            {"veh":2,"k":2,"t0":20.3679,"tf":21.1533,"genTime":19.6062,"actualGenTime":19.6062,"spaces":[4.0000],"segStart":[20.3679],"segEnd":[21.1533]},
            {"veh":3,"k":1,"t0":12.2500,"tf":13.0354,"genTime":12.2500,"actualGenTime":12.2500,"spaces":[3.0000],"segStart":[12.2500],"segEnd":[13.0354]},
            {"veh":4,"k":1,"t0":14.2500,"tf":16.2500,"genTime":14.2500,"actualGenTime":14.2500,"spaces":[3.0000,4.0000],"segStart":[14.2500,15.2500],"segEnd":[15.2500,16.2500]},
            {"veh":5,"k":2,"t0":16.0353,"tf":18.0353,"genTime":16.0354,"actualGenTime":16.0353,"spaces":[2.0000,3.0000],"segStart":[16.0353,17.0353],"segEnd":[17.0353,18.0353]},
            {"veh":6,"k":2,"t0":18.0353,"tf":20.0353,"genTime":18.0354,"actualGenTime":18.0354,"spaces":[2.0000,3.0000],"segStart":[18.0353,19.0353],"segEnd":[19.0353,20.0353]},
            {"veh":7,"k":2,"t0":17.2499,"tf":18.0353,"genTime":17.2500,"actualGenTime":17.2500,"spaces":[1.0000],"segStart":[17.2499],"segEnd":[18.0353]},
            {"veh":8,"k":2,"t0":19.3679,"tf":21.3679,"genTime":19.2500,"actualGenTime":19.3778,"spaces":[1.0000,2.0000],"segStart":[19.3679,20.3679],"segEnd":[20.3679,21.3679]},
            {"veh":9,"k":3,"t0":22.1533,"tf":24.1533,"genTime":21.3915,"actualGenTime":21.3915,"spaces":[4.0000,1.0000],"segStart":[22.1533,23.1533],"segEnd":[23.1533,24.1533]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 6.86,
          "vehicles": [
            {"veh":1,"k":2,"t0":22.0353,"tf":24.0353,"genTime":17.5570,"actualGenTime":17.5312,"spaces":[4.0000,1.0000],"segStart":[22.0353,23.0353],"segEnd":[23.0353,24.0353]},
            {"veh":2,"k":2,"t0":19.6062,"tf":20.3916,"genTime":19.6062,"actualGenTime":19.6062,"spaces":[4.0000],"segStart":[19.6062],"segEnd":[20.3916]},
            {"veh":3,"k":1,"t0":12.2500,"tf":13.0354,"genTime":12.2500,"actualGenTime":12.2500,"spaces":[3.0000],"segStart":[12.2500],"segEnd":[13.0354]},
            {"veh":4,"k":1,"t0":14.2500,"tf":16.2500,"genTime":14.2500,"actualGenTime":14.2500,"spaces":[3.0000,4.0000],"segStart":[14.2500,15.2500],"segEnd":[15.2500,16.2500]},
            {"veh":5,"k":2,"t0":16.0353,"tf":18.0353,"genTime":16.0354,"actualGenTime":16.0353,"spaces":[2.0000,3.0000],"segStart":[16.0353,17.0353],"segEnd":[17.0353,18.0353]},
            {"veh":6,"k":2,"t0":18.0353,"tf":20.0353,"genTime":18.0354,"actualGenTime":18.0354,"spaces":[2.0000,3.0000],"segStart":[18.0353,19.0353],"segEnd":[19.0353,20.0353]},
            {"veh":7,"k":2,"t0":17.2499,"tf":18.0353,"genTime":17.2500,"actualGenTime":17.2500,"spaces":[1.0000],"segStart":[17.2499],"segEnd":[18.0353]},
            {"veh":8,"k":2,"t0":20.0353,"tf":22.0353,"genTime":19.2500,"actualGenTime":19.3778,"spaces":[1.0000,2.0000],"segStart":[20.0353,21.0353],"segEnd":[21.0353,22.0353]},
            {"veh":9,"k":3,"t0":23.0353,"tf":25.0353,"genTime":21.3915,"actualGenTime":21.3915,"spaces":[4.0000,1.0000],"segStart":[23.0353,24.0353],"segEnd":[24.0353,25.0353]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 5.33,
          "vehicles": [
            {"veh":1,"k":2,"t0":20.0353,"tf":22.0353,"genTime":17.5570,"actualGenTime":17.5312,"spaces":[4.0000,1.0000],"segStart":[20.0353,21.0353],"segEnd":[21.0353,22.0353]},
            {"veh":2,"k":2,"t0":22.3915,"tf":23.1769,"genTime":19.6062,"actualGenTime":19.6062,"spaces":[4.0000],"segStart":[22.3915],"segEnd":[23.1769]},
            {"veh":3,"k":1,"t0":12.2500,"tf":13.0354,"genTime":12.2500,"actualGenTime":12.2500,"spaces":[3.0000],"segStart":[12.2500],"segEnd":[13.0354]},
            {"veh":4,"k":1,"t0":14.2500,"tf":16.2500,"genTime":14.2500,"actualGenTime":14.2500,"spaces":[3.0000,4.0000],"segStart":[14.2500,15.2500],"segEnd":[15.2500,16.2500]},
            {"veh":5,"k":2,"t0":16.0353,"tf":18.0353,"genTime":16.0354,"actualGenTime":16.0353,"spaces":[2.0000,3.0000],"segStart":[16.0353,17.0353],"segEnd":[17.0353,18.0353]},
            {"veh":6,"k":2,"t0":18.0353,"tf":20.0353,"genTime":18.0354,"actualGenTime":18.0354,"spaces":[2.0000,3.0000],"segStart":[18.0353,19.0353],"segEnd":[19.0353,20.0353]},
            {"veh":7,"k":2,"t0":17.2499,"tf":18.0353,"genTime":17.2500,"actualGenTime":17.2500,"spaces":[1.0000],"segStart":[17.2499],"segEnd":[18.0353]},
            {"veh":8,"k":2,"t0":19.3679,"tf":21.3679,"genTime":19.2500,"actualGenTime":19.3778,"spaces":[1.0000,2.0000],"segStart":[19.3679,20.3679],"segEnd":[20.3679,21.3679]},
            {"veh":9,"k":3,"t0":21.3915,"tf":23.3915,"genTime":21.3915,"actualGenTime":21.3915,"spaces":[4.0000,1.0000],"segStart":[21.3915,22.3915],"segEnd":[22.3915,23.3915]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 7.40,
          "vehicles": [
            {"veh":1,"k":2,"t0":20.3679,"tf":22.3679,"genTime":17.5570,"actualGenTime":17.5312,"spaces":[4.0000,1.0000],"segStart":[20.3679,21.3679],"segEnd":[21.3679,22.3679]},
            {"veh":2,"k":2,"t0":22.3679,"tf":23.1533,"genTime":19.6062,"actualGenTime":19.6062,"spaces":[4.0000],"segStart":[22.3679],"segEnd":[23.1533]},
            {"veh":3,"k":1,"t0":12.2500,"tf":13.0354,"genTime":12.2500,"actualGenTime":12.2500,"spaces":[3.0000],"segStart":[12.2500],"segEnd":[13.0354]},
            {"veh":4,"k":1,"t0":14.2500,"tf":16.2500,"genTime":14.2500,"actualGenTime":14.2500,"spaces":[3.0000,4.0000],"segStart":[14.2500,15.2500],"segEnd":[15.2500,16.2500]},
            {"veh":5,"k":2,"t0":16.0353,"tf":18.0353,"genTime":16.0354,"actualGenTime":16.0353,"spaces":[2.0000,3.0000],"segStart":[16.0353,17.0353],"segEnd":[17.0353,18.0353]},
            {"veh":6,"k":2,"t0":18.0353,"tf":20.0353,"genTime":18.0354,"actualGenTime":18.0354,"spaces":[2.0000,3.0000],"segStart":[18.0353,19.0353],"segEnd":[19.0353,20.0353]},
            {"veh":7,"k":2,"t0":17.2499,"tf":18.0353,"genTime":17.2500,"actualGenTime":17.2500,"spaces":[1.0000],"segStart":[17.2499],"segEnd":[18.0353]},
            {"veh":8,"k":2,"t0":19.3679,"tf":21.3679,"genTime":19.2500,"actualGenTime":19.3778,"spaces":[1.0000,2.0000],"segStart":[19.3679,20.3679],"segEnd":[20.3679,21.3679]},
            {"veh":9,"k":3,"t0":23.1533,"tf":25.1533,"genTime":21.3915,"actualGenTime":21.3915,"spaces":[4.0000,1.0000],"segStart":[23.1533,24.1533],"segEnd":[24.1533,25.1533]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 5.66,
          "vehicles": [
            {"veh":1,"k":2,"t0":20.3679,"tf":22.3679,"genTime":17.5570,"actualGenTime":17.5312,"spaces":[4.0000,1.0000],"segStart":[20.3679,21.3679],"segEnd":[21.3679,22.3679]},
            {"veh":2,"k":2,"t0":22.3915,"tf":23.1769,"genTime":19.6062,"actualGenTime":19.6062,"spaces":[4.0000],"segStart":[22.3915],"segEnd":[23.1769]},
            {"veh":3,"k":1,"t0":12.2500,"tf":13.0354,"genTime":12.2500,"actualGenTime":12.2500,"spaces":[3.0000],"segStart":[12.2500],"segEnd":[13.0354]},
            {"veh":4,"k":1,"t0":14.2500,"tf":16.2500,"genTime":14.2500,"actualGenTime":14.2500,"spaces":[3.0000,4.0000],"segStart":[14.2500,15.2500],"segEnd":[15.2500,16.2500]},
            {"veh":5,"k":2,"t0":16.0353,"tf":18.0353,"genTime":16.0354,"actualGenTime":16.0353,"spaces":[2.0000,3.0000],"segStart":[16.0353,17.0353],"segEnd":[17.0353,18.0353]},
            {"veh":6,"k":2,"t0":18.0353,"tf":20.0353,"genTime":18.0354,"actualGenTime":18.0354,"spaces":[2.0000,3.0000],"segStart":[18.0353,19.0353],"segEnd":[19.0353,20.0353]},
            {"veh":7,"k":2,"t0":17.2499,"tf":18.0353,"genTime":17.2500,"actualGenTime":17.2500,"spaces":[1.0000],"segStart":[17.2499],"segEnd":[18.0353]},
            {"veh":8,"k":2,"t0":19.3679,"tf":21.3679,"genTime":19.2500,"actualGenTime":19.3778,"spaces":[1.0000,2.0000],"segStart":[19.3679,20.3679],"segEnd":[20.3679,21.3679]},
            {"veh":9,"k":3,"t0":21.3915,"tf":23.3915,"genTime":21.3915,"actualGenTime":21.3915,"spaces":[4.0000,1.0000],"segStart":[21.3915,22.3915],"segEnd":[22.3915,23.3915]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":13,"tw":42.502,"f":-0.00,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": -0.00,
          "vehicles": [
            {"veh":3,"k":3,"t0":21.3915,"tf":22.1769,"genTime":21.3915,"actualGenTime":21.3915,"spaces":[3.0000],"segStart":[21.3915],"segEnd":[22.1769]},
            {"veh":5,"k":4,"t0":26.3915,"tf":28.3915,"genTime":26.3915,"actualGenTime":26.3915,"spaces":[3.0000,4.0000],"segStart":[26.3915,27.3915],"segEnd":[27.3915,28.3915]},
            {"veh":9,"k":1,"t0":12.2500,"tf":14.6062,"genTime":12.2500,"actualGenTime":12.2500,"spaces":[4.0000,5.0000,2.0000],"segStart":[12.2500,13.0354,13.8208],"segEnd":[13.0354,13.8208,14.6062]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":17,"tw":39.502,"f":-0.00,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": -0.00,
          "vehicles": [
            {"veh":2,"k":3,"t0":23.3915,"tf":25.7477,"genTime":23.3915,"actualGenTime":23.3915,"spaces":[3.0000,5.0000,1.0000],"segStart":[23.3915,24.1769,24.9623],"segEnd":[24.1769,24.9623,25.7477]},
            {"veh":4,"k":2,"t0":19.2499,"tf":21.2499,"genTime":19.2500,"actualGenTime":19.2499,"spaces":[3.0000,4.0000],"segStart":[19.2499,20.2499],"segEnd":[20.2499,21.2499]},
            {"veh":7,"k":1,"t0":12.2500,"tf":14.2500,"genTime":12.2500,"actualGenTime":12.2500,"spaces":[1.0000,2.0000],"segStart":[12.2500,13.2500],"segEnd":[13.2500,14.2500]},
            {"veh":8,"k":1,"t0":14.2500,"tf":16.2500,"genTime":14.2500,"actualGenTime":14.2500,"spaces":[1.0000,2.0000],"segStart":[14.2500,15.2500],"segEnd":[15.2500,16.2500]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "5": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":20,"tw":42.502,"f":-0.05,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": -0.05,
          "vehicles": [
            {"veh":1,"k":3,"t0":22.4349,"tf":24.4349,"genTime":22.4693,"actualGenTime":22.4541,"spaces":[4.0000,1.0000],"segStart":[22.4349,23.4349],"segEnd":[23.4349,24.4349]},
            {"veh":5,"k":1,"t0":12.2500,"tf":13.0354,"genTime":12.2500,"actualGenTime":12.2500,"spaces":[3.0000],"segStart":[12.2500],"segEnd":[13.0354]},
            {"veh":6,"k":1,"t0":14.2500,"tf":15.0354,"genTime":14.2500,"actualGenTime":14.2500,"spaces":[3.0000],"segStart":[14.2500],"segEnd":[15.0354]},
            {"veh":7,"k":3,"t0":21.0353,"tf":23.0353,"genTime":21.0353,"actualGenTime":21.0353,"spaces":[4.0000,1.0000],"segStart":[21.0353,22.0353],"segEnd":[22.0353,23.0353]},
            {"veh":9,"k":4,"t0":26.3914,"tf":28.7476,"genTime":26.3914,"actualGenTime":26.3914,"spaces":[4.0000,5.0000,2.0000],"segStart":[26.3914,27.1768,27.9622],"segEnd":[27.1768,27.9622,28.7476]}
          ],
          "numSpaces": 5
        }
      ]
    }
  }
};
