// Interactive decision-tree data — tr_15r_S3
// Auto-generated by export_interactive_tree.m
window.ALL_INTERACTIVE_TREES = window.ALL_INTERACTIVE_TREES || {};
window.ALL_INTERACTIVE_TREES["tr_15r_S3"] = {
  "numInt": 5,
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":19,"tw":40.409,"f":0.05,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 0.05,
          "vehicles": [
            {"veh":2,"k":1,"t0":13.2500,"tf":14.0354,"genTime":13.2500,"actualGenTime":13.2500,"spaces":[4.0000],"segStart":[13.2500],"segEnd":[14.0354]},
            {"veh":3,"k":1,"t0":15.2500,"tf":16.0354,"genTime":15.2500,"actualGenTime":15.2500,"spaces":[4.0000],"segStart":[15.2500],"segEnd":[16.0354]},
            {"veh":7,"k":2,"t0":20.6061,"tf":22.6061,"genTime":20.6062,"actualGenTime":20.6061,"spaces":[1.0000,2.0000],"segStart":[20.6061,21.6061],"segEnd":[21.6061,22.6061]},
            {"veh":10,"k":2,"t0":24.2980,"tf":26.2980,"genTime":24.2655,"actualGenTime":24.2744,"spaces":[1.0000,2.0000],"segStart":[24.2980,25.2980],"segEnd":[25.2980,26.2980]},
            {"veh":12,"k":1,"t0":18.2500,"tf":20.2500,"genTime":18.2500,"actualGenTime":18.2500,"spaces":[3.0000,4.0000],"segStart":[18.2500,19.2500],"segEnd":[19.2500,20.2500]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":29,"tw":42.361,"f":-0.00,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": -0.00,
          "vehicles": [
            {"veh":4,"k":1,"t0":14.2500,"tf":16.6062,"genTime":14.2500,"actualGenTime":14.2500,"spaces":[3.0000,5.0000,1.0000],"segStart":[14.2500,15.0354,15.8208],"segEnd":[15.0354,15.8208,16.6062]},
            {"veh":5,"k":1,"t0":16.2500,"tf":18.2500,"genTime":16.2500,"actualGenTime":16.2500,"spaces":[3.0000,4.0000],"segStart":[16.2500,17.2500],"segEnd":[17.2500,18.2500]},
            {"veh":6,"k":1,"t0":18.2500,"tf":20.6062,"genTime":18.2500,"actualGenTime":18.2500,"spaces":[3.0000,5.0000,1.0000],"segStart":[18.2500,19.0354,19.8208],"segEnd":[19.0354,19.8208,20.6062]},
            {"veh":11,"k":2,"t0":22.2499,"tf":23.0353,"genTime":22.2500,"actualGenTime":22.2499,"spaces":[2.0000],"segStart":[22.2499],"segEnd":[23.0353]},
            {"veh":13,"k":2,"t0":24.2499,"tf":26.2499,"genTime":24.2500,"actualGenTime":24.2499,"spaces":[1.0000,2.0000],"segStart":[24.2499,25.2499],"segEnd":[25.2499,26.2499]},
            {"veh":14,"k":2,"t0":26.2499,"tf":28.2499,"genTime":26.2500,"actualGenTime":26.2499,"spaces":[1.0000,2.0000],"segStart":[26.2499,27.2499],"segEnd":[27.2499,28.2499]},
            {"veh":15,"k":2,"t0":24.0353,"tf":26.3915,"genTime":24.0354,"actualGenTime":24.0353,"spaces":[2.0000,5.0000,4.0000],"segStart":[24.0353,24.8207,25.6061],"segEnd":[24.8207,25.6061,26.3915]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":11,"tw":18.250,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":3,"orig":12,"tw":19.035,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":4,"orig":14,"tw":19.250,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":5,"orig":15,"tw":19.821,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":6,"orig":16,"tw":20.821,"f":1.57,"isLeaf":false,"isRoot":false},
        {"id":7,"orig":39,"tw":39.361,"f":1.00,"isLeaf":true,"isRoot":false},
        {"id":8,"orig":50,"tw":39.361,"f":4.14,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [3,4],
        [3,5],
        [5,6],
        [4,7],
        [6,8]
      ],
      "optimalPath": [1,2,3,4,7],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2,3,4,7],
        [1,2,3,5,6,8]
      ],
      "leafGantts": [
        {
          "fCost": 1.00,
          "vehicles": [
            {"veh":2,"k":2,"t0":17.0353,"tf":17.8207,"genTime":17.0354,"actualGenTime":17.0353,"spaces":[3.0000],"segStart":[17.0353],"segEnd":[17.8207]},
            {"veh":3,"k":2,"t0":19.0353,"tf":19.8207,"genTime":19.0354,"actualGenTime":19.0353,"spaces":[3.0000],"segStart":[19.0353],"segEnd":[19.8207]},
            {"veh":7,"k":1,"t0":15.2500,"tf":17.6062,"genTime":15.2500,"actualGenTime":15.2500,"spaces":[4.0000,5.0000,2.0000],"segStart":[15.2500,16.0354,16.8208],"segEnd":[16.0354,16.8208,17.6062]},
            {"veh":8,"k":1,"t0":17.2500,"tf":19.2500,"genTime":17.2500,"actualGenTime":17.2500,"spaces":[4.0000,1.0000],"segStart":[17.2500,18.2500],"segEnd":[18.2500,19.2500]},
            {"veh":9,"k":1,"t0":16.2500,"tf":17.0354,"genTime":16.2500,"actualGenTime":16.2500,"spaces":[1.0000],"segStart":[16.2500],"segEnd":[17.0354]},
            {"veh":10,"k":1,"t0":19.2500,"tf":21.2500,"genTime":18.2500,"actualGenTime":18.2500,"spaces":[1.0000,2.0000],"segStart":[19.2500,20.2500],"segEnd":[20.2500,21.2500]},
            {"veh":12,"k":2,"t0":23.2499,"tf":24.0353,"genTime":23.2500,"actualGenTime":23.2499,"spaces":[3.0000],"segStart":[23.2499],"segEnd":[24.0353]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 4.14,
          "vehicles": [
            {"veh":2,"k":2,"t0":17.0353,"tf":17.8207,"genTime":17.0354,"actualGenTime":17.0353,"spaces":[3.0000],"segStart":[17.0353],"segEnd":[17.8207]},
            {"veh":3,"k":2,"t0":19.0353,"tf":19.8207,"genTime":19.0354,"actualGenTime":19.0353,"spaces":[3.0000],"segStart":[19.0353],"segEnd":[19.8207]},
            {"veh":7,"k":1,"t0":15.2500,"tf":17.6062,"genTime":15.2500,"actualGenTime":15.2500,"spaces":[4.0000,5.0000,2.0000],"segStart":[15.2500,16.0354,16.8208],"segEnd":[16.0354,16.8208,17.6062]},
            {"veh":8,"k":1,"t0":18.8207,"tf":20.8207,"genTime":17.2500,"actualGenTime":17.2500,"spaces":[4.0000,1.0000],"segStart":[18.8207,19.8207],"segEnd":[19.8207,20.8207]},
            {"veh":9,"k":1,"t0":16.2500,"tf":17.0354,"genTime":16.2500,"actualGenTime":16.2500,"spaces":[1.0000],"segStart":[16.2500],"segEnd":[17.0354]},
            {"veh":10,"k":1,"t0":20.8207,"tf":22.8207,"genTime":18.2500,"actualGenTime":18.2500,"spaces":[1.0000,2.0000],"segStart":[20.8207,21.8207],"segEnd":[21.8207,22.8207]},
            {"veh":12,"k":2,"t0":23.2499,"tf":24.0353,"genTime":23.2500,"actualGenTime":23.2499,"spaces":[3.0000],"segStart":[23.2499],"segEnd":[24.0353]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":14,"tw":22.784,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":3,"orig":16,"tw":23.250,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":4,"orig":20,"tw":23.305,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":5,"orig":36,"tw":45.502,"f":1.11,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [3,4],
        [4,5]
      ],
      "optimalPath": [1,2,3,4,5],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2,3,4,5]
      ],
      "leafGantts": [
        {
          "fCost": 1.11,
          "vehicles": [
            {"veh":1,"k":1,"t0":12.2500,"tf":14.6062,"genTime":12.2500,"actualGenTime":12.2500,"spaces":[2.0000,5.0000,4.0000],"segStart":[12.2500,13.0354,13.8208],"segEnd":[13.0354,13.8208,14.6062]},
            {"veh":5,"k":2,"t0":22.3047,"tf":24.3047,"genTime":21.2500,"actualGenTime":21.7821,"spaces":[3.0000,4.0000],"segStart":[22.3047,23.3047],"segEnd":[23.3047,24.3047]},
            {"veh":8,"k":2,"t0":22.3047,"tf":24.3047,"genTime":22.2873,"actualGenTime":22.3007,"spaces":[4.0000,1.0000],"segStart":[22.3047,23.3047],"segEnd":[23.3047,24.3047]},
            {"veh":9,"k":2,"t0":20.0353,"tf":20.8207,"genTime":20.0354,"actualGenTime":20.0353,"spaces":[4.0000],"segStart":[20.0353],"segEnd":[20.8207]},
            {"veh":13,"k":1,"t0":19.2500,"tf":21.2500,"genTime":19.2500,"actualGenTime":19.2500,"spaces":[1.0000,2.0000],"segStart":[19.2500,20.2500],"segEnd":[20.2500,21.2500]},
            {"veh":14,"k":1,"t0":21.2500,"tf":23.2500,"genTime":21.2500,"actualGenTime":21.2500,"spaces":[1.0000,2.0000],"segStart":[21.2500,22.2500],"segEnd":[22.2500,23.2500]},
            {"veh":15,"k":3,"t0":29.3915,"tf":31.3915,"genTime":29.3915,"actualGenTime":29.3915,"spaces":[3.0000,4.0000],"segStart":[29.3915,30.3915],"segEnd":[30.3915,31.3915]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "5": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":17,"tw":39.717,"f":-0.00,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": -0.00,
          "vehicles": [
            {"veh":4,"k":2,"t0":19.6061,"tf":21.9623,"genTime":19.6062,"actualGenTime":19.6061,"spaces":[4.0000,5.0000,2.0000],"segStart":[19.6061,20.3915,21.1769],"segEnd":[20.3915,21.1769,21.9623]},
            {"veh":6,"k":2,"t0":23.6061,"tf":25.6061,"genTime":23.6062,"actualGenTime":23.6061,"spaces":[4.0000,1.0000],"segStart":[23.6061,24.6061],"segEnd":[24.6061,25.6061]},
            {"veh":11,"k":1,"t0":17.2500,"tf":19.2500,"genTime":17.2500,"actualGenTime":17.2500,"spaces":[2.0000,3.0000],"segStart":[17.2500,18.2500],"segEnd":[18.2500,19.2500]},
            {"veh":15,"k":1,"t0":20.2500,"tf":21.0354,"genTime":20.2500,"actualGenTime":20.2500,"spaces":[3.0000],"segStart":[20.2500],"segEnd":[21.0354]}
          ],
          "numSpaces": 5
        }
      ]
    }
  }
};
