// Decision-tree data (5-int) — group=15r  scene=S3
// Auto-generated by export_tree_json_5int.m — do not edit manually.
window.ALL_TREE_DATA = window.ALL_TREE_DATA || {};
window.ALL_TREE_DATA["tr_15r_S3"] = {
  "group": "15r", "scene": "S3",
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":19,"tw":40.409,"f":0.048,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":29,"tw":42.361,"f":-0.000,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":11,"tw":18.250,"f":-0.000,"isPath":true},
        {"id":3,"orig":12,"tw":19.035,"f":-0.000,"isPath":true},
        {"id":4,"orig":13,"tw":19.035,"f":-0.000,"isPath":false},
        {"id":5,"orig":14,"tw":19.250,"f":-0.000,"isPath":true},
        {"id":6,"orig":15,"tw":19.821,"f":-0.000,"isPath":false},
        {"id":7,"orig":16,"tw":20.821,"f":1.571,"isPath":false},
        {"id":8,"orig":17,"tw":20.035,"f":-0.000,"isPath":false},
        {"id":9,"orig":18,"tw":21.035,"f":2.571,"isPath":false},
        {"id":10,"orig":19,"tw":19.821,"f":-0.000,"isPath":false},
        {"id":11,"orig":20,"tw":19.250,"f":-0.000,"isPath":false},
        {"id":12,"orig":21,"tw":20.035,"f":0.785,"isPath":false},
        {"id":13,"orig":22,"tw":20.821,"f":-0.000,"isPath":false},
        {"id":14,"orig":23,"tw":21.821,"f":4.141,"isPath":false},
        {"id":15,"orig":28,"tw":20.250,"f":1.000,"isPath":false},
        {"id":16,"orig":30,"tw":22.035,"f":2.571,"isPath":false},
        {"id":17,"orig":39,"tw":39.361,"f":1.000,"isPath":true},
        {"id":18,"orig":50,"tw":39.361,"f":4.141,"isPath":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [3,5],
        [3,6],
        [6,7],
        [6,8],
        [8,9],
        [4,10],
        [4,11],
        [10,12],
        [10,13],
        [13,14],
        [11,15],
        [12,16],
        [5,17],
        [7,18]
      ],
      "path": [1,2,3,5,17]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":14,"tw":22.784,"f":-0.000,"isPath":true},
        {"id":3,"orig":15,"tw":23.250,"f":-0.000,"isPath":false},
        {"id":4,"orig":16,"tw":23.250,"f":-0.000,"isPath":true},
        {"id":5,"orig":17,"tw":23.784,"f":0.534,"isPath":false},
        {"id":6,"orig":18,"tw":24.250,"f":-0.000,"isPath":false},
        {"id":7,"orig":19,"tw":24.250,"f":1.000,"isPath":false},
        {"id":8,"orig":20,"tw":23.305,"f":-0.000,"isPath":true},
        {"id":9,"orig":21,"tw":25.250,"f":3.000,"isPath":false},
        {"id":10,"orig":24,"tw":25.784,"f":2.069,"isPath":false},
        {"id":11,"orig":26,"tw":26.250,"f":3.000,"isPath":false},
        {"id":12,"orig":36,"tw":45.502,"f":1.109,"isPath":true}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [3,5],
        [3,6],
        [4,7],
        [4,8],
        [6,9],
        [5,10],
        [7,11],
        [8,12]
      ],
      "path": [1,2,4,8,12]
    },
    "5": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":17,"tw":39.717,"f":-0.000,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    }
  }
};
