// Decision-tree data (5-int) — group=15r  scene=S2
// Auto-generated by export_tree_json_5int.m — do not edit manually.
window.ALL_TREE_DATA = window.ALL_TREE_DATA || {};
window.ALL_TREE_DATA["tr_15r_S2"] = {
  "group": "15r", "scene": "S2",
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":3,"tw":15.250,"f":0.000,"isPath":true},
        {"id":3,"orig":4,"tw":16.250,"f":0.000,"isPath":false},
        {"id":4,"orig":5,"tw":16.250,"f":0.000,"isPath":true},
        {"id":5,"orig":10,"tw":17.821,"f":0.000,"isPath":false},
        {"id":6,"orig":11,"tw":18.606,"f":-0.000,"isPath":false},
        {"id":7,"orig":12,"tw":18.250,"f":1.000,"isPath":false},
        {"id":8,"orig":13,"tw":19.606,"f":2.356,"isPath":false},
        {"id":9,"orig":15,"tw":19.035,"f":1.429,"isPath":false},
        {"id":10,"orig":32,"tw":46.361,"f":1.000,"isPath":true}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [3,5],
        [5,6],
        [5,7],
        [6,8],
        [7,9],
        [4,10]
      ],
      "path": [1,2,4,10]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":31,"tw":41.361,"f":-0.000,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":33,"tw":42.361,"f":0.072,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":9,"tw":19.668,"f":-0.000,"isPath":true},
        {"id":3,"orig":10,"tw":20.077,"f":0.041,"isPath":true},
        {"id":4,"orig":11,"tw":20.250,"f":-0.000,"isPath":false},
        {"id":5,"orig":12,"tw":21.035,"f":1.000,"isPath":false},
        {"id":6,"orig":13,"tw":20.668,"f":0.418,"isPath":false},
        {"id":7,"orig":25,"tw":37.361,"f":0.868,"isPath":true},
        {"id":8,"orig":26,"tw":21.250,"f":1.000,"isPath":false},
        {"id":9,"orig":27,"tw":21.250,"f":1.000,"isPath":false},
        {"id":10,"orig":28,"tw":22.035,"f":1.000,"isPath":false},
        {"id":11,"orig":29,"tw":22.250,"f":2.000,"isPath":false},
        {"id":12,"orig":31,"tw":23.035,"f":3.785,"isPath":false},
        {"id":13,"orig":32,"tw":22.250,"f":1.000,"isPath":false},
        {"id":14,"orig":33,"tw":23.250,"f":4.000,"isPath":false},
        {"id":15,"orig":41,"tw":37.361,"f":1.837,"isPath":false},
        {"id":16,"orig":42,"tw":23.250,"f":2.000,"isPath":false},
        {"id":17,"orig":43,"tw":23.250,"f":2.000,"isPath":false},
        {"id":18,"orig":44,"tw":24.250,"f":7.000,"isPath":false},
        {"id":19,"orig":46,"tw":25.250,"f":7.000,"isPath":false},
        {"id":20,"orig":50,"tw":25.035,"f":8.356,"isPath":false},
        {"id":21,"orig":55,"tw":37.361,"f":6.785,"isPath":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [4,5],
        [4,6],
        [3,7],
        [5,8],
        [5,9],
        [8,10],
        [8,11],
        [10,12],
        [10,13],
        [9,14],
        [6,15],
        [11,16],
        [11,17],
        [16,18],
        [17,19],
        [12,20],
        [13,21]
      ],
      "path": [1,2,3,7]
    },
    "5": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":16,"tw":38.717,"f":-0.000,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    }
  }
};
