// Decision-tree data (5-int) — group=15r  scene=S1
// Auto-generated by export_tree_json_5int.m — do not edit manually.
window.ALL_TREE_DATA = window.ALL_TREE_DATA || {};
window.ALL_TREE_DATA["tr_15r_S1"] = {
  "group": "15r", "scene": "S1",
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":24,"tw":41.479,"f":0.118,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":29,"tw":43.361,"f":-0.000,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":4,"tw":17.250,"f":0.000,"isPath":true},
        {"id":3,"orig":5,"tw":18.250,"f":0.000,"isPath":false},
        {"id":4,"orig":6,"tw":18.250,"f":0.000,"isPath":true},
        {"id":5,"orig":10,"tw":20.250,"f":1.000,"isPath":false},
        {"id":6,"orig":26,"tw":43.146,"f":1.000,"isPath":true}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [3,5],
        [4,6]
      ],
      "path": [1,2,4,6]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":27,"tw":50.717,"f":-0.000,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "5": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":16,"tw":37.717,"f":-0.000,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    }
  }
};
