// Decision-tree data — group=25r  scene=S1
// Auto-generated by export_tree_json.m — do not edit manually.
window.ALL_TREE_DATA = window.ALL_TREE_DATA || {};
window.ALL_TREE_DATA["25r_S1"] = {
  "group": "25r", "scene": "S1",
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":48,"tw":40.610,"f":2.297,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":37,"tw":32.004,"f":1.571,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":3,"tw":2.785,"f":0.000,"isPath":true},
        {"id":3,"orig":4,"tw":3.571,"f":0.000,"isPath":true},
        {"id":4,"orig":5,"tw":3.571,"f":0.000,"isPath":false},
        {"id":5,"orig":9,"tw":5.142,"f":0.785,"isPath":false},
        {"id":6,"orig":48,"tw":31.326,"f":2.508,"isPath":true}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [4,5],
        [3,6]
      ],
      "path": [1,2,3,6]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":42,"tw":35.182,"f":0.636,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    }
  }
};
