// Decision-tree data — group=10r  scene=S1_p9
// Auto-generated by export_tree_json.m — do not edit manually.
window.ALL_TREE_DATA = window.ALL_TREE_DATA || {};
window.ALL_TREE_DATA["10r_S1_p9"] = {
  "group": "10r", "scene": "S1_p9",
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":15,"tw":26.488,"f":-0.033,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":13,"tw":8.069,"f":-0.000,"isPath":true},
        {"id":3,"orig":14,"tw":8.356,"f":-0.000,"isPath":false},
        {"id":4,"orig":15,"tw":8.353,"f":-0.003,"isPath":true},
        {"id":5,"orig":19,"tw":9.069,"f":0.284,"isPath":false},
        {"id":6,"orig":20,"tw":9.142,"f":0.785,"isPath":false},
        {"id":7,"orig":21,"tw":9.142,"f":0.284,"isPath":false},
        {"id":8,"orig":22,"tw":9.855,"f":0.284,"isPath":false},
        {"id":9,"orig":34,"tw":24.467,"f":0.565,"isPath":true},
        {"id":10,"orig":35,"tw":9.927,"f":0.785,"isPath":false},
        {"id":11,"orig":36,"tw":10.142,"f":2.142,"isPath":false},
        {"id":12,"orig":37,"tw":10.712,"f":0.785,"isPath":false},
        {"id":13,"orig":44,"tw":24.467,"f":2.356,"isPath":false},
        {"id":14,"orig":50,"tw":24.467,"f":3.426,"isPath":false},
        {"id":15,"orig":55,"tw":24.467,"f":3.712,"isPath":false},
        {"id":16,"orig":60,"tw":24.467,"f":4.852,"isPath":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [3,5],
        [3,6],
        [5,7],
        [5,8],
        [4,9],
        [6,10],
        [10,11],
        [10,12],
        [11,13],
        [7,14],
        [12,15],
        [8,16]
      ],
      "path": [1,2,4,9]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":12,"tw":7.801,"f":0.023,"isPath":true},
        {"id":3,"orig":13,"tw":8.801,"f":0.824,"isPath":false},
        {"id":4,"orig":14,"tw":8.594,"f":0.023,"isPath":true},
        {"id":5,"orig":22,"tw":22.919,"f":3.210,"isPath":true},
        {"id":6,"orig":27,"tw":22.919,"f":3.624,"isPath":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [4,5],
        [3,6]
      ],
      "path": [1,2,4,5]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":8,"tw":7.205,"f":0.000,"isPath":true},
        {"id":3,"orig":9,"tw":7.990,"f":0.000,"isPath":false},
        {"id":4,"orig":10,"tw":7.612,"f":0.000,"isPath":true},
        {"id":5,"orig":17,"tw":22.531,"f":0.868,"isPath":true},
        {"id":6,"orig":20,"tw":22.531,"f":1.624,"isPath":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [4,5],
        [3,6]
      ],
      "path": [1,2,4,5]
    }
  }
};
