function export_interactive_tree(matFile, out_js, numInt, group, scene)
% export_interactive_tree  Export decision-tree + gantt data for interactive demo.
%
% Usage:
%   export_interactive_tree('BatchRuns\manual_10r\...mat', '...js', 4, '10r', 'S1')
%
% INPUTS
%   matFile  — path to ADMM .mat file
%   out_js   — output .js file path
%   numInt   — number of intersections (default: 4)
%   group    — group key e.g. '10r' (default: '')
%   scene    — scene key e.g. 'S1' (default: '')

if nargin < 3, numInt = 4; end
if nargin < 4, group = ''; end
if nargin < 5, scene = ''; end

fprintf('Loading %s ...\n', matFile);
S = load(matFile);

LocalTreeCache = S.LocalTreeCache;
const          = S.const;
x_prev         = S.x_prev;

IntSpaceDB           = const.IntSpaceDB;
pathInfo             = const.pathInfo;
pathInfo_agent_chain = const.pathInfo_agent_chain;
alpha_tilde          = const.alpha_tilde;
Dt                   = const.Dt;
kn                   = 1;

fid = fopen(out_js, 'w');
if fid < 0, error('Cannot open: %s', out_js); end

treeKey = sprintf('%s_%s', group, scene);  % e.g. '10r_S1'

fprintf(fid, '// Interactive decision-tree data — %s\n', treeKey);
fprintf(fid, '// Auto-generated by export_interactive_tree.m\n');
fprintf(fid, 'window.ALL_INTERACTIVE_TREES = window.ALL_INTERACTIVE_TREES || {};\n');
fprintf(fid, 'window.ALL_INTERACTIVE_TREES["%s"] = {\n', treeKey);
fprintf(fid, '  "numInt": %d,\n', numInt);
fprintf(fid, '  "intersections": {\n');

for agent_i = 1:numInt
    if agent_i > 1, fprintf(fid, ',\n'); end

    cache = LocalTreeCache{agent_i};
    if isempty(cache) || ~isstruct(cache) || ~isfield(cache, 'NODES')
        fprintf(fid, '    "%d": null', agent_i);
        fprintf('  Int %d: no data\n', agent_i);
        continue;
    end

    NODES         = cache.NODES;
    optimalPath   = cache.Path;
    valid_systems = cache.valid_systems;
    num_nodes     = size(NODES, 1);

    % ── Build children map ──────────────────────────────────────────────
    children = cell(num_nodes, 1);
    for i = 1:num_nodes
        p = NODES{i}{7};
        if p > 0 && p <= num_nodes
            children{p} = [children{p}, i];
        end
    end

    % ── Identify branch/leaf nodes ─────────────────────────────────────
    is_branch = false(num_nodes, 1);
    is_leaf   = false(num_nodes, 1);
    for i = 1:num_nodes
        nc = numel(children{i});
        if nc >= 2, is_branch(i) = true; end
        if nc == 0, is_leaf(i)   = true; end
    end

    % ── Find COMPLETE leaves first (all vehicles scheduled) ────────────
    numExpectedVeh = 0;
    for idx = 1:numel(valid_systems)
        n = valid_systems(idx);
        chain = pathInfo_agent_chain{n}{kn};
        if any(chain == agent_i), numExpectedVeh = numExpectedVeh + 1; end
    end

    raw_leaf_indices = find(is_leaf);
    leaf_indices = [];
    for li = 1:numel(raw_leaf_indices)
        orig_leaf = raw_leaf_indices(li);
        gamma_leaf = NODES{orig_leaf}{11};
        nScheduled = 0;
        for idx = 1:numel(valid_systems)
            n = valid_systems(idx);
            chain = pathInfo_agent_chain{n}{kn};
            if ~any(chain == agent_i), continue; end
            if iscell(gamma_leaf) && numel(gamma_leaf) >= n && ...
                    ~isempty(gamma_leaf{n})
                g = gamma_leaf{n};
                if numel(g) >= 1 && g(end) > 0
                    nScheduled = nScheduled + 1;
                end
            end
        end
        if nScheduled >= numExpectedVeh
            leaf_indices(end+1) = orig_leaf; %#ok<AGROW>
        end
    end
    numLeaves = numel(leaf_indices);

    % ── Trace full paths (original indices) for each complete leaf ──────
    all_full_paths = cell(numLeaves, 1);
    on_complete_path = false(num_nodes, 1);
    for li = 1:numLeaves
        path_orig = leaf_indices(li);
        cur = leaf_indices(li);
        while NODES{cur}{7} > 0
            cur = NODES{cur}{7};
            path_orig = [cur, path_orig]; %#ok<AGROW>
        end
        all_full_paths{li} = path_orig;
        on_complete_path(path_orig) = true;
    end

    % ── Build display nodes: only nodes on complete paths ──────────────
    is_display = false(num_nodes, 1);
    is_display(1) = true;  % always show root
    for i = 1:num_nodes
        if ~on_complete_path(i), continue; end
        if is_branch(i)
            is_display(i) = true;
            % Only show children that are on complete paths
            for c = children{i}
                if on_complete_path(c), is_display(c) = true; end
            end
        end
        if is_leaf(i) && any(leaf_indices == i)
            is_display(i) = true;
        end
    end

    display_nodes = find(is_display);
    nd = numel(display_nodes);

    old2new = zeros(num_nodes, 1);
    for k = 1:nd
        old2new(display_nodes(k)) = k;
    end

    % ── Compressed edges (only between display nodes) ──────────────────
    edges_src = [];
    edges_dst = [];
    for k = 1:nd
        orig = display_nodes(k);
        if orig == 1, continue; end
        p = NODES{orig}{7};
        while p > 0 && ~is_display(p)
            p = NODES{p}{7};
        end
        if p > 0 && is_display(p)
            edges_src(end+1) = old2new(p);   %#ok<AGROW>
            edges_dst(end+1) = old2new(orig); %#ok<AGROW>
        end
    end

    % ── Leaf paths in compressed indices ────────────────────────────────
    all_paths = cell(numLeaves, 1);
    for li = 1:numLeaves
        path_comp = [];
        for pp = 1:numel(all_full_paths{li})
            cn = old2new(all_full_paths{li}(pp));
            if cn > 0
                path_comp(end+1) = cn; %#ok<AGROW>
            end
        end
        all_paths{li} = path_comp;
    end

    % ── Optimal path in compressed indices ──────────────────────────────
    opt_path_comp = [];
    if ~isempty(optimalPath)
        for pp = 1:numel(optimalPath)
            cn = old2new(optimalPath(pp));
            if cn > 0
                opt_path_comp(end+1) = cn; %#ok<AGROW>
            end
        end
    end

    % ── Identify which leaf is optimal ──────────────────────────────────
    optLeafIdx = 0;
    if ~isempty(opt_path_comp)
        optLeafComp = opt_path_comp(end);
        for li = 1:numLeaves
            if all_paths{li}(end) == optLeafComp
                optLeafIdx = li;
                break;
            end
        end
    end

    % ── Extract gantt data for each leaf path ───────────────────────────
    gantt_data = cell(numLeaves, 1);
    for li = 1:numLeaves
        orig_leaf = leaf_indices(li);
        gamma_leaf = NODES{orig_leaf}{11};
        gantt_data{li} = extract_gantt_for_leaf(agent_i, gamma_leaf, ...
            valid_systems, IntSpaceDB, pathInfo, pathInfo_agent_chain, ...
            alpha_tilde, x_prev, Dt, const, kn);
    end

    % ── Node info ───────────────────────────────────────────────────────
    fprintf(fid, '    "%d": {\n', agent_i);

    % nodes
    fprintf(fid, '      "nodes": [\n');
    for k = 1:nd
        orig = display_nodes(k);
        tw_val = NODES{orig}{5};
        f_val  = NODES{orig}{12};
        nodeIsLeaf = is_leaf(orig);
        nodeIsRoot = (orig == 1);
        comma = ''; if k < nd, comma = ','; end
        fprintf(fid, '        {"id":%d,"orig":%d,"tw":%.3f,"f":%.2f,"isLeaf":%s,"isRoot":%s}%s\n', ...
            k, orig, tw_val, f_val, b2s(nodeIsLeaf), b2s(nodeIsRoot), comma);
    end
    fprintf(fid, '      ],\n');

    % edges
    fprintf(fid, '      "edges": [\n');
    ne = numel(edges_src);
    for e = 1:ne
        comma = ''; if e < ne, comma = ','; end
        fprintf(fid, '        [%d,%d]%s\n', edges_src(e), edges_dst(e), comma);
    end
    fprintf(fid, '      ],\n');

    % optimal path
    fprintf(fid, '      "optimalPath": [');
    fprintf(fid, '%s', strjoin(arrayfun(@num2str, opt_path_comp, 'UniformOutput', false), ','));
    fprintf(fid, '],\n');
    fprintf(fid, '      "optimalLeaf": %d,\n', optLeafIdx);

    % all leaf paths
    fprintf(fid, '      "leafPaths": [\n');
    for li = 1:numLeaves
        comma = ''; if li < numLeaves, comma = ','; end
        fprintf(fid, '        [%s]%s\n', ...
            strjoin(arrayfun(@num2str, all_paths{li}, 'UniformOutput', false), ','), comma);
    end
    fprintf(fid, '      ],\n');

    % gantt data for each leaf
    fprintf(fid, '      "leafGantts": [\n');
    for li = 1:numLeaves
        comma = ''; if li < numLeaves, comma = ','; end
        gd = gantt_data{li};
        fprintf(fid, '        {\n');

        % f-cost of this leaf
        orig_leaf = leaf_indices(li);
        fprintf(fid, '          "fCost": %.2f,\n', NODES{orig_leaf}{12});

        % vehicle items
        fprintf(fid, '          "vehicles": [\n');
        for vi = 1:numel(gd.vehicles)
            v = gd.vehicles(vi);
            vc = ''; if vi < numel(gd.vehicles), vc = ','; end
            fprintf(fid, '            {"veh":%d,"k":%d,"t0":%.4f,"tf":%.4f,"genTime":%.4f,"actualGenTime":%.4f,', ...
                v.veh, v.k, v.t0, v.tf, v.genTime, v.actualGenTime);
            fprintf(fid, '"spaces":[%s],"segStart":[%s],"segEnd":[%s]}%s\n', ...
                mat2str_inline(v.spaces), mat2str_inline(v.segStart), mat2str_inline(v.segEnd), vc);
        end
        fprintf(fid, '          ],\n');

        % zone occupancy (numSpaces)
        fprintf(fid, '          "numSpaces": %d\n', gd.numSpaces);
        fprintf(fid, '        }%s\n', comma);
    end
    fprintf(fid, '      ]\n');

    fprintf(fid, '    }');
    fprintf('  Int %d: %d display nodes, %d leaves\n', agent_i, nd, numLeaves);
end

fprintf(fid, '\n  }\n};\n');
fclose(fid);
fprintf('Done: %s\n', out_js);
end

%% ── Extract gantt chart data for one leaf ──────────────────────────────────
function gd = extract_gantt_for_leaf(agent_i, gamma_leaf, valid_systems, ...
    IntSpaceDB, pathInfo, pathInfo_agent_chain, alpha_tilde, x_prev, Dt, const, kn)

numSpaces = IntSpaceDB{agent_i}.numSpaces;
vehicles = struct('veh',{},'k',{},'t0',{},'tf',{},'genTime',{},'actualGenTime',{},...
    'spaces',{},'segStart',{},'segEnd',{});

for idx = 1:numel(valid_systems)
    n = valid_systems(idx);
    chain = pathInfo_agent_chain{n}{kn};
    posi = find(chain == agent_i, 1, 'first');
    if isempty(posi), continue; end

    pos_int = (posi + 1) / 2;
    routeId = pathInfo{n}.routeId(pos_int);

    space_seq = IntSpaceDB{agent_i}.routeSpace{routeId};
    dur_seq   = IntSpaceDB{agent_i}.routeDur{routeId};
    if isempty(space_seq) || isempty(dur_seq), continue; end

    tf = fetch_gamma(gamma_leaf, n, idx);
    if isempty(tf) || ~isfinite(tf), continue; end

    t0 = tf - sum(dur_seq);

    segStart = zeros(1, numel(dur_seq));
    segEnd   = zeros(1, numel(dur_seq));
    tcur = t0;
    for q = 1:numel(dur_seq)
        segStart(q) = tcur;
        segEnd(q)   = tcur + dur_seq(q);
        tcur = segEnd(q);
    end

    % Generation time
    genTime = NaN;
    if posi == 1
        if iscell(alpha_tilde{n})
            genTime = alpha_tilde{n}{kn};
        else
            genTime = alpha_tilde{n}(kn);
        end
    else
        prev_road = chain(posi - 1);
        if ~isempty(x_prev) && numel(x_prev) >= prev_road && ...
                ~isempty(x_prev{prev_road}) && numel(x_prev{prev_road}) >= n && ...
                ~isempty(x_prev{prev_road}{n})
            xroad = x_prev{prev_road}{n};
            if iscell(xroad), xroad = xroad{kn};
            elseif numel(xroad) >= kn, xroad = xroad(kn); end
            genTime = xroad + Dt;
        end
    end

    % Actual generation time used by ADMM local tree:
    %   - First intersection (posi==1): just alpha_tilde, no road to average with
    %   - Subsequent intersections: (x_prev{road} + Dt + x_prev{int}) / 2
    actualGenTime = NaN;
    if posi == 1
        % No previous road → actual gen time = theoretical gen time
        actualGenTime = genTime;
    else
        % Get x_prev{agent_i}{n} — intersection's own x_prev
        x_int = NaN;
        if ~isempty(x_prev) && numel(x_prev) >= agent_i && ...
                ~isempty(x_prev{agent_i}) && numel(x_prev{agent_i}) >= n && ...
                ~isempty(x_prev{agent_i}{n})
            xi = x_prev{agent_i}{n};
            if iscell(xi), xi = xi{kn};
            elseif numel(xi) >= kn, xi = xi(kn); end
            x_int = xi;
        end
        if isfinite(genTime) && isfinite(x_int)
            actualGenTime = (genTime + x_int) / 2;
        end
    end

    vehicles(end+1) = struct('veh', n, 'k', pos_int, ...
        't0', t0, 'tf', tf, 'genTime', genTime, 'actualGenTime', actualGenTime, ...
        'spaces', space_seq, 'segStart', segStart, 'segEnd', segEnd); %#ok<AGROW>
end

% Sort by vehicle id
if ~isempty(vehicles)
    [~, ord] = sort([vehicles.veh]);
    vehicles = vehicles(ord);
end

gd.vehicles  = vehicles;
gd.numSpaces = numSpaces;
end

%% ── Helpers ────────────────────────────────────────────────────────────────
function val = fetch_gamma(gamma, n, idx)
    val = [];
    if iscell(gamma)
        if numel(gamma) >= n && ~isempty(gamma{n})
            g = gamma{n};
            if numel(g) >= 1
                val = g(end);  % last entry
                % Skip unscheduled vehicles (gamma=0 means not yet processed)
                if val <= 0, val = []; end
            end
        end
    end
end

function s = b2s(b)
    if b, s = 'true'; else, s = 'false'; end
end

function s = mat2str_inline(v)
    s = strjoin(arrayfun(@(x) sprintf('%.4f', x), v, 'UniformOutput', false), ',');
end
