function export_tree_json(LocalTreeCache, group, scene, out_path)
% export_tree_json  Export filtered decision-tree data for 4 intersections
%                  as a JavaScript variable declaration file.
%
% The file declares:  var TREE_DATA = { ... };
% The HTML renderer reads this to draw interactive SVG trees.
%
% INPUTS
%   LocalTreeCache  cell(9,1) — LocalTreeCache{1..4} used
%   group           string e.g. '10r'
%   scene           string e.g. 'S1'
%   out_path        full path to output .js file

fid = fopen(out_path, 'w');
if fid < 0
    error('export_tree_json: cannot open for writing: %s', out_path);
end

fprintf(fid, '// Decision-tree data — group=%s  scene=%s\n', group, scene);
fprintf(fid, '// Auto-generated by export_tree_json.m — do not edit manually.\n');
fprintf(fid, 'window.ALL_TREE_DATA = window.ALL_TREE_DATA || {};\n');
fprintf(fid, 'window.ALL_TREE_DATA["%s_%s"] = {\n', group, scene);
fprintf(fid, '  "group": "%s", "scene": "%s",\n', group, scene);
fprintf(fid, '  "intersections": {\n');

for agent_i = 1:4
    if agent_i > 1
        fprintf(fid, ',\n');
    end

    cache = LocalTreeCache{agent_i};

    if isempty(cache) || ~isstruct(cache) || ~isfield(cache, 'NODES')
        fprintf(fid, '    "%d": null', agent_i);
        continue;
    end

    NODES     = cache.NODES;
    Path      = cache.Path;
    num_nodes = size(NODES, 1);

    % ── Build children map ──────────────────────────────────────────────
    children = cell(num_nodes, 1);
    for i = 1:num_nodes
        p = NODES{i}{7};
        if p > 0 && p <= num_nodes
            children{p} = [children{p}, i];
        end
    end

    % ── Identify display nodes (same logic as plot_decision_tree_panel) ─
    is_branch = false(num_nodes, 1);
    is_leaf   = false(num_nodes, 1);
    for i = 1:num_nodes
        nc = numel(children{i});
        if nc >= 2, is_branch(i) = true; end
        if nc == 0, is_leaf(i)   = true; end
    end

    is_display    = false(num_nodes, 1);
    is_display(1) = true;
    for i = 1:num_nodes
        if is_branch(i)
            is_display(i)           = true;
            is_display(children{i}) = true;
        end
        if is_leaf(i)
            is_display(i) = true;
        end
    end

    display_nodes = find(is_display);
    nd = numel(display_nodes);

    % Map original NODES index → 1-based compressed index
    old2new = zeros(num_nodes, 1);
    for k = 1:nd
        old2new(display_nodes(k)) = k;
    end

    % ── Compressed edges (1-based compressed indices) ───────────────────
    src_list = [];
    dst_list = [];
    for k = 1:nd
        orig = display_nodes(k);
        if orig == 1, continue; end
        p = NODES{orig}{7};
        while p > 0 && ~is_display(p)
            p = NODES{p}{7};
        end
        if p > 0 && is_display(p)
            src_list = [src_list, old2new(p)];   %#ok<AGROW>
            dst_list = [dst_list, old2new(orig)]; %#ok<AGROW>
        end
    end

    % ── Optimal path in compressed indices ──────────────────────────────
    path_comp = [];
    if ~isempty(Path)
        valid_mask = (Path >= 1) & (Path <= num_nodes) & is_display(Path)';
        path_disp  = Path(valid_mask);
        path_comp  = old2new(path_disp);
        path_comp  = path_comp(path_comp > 0);
    end
    path_set = false(nd, 1);
    if ~isempty(path_comp)
        path_set(path_comp) = true;
    end

    % ── Write JSON object ────────────────────────────────────────────────
    fprintf(fid, '    "%d": {\n', agent_i);

    % nodes array
    fprintf(fid, '      "nodes": [\n');
    for k = 1:nd
        orig   = display_nodes(k);
        tw_val = NODES{orig}{5};
        f_val  = NODES{orig}{12};
        comma  = ''; if k < nd, comma = ','; end
        fprintf(fid, '        {"id":%d,"orig":%d,"tw":%.3f,"f":%.3f,"isPath":%s}%s\n', ...
            k, orig, tw_val, f_val, bool2str(path_set(k)), comma);
    end
    fprintf(fid, '      ],\n');

    % edges array
    fprintf(fid, '      "edges": [\n');
    ne = numel(src_list);
    for e = 1:ne
        comma = ''; if e < ne, comma = ','; end
        fprintf(fid, '        [%d,%d]%s\n', src_list(e), dst_list(e), comma);
    end
    fprintf(fid, '      ],\n');

    % path array (compact, one line)
    fprintf(fid, '      "path": [');
    if ~isempty(path_comp)
        fprintf(fid, '%d', path_comp(1));
        for k = 2:numel(path_comp)
            fprintf(fid, ',%d', path_comp(k));
        end
    end
    fprintf(fid, ']\n');

    fprintf(fid, '    }');
end

fprintf(fid, '\n  }\n};\n');
fclose(fid);
fprintf('Tree JS exported: %s\n', out_path);
end

% ── helper ──────────────────────────────────────────────────────────────────
function s = bool2str(b)
if b, s = 'true'; else, s = 'false'; end
end
