"""
Port of export_tree_json.m + export_interactive_tree.m.

Generates the two .js files demo's "Tree" panel needs for a given case:
  schedules/tree_<group>_<scene>_optimal.js          (static viewer)
  schedules/interactive_tree_<group>_<scene>.js      (interactive explorer)

Input is the per-int LocalTreeCache from ADMM (a list[n_agents] of dicts
containing 'NODES' and 'Path' from the converged ADMM run).
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import List


def _bool(b: bool) -> str:
    return 'true' if b else 'false'


def export_tree_static_js(local_tree_cache, group: str, scene: str,
                           out_path) -> Path:
    """Mirror of export_tree_json.m. 4-int focused (uses agents 0..3)."""
    out_path = Path(out_path).with_suffix('.js')
    out_path.parent.mkdir(parents=True, exist_ok=True)

    lines: List[str] = []
    lines.append(f'// Decision-tree data — group={group}  scene={scene}')
    lines.append('// Auto-generated by export_tree_to_demo.py — do not edit manually.')
    lines.append('window.ALL_TREE_DATA = window.ALL_TREE_DATA || {};')
    lines.append(f'window.ALL_TREE_DATA["{group}_{scene}"] = {{')
    lines.append(f'  "group": "{group}", "scene": "{scene}",')
    lines.append('  "intersections": {')

    int_blocks = []
    for agent_i in range(4):   # always 4 ints in 2x2 demo
        cache = (local_tree_cache[agent_i]
                 if agent_i < len(local_tree_cache) else None)
        if not cache or 'NODES' not in cache or not cache['NODES']:
            int_blocks.append(f'    "{agent_i + 1}": null')
            continue

        NODES = cache['NODES']
        Path_list = cache.get('Path') or []
        # NODES[0] is a sentinel None; real nodes live at NODES[1..max_idx]
        # with NODES[i].idx == i and NODES[i].parent in 1..max_idx (0 = root).
        max_idx = len(NODES) - 1

        # Build children map (1-indexed parent → list of 1-indexed children)
        children = [[] for _ in range(max_idx + 1)]
        for i in range(1, max_idx + 1):
            if NODES[i] is None: continue
            p = NODES[i].parent
            if 1 <= p <= max_idx:
                children[p].append(i)

        is_branch = [False] * (max_idx + 1)
        is_leaf   = [False] * (max_idx + 1)
        for i in range(1, max_idx + 1):
            if NODES[i] is None: continue
            nc = len(children[i])
            if nc >= 2: is_branch[i] = True
            if nc == 0: is_leaf[i] = True

        is_display = [False] * (max_idx + 1)
        if max_idx >= 1 and NODES[1] is not None:
            is_display[1] = True
        for i in range(1, max_idx + 1):
            if NODES[i] is None: continue
            if is_branch[i]:
                is_display[i] = True
                for c in children[i]:
                    is_display[c] = True
            if is_leaf[i]:
                is_display[i] = True

        display_nodes = [i for i in range(1, max_idx + 1) if is_display[i]]
        nd = len(display_nodes)

        # Map idx → compressed (1-based, in display order)
        old2new = [0] * (max_idx + 1)
        for k, orig in enumerate(display_nodes, start=1):
            old2new[orig] = k

        # Compressed edges
        src_list, dst_list = [], []
        for orig in display_nodes:
            if orig == 1: continue
            p = NODES[orig].parent
            while 1 <= p <= max_idx and NODES[p] is not None and not is_display[p]:
                p = NODES[p].parent
            if 1 <= p <= max_idx and NODES[p] is not None and is_display[p]:
                src_list.append(old2new[p])
                dst_list.append(old2new[orig])

        # Optimal path → compressed
        path_comp = []
        for orig in Path_list:
            if 1 <= orig <= max_idx and NODES[orig] is not None and is_display[orig]:
                cc = old2new[orig]
                if cc > 0:
                    path_comp.append(cc)
        path_set = set(path_comp)

        # Per-int JSON
        node_lines = []
        for k, orig in enumerate(display_nodes, start=1):
            node = NODES[orig]
            tw = float(node.tw); f = float(node.f)
            comma = ',' if k < nd else ''
            node_lines.append(
                f'        {{"id":{k},"orig":{orig},"tw":{tw:.3f},"f":{f:.3f},'
                f'"isPath":{_bool(k in path_set)}}}{comma}')
        edge_lines = []
        for e, (s, d) in enumerate(zip(src_list, dst_list)):
            comma = ',' if e < len(src_list) - 1 else ''
            edge_lines.append(f'        [{s},{d}]{comma}')

        # Trivial-tree visibility fix
        if nd == 1 and node_lines:
            line0 = node_lines[0].rstrip(',').rstrip()
            import re as _re
            o_m = _re.search(r'"orig":(\d+)', line0)
            t_m = _re.search(r'"tw":([\d.\-]+)', line0)
            f_m = _re.search(r'"f":([\d.\-]+)', line0)
            if o_m and t_m and f_m:
                orig = int(o_m.group(1)); tw = float(t_m.group(1)); f = float(f_m.group(1))
                node_lines = [
                    f'        {{"id":1,"orig":{orig},"tw":{tw:.3f},"f":{f:.3f},"isPath":true}},',
                    f'        {{"id":2,"orig":{orig},"tw":{tw:.3f},"f":{f:.3f},"isPath":true}}',
                ]
                edge_lines = ['        [1,2]']
                path_comp = [1, 2]

        block = [
            f'    "{agent_i + 1}": {{',
            '      "nodes": [',
            *node_lines,
            '      ],',
            '      "edges": [',
            *edge_lines,
            '      ],',
            '      "path": [' + ','.join(str(x) for x in path_comp) + ']',
            '    }',
        ]
        int_blocks.append('\n'.join(block))

    lines.append(',\n'.join(int_blocks))
    lines.append('  }')
    lines.append('};')
    out_path.write_text('\n'.join(lines) + '\n')
    print(f'Tree static JS exported: {out_path}')
    return out_path


# ───────────────────────────────────────────────────────────────────────
# Interactive tree (Port of export_interactive_tree.m)
# ───────────────────────────────────────────────────────────────────────


def _to_list(v):
    return v if isinstance(v, list) else [v]


def _extract_gantt_for_leaf(agent_i, gamma_leaf, valid_systems, const,
                              x_prev, y_prev=None, use_admm_solution=False) -> dict:
    """Mirror of MATLAB extract_gantt_for_leaf."""
    IntSpaceDB = const['IntSpaceDB']
    pathInfo   = const['pathInfo']
    chains     = [const['pathInfo_agent_chain'][n][0] for n in range(const['N'])]
    alpha_tilde = const['alpha_tilde']
    Dt         = float(const['Dt'])
    n_int      = const['n_int']

    db        = IntSpaceDB[agent_i]
    numSpaces = db['numSpaces']
    vehicles  = []

    for n in valid_systems:
        chain = chains[n]
        try:
            posi = chain.index(agent_i)   # 0-based agent position in chain
        except ValueError:
            continue

        # Count intersections up to and including this one
        pos_int = sum(1 for a in chain[:posi + 1] if a < n_int) - 1
        rids = list(pathInfo[n].get('routeId', []))
        if pos_int >= len(rids):
            continue
        rId = int(rids[pos_int])

        rs = db['routeSpace']
        rd = db['routeDur']
        space_seq = list(rs[rId] if isinstance(rs, dict) else rs[rId - 1])
        dur_seq   = list(rd[rId] if isinstance(rd, dict) else rd[rId - 1])
        if not space_seq or not dur_seq:
            continue

        # Fetch γ — for the ADMM-converged path use y_prev (true converged
        # solution); for other leaves use the local tree's gamma.
        tf = None
        if use_admm_solution and y_prev is not None:
            yv = y_prev[agent_i][n] if (agent_i < len(y_prev) and n < len(y_prev[agent_i])) else None
            if yv is not None and len(yv) > 0:
                tf = float(yv[0])
        if tf is None:
            if n >= len(gamma_leaf) or gamma_leaf[n] is None:
                continue
            g = gamma_leaf[n]
            try:
                tf = float(g if not hasattr(g, '__len__') else g[-1])
            except Exception:
                continue
        if tf <= 0 or not (tf == tf):
            continue

        t0 = tf - sum(dur_seq)
        segStart, segEnd = [], []
        cur = t0
        for d in dur_seq:
            segStart.append(cur); segEnd.append(cur + d); cur += d

        # Generation time
        genTime = float('nan')
        if posi == 0:
            at = alpha_tilde[n]
            try:
                genTime = float(at[0])
            except (TypeError, IndexError):
                genTime = float(at)
        else:
            prev_road = chain[posi - 1]
            if (x_prev and prev_road < len(x_prev) and
                    n < len(x_prev[prev_road]) and
                    x_prev[prev_road][n] is not None and
                    len(x_prev[prev_road][n]) > 0):
                genTime = float(x_prev[prev_road][n][0]) + Dt

        # Actual generation time (averaged with int's own x_prev)
        actualGenTime = float('nan')
        if posi == 0:
            actualGenTime = genTime
        else:
            x_int = float('nan')
            if (x_prev and agent_i < len(x_prev) and
                    n < len(x_prev[agent_i]) and
                    x_prev[agent_i][n] is not None and
                    len(x_prev[agent_i][n]) > 0):
                x_int = float(x_prev[agent_i][n][0])
            if (genTime == genTime) and (x_int == x_int):
                actualGenTime = (genTime + x_int) / 2.0

        vehicles.append({
            'veh': int(n) + 1,    # 1-indexed to match MATLAB convention (N1-N20)
            'k': int(pos_int + 1),
            't0': float(t0), 'tf': float(tf),
            'genTime': float(genTime), 'actualGenTime': float(actualGenTime),
            'spaces': [int(s) for s in space_seq],
            'segStart': [float(x) for x in segStart],
            'segEnd':   [float(x) for x in segEnd],
        })

    vehicles.sort(key=lambda v: v['veh'])
    return {'vehicles': vehicles, 'numSpaces': int(numSpaces)}


def _ensure_two_nodes(node_lines, edge_lines, display_nodes_count, NODES,
                       leaf_indices, is_leaf, opt_orig=None):
    """When the compressed tree has only 1 node (trivial / no contention),
    synthesize a duplicate so the demo can render at least root → leaf.
    Returns (new_node_lines, new_edge_lines, new_count, opt_path_extra)."""
    if display_nodes_count != 1 or not node_lines:
        return node_lines, edge_lines, display_nodes_count, []
    # Duplicate the single node as id=2 with same data, mark as leaf.
    line0 = node_lines[0].rstrip(',').rstrip()
    # Quick parse: extract orig/tw/f from the formatted JSON line.
    import re
    orig_m = re.search(r'"orig":(\d+)', line0)
    tw_m   = re.search(r'"tw":([\d.\-]+)', line0)
    f_m    = re.search(r'"f":([\d.\-]+)', line0)
    if not (orig_m and tw_m and f_m):
        return node_lines, edge_lines, display_nodes_count, []
    orig = int(orig_m.group(1)); tw = float(tw_m.group(1)); f = float(f_m.group(1))
    # Modify line0: not a leaf anymore (it's now root)
    new0 = (f'        {{"id":1,"orig":{orig},"tw":{tw:.3f},"f":{f:.2f},'
            f'"isLeaf":false,"isRoot":true}},')
    new1 = (f'        {{"id":2,"orig":{orig},"tw":{tw:.3f},"f":{f:.2f},'
            f'"isLeaf":true,"isRoot":false}}')
    return [new0, new1], ['        [1,2]'], 2, [1, 2]


def export_tree_interactive_js(local_tree_cache, const, x_prev,
                                 group: str, scene: str,
                                 out_path, num_int: int = 4,
                                 y_prev=None) -> Path:
    """Mirror of export_interactive_tree.m. Generates per-leaf gantt data."""
    out_path = Path(out_path).with_suffix('.js')
    out_path.parent.mkdir(parents=True, exist_ok=True)

    chains = [const['pathInfo_agent_chain'][n][0] for n in range(const['N'])]
    treeKey = f'{group}_{scene}'

    lines: List[str] = []
    lines.append(f'// Interactive decision-tree data — {treeKey}')
    lines.append('// Auto-generated by export_tree_to_demo.py')
    lines.append('window.ALL_INTERACTIVE_TREES = window.ALL_INTERACTIVE_TREES || {};')
    lines.append(f'window.ALL_INTERACTIVE_TREES["{treeKey}"] = {{')
    lines.append(f'  "numInt": {num_int},')
    lines.append('  "intersections": {')

    int_blocks = []
    for agent_i in range(num_int):
        cache = (local_tree_cache[agent_i]
                 if agent_i < len(local_tree_cache) else None)
        if not cache or 'NODES' not in cache or not cache['NODES']:
            int_blocks.append(f'    "{agent_i + 1}": null')
            continue

        NODES = cache['NODES']
        Path_list = cache.get('Path') or []
        valid_systems = cache.get('valid_systems') or list(range(const['N']))
        num_nodes = len(NODES)

        max_idx = len(NODES) - 1   # NODES[0] = None sentinel
        children = [[] for _ in range(max_idx + 1)]
        for i in range(1, max_idx + 1):
            if NODES[i] is None: continue
            p = NODES[i].parent
            if 1 <= p <= max_idx:
                children[p].append(i)

        is_branch = [False] * (max_idx + 1)
        is_leaf   = [False] * (max_idx + 1)
        for i in range(1, max_idx + 1):
            if NODES[i] is None: continue
            nc = len(children[i])
            if nc >= 2: is_branch[i] = True
            if nc == 0: is_leaf[i] = True

        numExpectedVeh = sum(1 for n in valid_systems if agent_i in chains[n])

        # Find COMPLETE leaves
        leaf_indices = []
        for orig_leaf in range(1, max_idx + 1):
            if NODES[orig_leaf] is None: continue
            if not is_leaf[orig_leaf]: continue
            gamma_leaf = NODES[orig_leaf].gamma
            nScheduled = 0
            for n in valid_systems:
                if agent_i not in chains[n]: continue
                if n < len(gamma_leaf) and gamma_leaf[n] is not None:
                    g = gamma_leaf[n]
                    g_last = g if not hasattr(g, '__len__') else (g[-1] if len(g) else 0)
                    if g_last and g_last > 0: nScheduled += 1
            if nScheduled >= numExpectedVeh:
                leaf_indices.append(orig_leaf)

        # ADMM leaf first
        admm_leaf = Path_list[-1] if Path_list else None
        if (admm_leaf is not None and 1 <= admm_leaf <= max_idx
                and NODES[admm_leaf] is not None):
            rest = [li for li in leaf_indices if li != admm_leaf]
            rest.sort(key=lambda li: float(NODES[li].f))
            leaf_indices = [admm_leaf] + rest
        else:
            leaf_indices.sort(key=lambda li: float(NODES[li].f))
        numLeaves = len(leaf_indices)

        # Trace path from each leaf to root via parent links
        all_full_paths = []
        on_complete_path = [False] * (max_idx + 1)
        for orig_leaf in leaf_indices:
            path_orig = [orig_leaf]
            cur = orig_leaf
            # NODES[i].parent is 1-indexed; 0 means root (no parent)
            while NODES[cur] is not None and NODES[cur].parent > 0:
                cur = NODES[cur].parent
                path_orig.insert(0, cur)
            all_full_paths.append(path_orig)
            for x in path_orig:
                on_complete_path[x] = True

        # Display nodes
        is_display = [False] * (max_idx + 1)
        if max_idx >= 1 and NODES[1] is not None:
            is_display[1] = True
        for i in range(1, max_idx + 1):
            if NODES[i] is None: continue
            if not on_complete_path[i]: continue
            if is_branch[i]:
                is_display[i] = True
                for c in children[i]:
                    if on_complete_path[c]:
                        is_display[c] = True
            if is_leaf[i] and i in leaf_indices:
                is_display[i] = True

        display_nodes = [i for i in range(1, max_idx + 1) if is_display[i]]
        nd = len(display_nodes)
        old2new = [0] * (max_idx + 1)
        for k, orig in enumerate(display_nodes, start=1):
            old2new[orig] = k

        # Compressed edges
        edges_src, edges_dst = [], []
        for orig in display_nodes:
            if orig == 1: continue
            p = NODES[orig].parent
            while 1 <= p <= max_idx and NODES[p] is not None and not is_display[p]:
                p = NODES[p].parent
            if 1 <= p <= max_idx and NODES[p] is not None and is_display[p]:
                edges_src.append(old2new[p])
                edges_dst.append(old2new[orig])

        # Leaf paths in compressed indices
        all_paths = []
        for path_orig in all_full_paths:
            path_comp = [old2new[o] for o in path_orig if old2new[o] > 0]
            all_paths.append(path_comp)

        # Optimal path in compressed
        opt_path_comp = [old2new[o] for o in Path_list
                          if 1 <= o <= max_idx and NODES[o] is not None
                          and old2new[o] > 0]

        # Identify which leaf is optimal
        optLeafIdx = 0
        if opt_path_comp:
            opt_leaf_comp = opt_path_comp[-1]
            for li, p in enumerate(all_paths, start=1):
                if p and p[-1] == opt_leaf_comp:
                    optLeafIdx = li
                    break

        # Per-leaf gantt data — Path 1 (ADMM leaf) uses x_prev/y_prev for the
        # converged solution; other paths use leaf.gamma. fCost is the LOCAL
        # delay at this int (sum of vehicle wait = β - genTime).
        gantt_data = []
        for li_idx, orig_leaf in enumerate(leaf_indices):
            node = NODES[orig_leaf]
            if node is None: continue
            is_admm_path = (li_idx == 0 and orig_leaf == admm_leaf)
            gd = _extract_gantt_for_leaf(agent_i, node.gamma, valid_systems,
                                          const, x_prev,
                                          y_prev=y_prev,
                                          use_admm_solution=is_admm_path)
            local_delay = sum(max(0.0, v['t0'] - v['genTime'])
                               for v in gd['vehicles']
                               if v['genTime'] == v['genTime'])
            gantt_data.append((gd, float(local_delay)))

        # Build per-int JSON block
        node_lines = []
        for k, orig in enumerate(display_nodes, start=1):
            node = NODES[orig]
            tw = float(node.tw); f = float(node.f)
            comma = ',' if k < nd else ''
            node_lines.append(
                f'        {{"id":{k},"orig":{orig},"tw":{tw:.3f},"f":{f:.2f},'
                f'"isLeaf":{_bool(is_leaf[orig])},"isRoot":{_bool(orig == 1)}}}{comma}')
        edge_lines = []
        for e, (s, d) in enumerate(zip(edges_src, edges_dst)):
            comma = ',' if e < len(edges_src) - 1 else ''
            edge_lines.append(f'        [{s},{d}]{comma}')

        # If trivial (1 node), promote it to root + duplicate leaf for visibility.
        node_lines, edge_lines, nd_eff, synth_path = _ensure_two_nodes(
            node_lines, edge_lines, nd, NODES, leaf_indices, is_leaf)
        if synth_path:
            # Replace single-node leaf paths with the synthetic [1,2] path.
            all_paths = [synth_path for _ in all_paths] if all_paths else [synth_path]
            opt_path_comp = synth_path
            optLeafIdx = 1 if numLeaves >= 1 else 0

        leaf_path_lines = []
        for li, p in enumerate(all_paths, start=1):
            comma = ',' if li < numLeaves else ''
            leaf_path_lines.append(f'        [{",".join(str(x) for x in p)}]{comma}')

        leaf_gantt_lines = []
        for li, (gd, fcost) in enumerate(gantt_data, start=1):
            comma = ',' if li < numLeaves else ''
            veh_lines = []
            for vi, v in enumerate(gd['vehicles']):
                vc = ',' if vi < len(gd['vehicles']) - 1 else ''
                spaces_str = ','.join(str(x) for x in v['spaces'])
                segS = ','.join(f'{x:.4f}' for x in v['segStart'])
                segE = ','.join(f'{x:.4f}' for x in v['segEnd'])
                veh_lines.append(
                    f'            {{"veh":{v["veh"]},"k":{v["k"]},'
                    f'"t0":{v["t0"]:.4f},"tf":{v["tf"]:.4f},'
                    f'"genTime":{v["genTime"]:.4f},"actualGenTime":{v["actualGenTime"]:.4f},'
                    f'"spaces":[{spaces_str}],"segStart":[{segS}],"segEnd":[{segE}]}}{vc}')
            leaf_gantt_lines.extend([
                '        {',
                f'          "fCost": {fcost:.2f},',
                '          "vehicles": [',
                *veh_lines,
                '          ],',
                f'          "numSpaces": {gd["numSpaces"]}',
                '        }' + comma,
            ])

        block = [
            f'    "{agent_i + 1}": {{',
            '      "nodes": [',
            *node_lines,
            '      ],',
            '      "edges": [',
            *edge_lines,
            '      ],',
            '      "optimalPath": [' + ','.join(str(x) for x in opt_path_comp) + '],',
            f'      "optimalLeaf": {optLeafIdx},',
            '      "leafPaths": [',
            *leaf_path_lines,
            '      ],',
            '      "leafGantts": [',
            *leaf_gantt_lines,
            '      ]',
            '    }',
        ]
        int_blocks.append('\n'.join(block))
        print(f'  Int {agent_i + 1}: {nd} display nodes, {numLeaves} leaves')

    lines.append(',\n'.join(int_blocks))
    lines.append('  }')
    lines.append('};')
    out_path.write_text('\n'.join(lines) + '\n')
    print(f'Interactive tree JS exported: {out_path}')
    return out_path
