%% export_scenario_to_demo_5int.m
% Export one 5-intersection ADMM scheduling result to the HTML demo.
% All output files use a 'tr_' prefix to avoid collisions with warehouse files.
%
% Usage (run from five_intersection/):
%   export_scenario_to_demo_5int('5int_seed42005_N15', '15r', 'S1')
%   export_scenario_to_demo_5int('5int_seed42001_N15', '15r', 'S2')
%   export_scenario_to_demo_5int('5int_manual_10r',   '10r', 'S1')
%   export_scenario_to_demo_5int('5int_seed42003_N20', '20r', 'S1')
%   export_scenario_to_demo_5int('5int_seed42005_N20', '20r', 'S2')
%
% Arguments:
%   caseName — folder name under BatchRuns/, e.g. '5int_seed42005_N15'
%   group    — HTML group key, e.g. '15r'
%   scene    — HTML scene key, e.g. 'S1' / 'S2'

function export_scenario_to_demo_5int(caseName, group, scene)

paths = setup_five_intersection();
DEMO_DIR = paths.demoDir;
IMG_DIR   = fullfile(DEMO_DIR, 'images');
CASE_DIR  = fullfile(paths.batchDir, caseName);
if ~exist(DEMO_DIR, 'dir'), mkdir(DEMO_DIR); end
if ~exist(IMG_DIR,  'dir'), mkdir(IMG_DIR);  end

pfx      = sprintf('%s_%s', group, scene);   % e.g. '15r_S1'
tr_pfx   = sprintf('tr_%s', pfx);            % e.g. 'tr_15r_S1'
ADMM_MAT = fullfile(CASE_DIR, sprintf('5int_ADMM_%s.mat', caseName));
FCFS_MAT = fullfile(CASE_DIR, sprintf('FCFS_%s.mat', caseName));

%% ── Load ADMM ──────────────────────────────────────────────────────────────
if ~exist(ADMM_MAT, 'file')
    error('MAT file not found: %s', ADMM_MAT);
end
fprintf('Loading %s ...\n', ADMM_MAT);
load(ADMM_MAT);   % loads: const, x_prev, y_prev, LocalTreeCache,
                  %        residual_r, residual_s, delay_costs, k

%% ── Copy schedule images (already generated by MAIN) ────────────────────
fprintf('Copying schedule images...\n');
macro_src = fullfile(CASE_DIR, sprintf('macro_%s.png', caseName));
local_src = fullfile(CASE_DIR, sprintf('local_%s.png', caseName));
fcfs_src  = fullfile(CASE_DIR, sprintf('fcfs_%s.png',  caseName));

if exist(macro_src, 'file')
    copyfile(macro_src, fullfile(IMG_DIR, sprintf('%s_optimal_macro.png', tr_pfx)));
    fprintf('  -> macro image copied\n');
else
    fprintf('  [skip] macro image not found: %s\n', macro_src);
end
if exist(local_src, 'file')
    copyfile(local_src, fullfile(IMG_DIR, sprintf('%s_optimal_local.png', tr_pfx)));
    fprintf('  -> local image copied\n');
else
    fprintf('  [skip] local image not found: %s\n', local_src);
end
if exist(fcfs_src, 'file')
    copyfile(fcfs_src, fullfile(IMG_DIR, sprintf('%s_fcfs_local.png', tr_pfx)));
    fprintf('  -> fcfs image copied\n');
else
    fprintf('  [skip] fcfs image not found: %s\n', fcfs_src);
end

%% ── Decision tree JSON (5 intersections) ────────────────────────────────
fprintf('Tree JSON (5 intersections)...\n');
export_tree_json_5int(LocalTreeCache, group, scene, ...
    fullfile(DEMO_DIR, sprintf('tr_tree_%s_optimal.js', pfx)));

%% ── ADMM demo JS ─────────────────────────────────────────────────────────
fprintf('Exporting ADMM demo JS...\n');
export_demo_json(const, x_prev, y_prev, ...
    sprintf('%s · %s · Optimal', group, scene), ...
    fullfile(DEMO_DIR, sprintf('%s_optimal.js', tr_pfx)), ...
    'optimal', 0);

%% ── FCFS ─────────────────────────────────────────────────────────────────
if exist(FCFS_MAT, 'file')
    fprintf('Loading FCFS: %s\n', FCFS_MAT);
    fcfs_data  = load(FCFS_MAT);   % isolated — won't overwrite workspace
    const_fcfs = fcfs_data.const_fcfs;
    DATA_fcfs  = fcfs_data.DATA_fcfs;
    export_demo_json_fcfs(const_fcfs, DATA_fcfs, ...
        sprintf('%s · %s · FCFS', group, scene), ...
        fullfile(DEMO_DIR, sprintf('%s_fcfs.js', tr_pfx)), 'fcfs');
    fprintf('  -> FCFS done\n');
else
    fprintf('[skip] No FCFS MAT found: %s\n', FCFS_MAT);
end

%% ── Done ─────────────────────────────────────────────────────────────────
fprintf('\n=== Done: %s → %s (files prefixed tr_) ===\n', caseName, pfx);
fprintf('\nFiles generated:\n');
fprintf('  schedules/%s_optimal.js\n', tr_pfx);
if exist(FCFS_MAT, 'file')
    fprintf('  schedules/%s_fcfs.js\n', tr_pfx);
end
fprintf('  schedules/tr_tree_%s_optimal.js\n', pfx);
fprintf('  schedules/images/%s_optimal_macro.png\n', tr_pfx);
fprintf('  schedules/images/%s_optimal_local.png\n', tr_pfx);
if exist(FCFS_MAT, 'file')
    fprintf('  schedules/images/%s_fcfs_local.png\n', tr_pfx);
end
fprintf('\nRun all 5 scenarios:\n');
fprintf('  export_scenario_to_demo_5int(''5int_manual_10r'',   ''10r'', ''S1'')\n');
fprintf('  export_scenario_to_demo_5int(''5int_seed42005_N15'', ''15r'', ''S1'')\n');
fprintf('  export_scenario_to_demo_5int(''5int_seed42001_N15'', ''15r'', ''S2'')\n');
fprintf('  export_scenario_to_demo_5int(''5int_seed42003_N20'', ''20r'', ''S1'')\n');
fprintf('  export_scenario_to_demo_5int(''5int_seed42005_N20'', ''20r'', ''S2'')\n');
end
