// Interactive decision-tree data — 20r_S1
// Auto-generated by export_tree_to_demo.py
window.ALL_INTERACTIVE_TREES = window.ALL_INTERACTIVE_TREES || {};
window.ALL_INTERACTIVE_TREES["20r_S1"] = {
  "numInt": 4,
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":9,"tw":6.571,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":3,"orig":10,"tw":7.000,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":4,"orig":11,"tw":7.000,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":5,"orig":17,"tw":8.571,"f":0.43,"isLeaf":false,"isRoot":false},
        {"id":6,"orig":18,"tw":8.571,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":7,"orig":19,"tw":9.000,"f":0.43,"isLeaf":false,"isRoot":false},
        {"id":8,"orig":20,"tw":9.000,"f":0.43,"isLeaf":false,"isRoot":false},
        {"id":9,"orig":21,"tw":9.000,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":10,"orig":22,"tw":9.000,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":11,"orig":25,"tw":9.000,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":12,"orig":26,"tw":9.000,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":13,"orig":29,"tw":9.356,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":14,"orig":30,"tw":9.356,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":15,"orig":31,"tw":9.785,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":16,"orig":36,"tw":9.785,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":17,"orig":38,"tw":10.000,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":18,"orig":46,"tw":10.000,"f":3.00,"isLeaf":false,"isRoot":false},
        {"id":19,"orig":62,"tw":11.000,"f":3.00,"isLeaf":false,"isRoot":false},
        {"id":20,"orig":71,"tw":11.356,"f":3.00,"isLeaf":false,"isRoot":false},
        {"id":21,"orig":72,"tw":11.356,"f":3.00,"isLeaf":false,"isRoot":false},
        {"id":22,"orig":74,"tw":11.356,"f":0.43,"isLeaf":false,"isRoot":false},
        {"id":23,"orig":78,"tw":11.356,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":24,"orig":81,"tw":11.571,"f":3.00,"isLeaf":false,"isRoot":false},
        {"id":25,"orig":84,"tw":11.785,"f":3.00,"isLeaf":false,"isRoot":false},
        {"id":26,"orig":87,"tw":11.785,"f":0.43,"isLeaf":false,"isRoot":false},
        {"id":27,"orig":92,"tw":11.785,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":28,"orig":93,"tw":11.785,"f":2.79,"isLeaf":false,"isRoot":false},
        {"id":29,"orig":106,"tw":11.356,"f":1.71,"isLeaf":false,"isRoot":false},
        {"id":30,"orig":109,"tw":12.571,"f":2.79,"isLeaf":false,"isRoot":false},
        {"id":31,"orig":115,"tw":12.571,"f":5.79,"isLeaf":false,"isRoot":false},
        {"id":32,"orig":118,"tw":12.571,"f":0.43,"isLeaf":false,"isRoot":false},
        {"id":33,"orig":123,"tw":11.785,"f":1.71,"isLeaf":false,"isRoot":false},
        {"id":34,"orig":124,"tw":12.571,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":35,"orig":127,"tw":13.000,"f":2.79,"isLeaf":false,"isRoot":false},
        {"id":36,"orig":129,"tw":13.000,"f":2.79,"isLeaf":false,"isRoot":false},
        {"id":37,"orig":135,"tw":12.785,"f":5.79,"isLeaf":false,"isRoot":false},
        {"id":38,"orig":141,"tw":13.000,"f":0.43,"isLeaf":false,"isRoot":false},
        {"id":39,"orig":147,"tw":13.000,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":40,"orig":151,"tw":13.356,"f":4.00,"isLeaf":false,"isRoot":false},
        {"id":41,"orig":152,"tw":13.785,"f":2.79,"isLeaf":false,"isRoot":false},
        {"id":42,"orig":153,"tw":13.785,"f":3.21,"isLeaf":false,"isRoot":false},
        {"id":43,"orig":173,"tw":12.571,"f":6.85,"isLeaf":false,"isRoot":false},
        {"id":44,"orig":178,"tw":13.785,"f":4.00,"isLeaf":false,"isRoot":false},
        {"id":45,"orig":179,"tw":13.785,"f":4.00,"isLeaf":false,"isRoot":false},
        {"id":46,"orig":190,"tw":13.000,"f":6.57,"isLeaf":false,"isRoot":false},
        {"id":47,"orig":200,"tw":12.927,"f":7.64,"isLeaf":false,"isRoot":false},
        {"id":48,"orig":219,"tw":13.356,"f":6.57,"isLeaf":false,"isRoot":false},
        {"id":49,"orig":220,"tw":13.356,"f":6.57,"isLeaf":false,"isRoot":false},
        {"id":50,"orig":249,"tw":17.356,"f":0.86,"isLeaf":true,"isRoot":false},
        {"id":51,"orig":285,"tw":17.356,"f":14.43,"isLeaf":true,"isRoot":false},
        {"id":52,"orig":290,"tw":17.356,"f":5.14,"isLeaf":true,"isRoot":false},
        {"id":53,"orig":293,"tw":17.356,"f":13.14,"isLeaf":true,"isRoot":false},
        {"id":54,"orig":294,"tw":17.356,"f":12.93,"isLeaf":true,"isRoot":false},
        {"id":55,"orig":295,"tw":17.356,"f":14.64,"isLeaf":true,"isRoot":false},
        {"id":56,"orig":296,"tw":17.356,"f":13.14,"isLeaf":true,"isRoot":false},
        {"id":57,"orig":301,"tw":17.356,"f":13.71,"isLeaf":true,"isRoot":false},
        {"id":58,"orig":305,"tw":17.356,"f":8.00,"isLeaf":true,"isRoot":false},
        {"id":59,"orig":306,"tw":17.356,"f":11.71,"isLeaf":true,"isRoot":false},
        {"id":60,"orig":310,"tw":17.356,"f":12.93,"isLeaf":true,"isRoot":false},
        {"id":61,"orig":311,"tw":17.356,"f":12.71,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [4,5],
        [3,6],
        [5,7],
        [5,8],
        [6,9],
        [6,10],
        [9,11],
        [10,12],
        [11,13],
        [11,14],
        [12,15],
        [13,16],
        [15,17],
        [17,18],
        [18,19],
        [19,20],
        [19,21],
        [7,22],
        [14,23],
        [20,24],
        [21,25],
        [22,26],
        [23,27],
        [23,28],
        [16,29],
        [28,30],
        [25,31],
        [26,32],
        [29,33],
        [27,34],
        [30,35],
        [30,36],
        [31,37],
        [32,38],
        [34,39],
        [35,40],
        [35,41],
        [35,42],
        [33,43],
        [40,44],
        [40,45],
        [37,46],
        [43,47],
        [46,48],
        [46,49],
        [8,50],
        [42,51],
        [38,52],
        [44,53],
        [45,54],
        [41,55],
        [36,56],
        [39,57],
        [47,58],
        [24,59],
        [49,60],
        [48,61]
      ],
      "optimalPath": [1,2,4,5,8,50],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2,4,5,8,50],
        [1,2,4,5,7,22,26,32,38,52],
        [1,2,3,6,9,11,13,16,29,33,43,47,58],
        [1,2,3,6,10,12,15,17,18,19,20,24,59],
        [1,2,3,6,10,12,15,17,18,19,21,25,31,37,46,48,61],
        [1,2,3,6,9,11,14,23,28,30,35,40,45,54],
        [1,2,3,6,10,12,15,17,18,19,21,25,31,37,46,49,60],
        [1,2,3,6,9,11,14,23,28,30,35,40,44,53],
        [1,2,3,6,9,11,14,23,28,30,36,56],
        [1,2,3,6,9,11,14,23,27,34,39,57],
        [1,2,3,6,9,11,14,23,28,30,35,42,51],
        [1,2,3,6,9,11,14,23,28,30,35,41,55]
      ],
      "leafGantts": [
        {
          "fCost": 0.86,
          "vehicles": [
            {"veh":1,"k":1,"t0":3.0000,"tf":5.3562,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[4,5,2],"segStart":[3.0000,3.7854,4.5708],"segEnd":[3.7854,4.5708,5.3562]},
            {"veh":3,"k":2,"t0":8.9999,"tf":10.9999,"genTime":9.0000,"actualGenTime":8.9999,"spaces":[3,4],"segStart":[8.9999,9.9999],"segEnd":[9.9999,10.9999]},
            {"veh":4,"k":1,"t0":5.4293,"tf":7.7855,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[4,5,2],"segStart":[5.4293,6.2147,7.0001],"segEnd":[6.2147,7.0001,7.7855]},
            {"veh":5,"k":1,"t0":3.0000,"tf":3.7854,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[1],"segStart":[3.0000],"segEnd":[3.7854]},
            {"veh":7,"k":2,"t0":13.0000,"tf":13.7854,"genTime":13.0000,"actualGenTime":13.0000,"spaces":[3],"segStart":[13.0000],"segEnd":[13.7854]},
            {"veh":8,"k":2,"t0":11.3562,"tf":12.1416,"genTime":11.3562,"actualGenTime":11.3562,"spaces":[2],"segStart":[11.3562],"segEnd":[12.1416]},
            {"veh":9,"k":1,"t0":5.0000,"tf":7.0000,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[1,2],"segStart":[5.0000,6.0000],"segEnd":[6.0000,7.0000]},
            {"veh":11,"k":1,"t0":7.4293,"tf":9.7855,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[4,5,2],"segStart":[7.4293,8.2147,9.0001],"segEnd":[8.2147,9.0001,9.7855]},
            {"veh":12,"k":2,"t0":7.7854,"tf":8.5708,"genTime":7.7854,"actualGenTime":7.7854,"spaces":[3],"segStart":[7.7854],"segEnd":[8.5708]},
            {"veh":14,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[4],"segStart":[9.0000],"segEnd":[9.7854]},
            {"veh":15,"k":1,"t0":11.0000,"tf":13.3562,"genTime":11.0000,"actualGenTime":11.0000,"spaces":[4,5,2],"segStart":[11.0000,11.7854,12.5708],"segEnd":[11.7854,12.5708,13.3562]},
            {"veh":17,"k":2,"t0":15.0000,"tf":17.3562,"genTime":15.0000,"actualGenTime":15.0000,"spaces":[3,5,1],"segStart":[15.0000,15.7854,16.5708],"segEnd":[15.7854,16.5708,17.3562]},
            {"veh":19,"k":1,"t0":7.0000,"tf":9.0000,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[1,2],"segStart":[7.0000,8.0000],"segEnd":[8.0000,9.0000]},
            {"veh":20,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[1],"segStart":[9.0000],"segEnd":[9.7854]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 5.14,
          "vehicles": [
            {"veh":1,"k":1,"t0":3.0000,"tf":5.3562,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[4,5,2],"segStart":[3.0000,3.7854,4.5708],"segEnd":[3.7854,4.5708,5.3562]},
            {"veh":3,"k":2,"t0":8.9999,"tf":10.9999,"genTime":9.0000,"actualGenTime":8.9999,"spaces":[3,4],"segStart":[8.9999,9.9999],"segEnd":[9.9999,10.9999]},
            {"veh":4,"k":1,"t0":5.4292,"tf":7.7854,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[4,5,2],"segStart":[5.4292,6.2146,7.0000],"segEnd":[6.2146,7.0000,7.7854]},
            {"veh":5,"k":1,"t0":3.0000,"tf":3.7854,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[1],"segStart":[3.0000],"segEnd":[3.7854]},
            {"veh":7,"k":2,"t0":13.0000,"tf":13.7854,"genTime":13.0000,"actualGenTime":13.0000,"spaces":[3],"segStart":[13.0000],"segEnd":[13.7854]},
            {"veh":8,"k":2,"t0":11.3562,"tf":12.1416,"genTime":11.3562,"actualGenTime":11.3562,"spaces":[2],"segStart":[11.3562],"segEnd":[12.1416]},
            {"veh":9,"k":1,"t0":5.0000,"tf":7.0000,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[1,2],"segStart":[5.0000,6.0000],"segEnd":[6.0000,7.0000]},
            {"veh":11,"k":1,"t0":7.0000,"tf":9.3562,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[4,5,2],"segStart":[7.0000,7.7854,8.5708],"segEnd":[7.7854,8.5708,9.3562]},
            {"veh":12,"k":2,"t0":7.7854,"tf":8.5708,"genTime":7.7854,"actualGenTime":7.7854,"spaces":[3],"segStart":[7.7854],"segEnd":[8.5708]},
            {"veh":14,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[4],"segStart":[9.0000],"segEnd":[9.7854]},
            {"veh":15,"k":1,"t0":11.5708,"tf":13.9270,"genTime":11.0000,"actualGenTime":11.0000,"spaces":[4,5,2],"segStart":[11.5708,12.3562,13.1416],"segEnd":[12.3562,13.1416,13.9270]},
            {"veh":17,"k":2,"t0":15.0000,"tf":17.3562,"genTime":15.0000,"actualGenTime":15.0000,"spaces":[3,5,1],"segStart":[15.0000,15.7854,16.5708],"segEnd":[15.7854,16.5708,17.3562]},
            {"veh":19,"k":1,"t0":11.1416,"tf":13.1416,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[1,2],"segStart":[11.1416,12.1416],"segEnd":[12.1416,13.1416]},
            {"veh":20,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[1],"segStart":[9.0000],"segEnd":[9.7854]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 8.00,
          "vehicles": [
            {"veh":1,"k":1,"t0":3.0000,"tf":5.3562,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[4,5,2],"segStart":[3.0000,3.7854,4.5708],"segEnd":[3.7854,4.5708,5.3562]},
            {"veh":3,"k":2,"t0":8.9999,"tf":10.9999,"genTime":9.0000,"actualGenTime":8.9999,"spaces":[3,4],"segStart":[8.9999,9.9999],"segEnd":[9.9999,10.9999]},
            {"veh":4,"k":1,"t0":5.0000,"tf":7.3562,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[4,5,2],"segStart":[5.0000,5.7854,6.5708],"segEnd":[5.7854,6.5708,7.3562]},
            {"veh":5,"k":1,"t0":3.0000,"tf":3.7854,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[1],"segStart":[3.0000],"segEnd":[3.7854]},
            {"veh":7,"k":2,"t0":13.0000,"tf":13.7854,"genTime":13.0000,"actualGenTime":13.0000,"spaces":[3],"segStart":[13.0000],"segEnd":[13.7854]},
            {"veh":8,"k":2,"t0":12.1416,"tf":12.9270,"genTime":11.3562,"actualGenTime":11.3562,"spaces":[2],"segStart":[12.1416],"segEnd":[12.9270]},
            {"veh":9,"k":1,"t0":10.1416,"tf":12.1416,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[1,2],"segStart":[10.1416,11.1416],"segEnd":[11.1416,12.1416]},
            {"veh":11,"k":1,"t0":7.0000,"tf":9.3562,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[4,5,2],"segStart":[7.0000,7.7854,8.5708],"segEnd":[7.7854,8.5708,9.3562]},
            {"veh":12,"k":2,"t0":7.7854,"tf":8.5708,"genTime":7.7854,"actualGenTime":7.7854,"spaces":[3],"segStart":[7.7854],"segEnd":[8.5708]},
            {"veh":14,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[4],"segStart":[9.0000],"segEnd":[9.7854]},
            {"veh":15,"k":1,"t0":11.3562,"tf":13.7124,"genTime":11.0000,"actualGenTime":11.0000,"spaces":[4,5,2],"segStart":[11.3562,12.1416,12.9270],"segEnd":[12.1416,12.9270,13.7124]},
            {"veh":17,"k":2,"t0":15.0000,"tf":17.3562,"genTime":15.0000,"actualGenTime":15.0000,"spaces":[3,5,1],"segStart":[15.0000,15.7854,16.5708],"segEnd":[15.7854,16.5708,17.3562]},
            {"veh":19,"k":1,"t0":8.3562,"tf":10.3562,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[1,2],"segStart":[8.3562,9.3562],"segEnd":[9.3562,10.3562]},
            {"veh":20,"k":1,"t0":9.3562,"tf":10.1416,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[1],"segStart":[9.3562],"segEnd":[10.1416]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 11.71,
          "vehicles": [
            {"veh":1,"k":1,"t0":3.0000,"tf":5.3562,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[4,5,2],"segStart":[3.0000,3.7854,4.5708],"segEnd":[3.7854,4.5708,5.3562]},
            {"veh":3,"k":2,"t0":11.5708,"tf":13.5708,"genTime":9.0000,"actualGenTime":8.9999,"spaces":[3,4],"segStart":[11.5708,12.5708],"segEnd":[12.5708,13.5708]},
            {"veh":4,"k":1,"t0":5.0000,"tf":7.3562,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[4,5,2],"segStart":[5.0000,5.7854,6.5708],"segEnd":[5.7854,6.5708,7.3562]},
            {"veh":5,"k":1,"t0":3.0000,"tf":3.7854,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[1],"segStart":[3.0000],"segEnd":[3.7854]},
            {"veh":7,"k":2,"t0":13.0000,"tf":13.7854,"genTime":13.0000,"actualGenTime":13.0000,"spaces":[3],"segStart":[13.0000],"segEnd":[13.7854]},
            {"veh":8,"k":2,"t0":11.3562,"tf":12.1416,"genTime":11.3562,"actualGenTime":11.3562,"spaces":[2],"segStart":[11.3562],"segEnd":[12.1416]},
            {"veh":9,"k":1,"t0":8.0000,"tf":10.0000,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[1,2],"segStart":[8.0000,9.0000],"segEnd":[9.0000,10.0000]},
            {"veh":11,"k":1,"t0":10.5708,"tf":12.9270,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[4,5,2],"segStart":[10.5708,11.3562,12.1416],"segEnd":[11.3562,12.1416,12.9270]},
            {"veh":12,"k":2,"t0":7.7854,"tf":8.5708,"genTime":7.7854,"actualGenTime":7.7854,"spaces":[3],"segStart":[7.7854],"segEnd":[8.5708]},
            {"veh":14,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[4],"segStart":[9.0000],"segEnd":[9.7854]},
            {"veh":15,"k":1,"t0":13.5708,"tf":15.9270,"genTime":11.0000,"actualGenTime":11.0000,"spaces":[4,5,2],"segStart":[13.5708,14.3562,15.1416],"segEnd":[14.3562,15.1416,15.9270]},
            {"veh":17,"k":2,"t0":15.0000,"tf":17.3562,"genTime":15.0000,"actualGenTime":15.0000,"spaces":[3,5,1],"segStart":[15.0000,15.7854,16.5708],"segEnd":[15.7854,16.5708,17.3562]},
            {"veh":19,"k":1,"t0":7.0000,"tf":9.0000,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[1,2],"segStart":[7.0000,8.0000],"segEnd":[8.0000,9.0000]},
            {"veh":20,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[1],"segStart":[9.0000],"segEnd":[9.7854]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 12.71,
          "vehicles": [
            {"veh":1,"k":1,"t0":3.0000,"tf":5.3562,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[4,5,2],"segStart":[3.0000,3.7854,4.5708],"segEnd":[3.7854,4.5708,5.3562]},
            {"veh":3,"k":2,"t0":12.7854,"tf":14.7854,"genTime":9.0000,"actualGenTime":8.9999,"spaces":[3,4],"segStart":[12.7854,13.7854],"segEnd":[13.7854,14.7854]},
            {"veh":4,"k":1,"t0":5.0000,"tf":7.3562,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[4,5,2],"segStart":[5.0000,5.7854,6.5708],"segEnd":[5.7854,6.5708,7.3562]},
            {"veh":5,"k":1,"t0":3.0000,"tf":3.7854,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[1],"segStart":[3.0000],"segEnd":[3.7854]},
            {"veh":7,"k":2,"t0":13.7854,"tf":14.5708,"genTime":13.0000,"actualGenTime":13.0000,"spaces":[3],"segStart":[13.7854],"segEnd":[14.5708]},
            {"veh":8,"k":2,"t0":12.1416,"tf":12.9270,"genTime":11.3562,"actualGenTime":11.3562,"spaces":[2],"segStart":[12.1416],"segEnd":[12.9270]},
            {"veh":9,"k":1,"t0":8.0000,"tf":10.0000,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[1,2],"segStart":[8.0000,9.0000],"segEnd":[9.0000,10.0000]},
            {"veh":11,"k":1,"t0":9.7854,"tf":12.1416,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[4,5,2],"segStart":[9.7854,10.5708,11.3562],"segEnd":[10.5708,11.3562,12.1416]},
            {"veh":12,"k":2,"t0":7.7854,"tf":8.5708,"genTime":7.7854,"actualGenTime":7.7854,"spaces":[3],"segStart":[7.7854],"segEnd":[8.5708]},
            {"veh":14,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[4],"segStart":[9.0000],"segEnd":[9.7854]},
            {"veh":15,"k":1,"t0":12.5708,"tf":14.9270,"genTime":11.0000,"actualGenTime":11.0000,"spaces":[4,5,2],"segStart":[12.5708,13.3562,14.1416],"segEnd":[13.3562,14.1416,14.9270]},
            {"veh":17,"k":2,"t0":15.0000,"tf":17.3562,"genTime":15.0000,"actualGenTime":15.0000,"spaces":[3,5,1],"segStart":[15.0000,15.7854,16.5708],"segEnd":[15.7854,16.5708,17.3562]},
            {"veh":19,"k":1,"t0":7.0000,"tf":9.0000,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[1,2],"segStart":[7.0000,8.0000],"segEnd":[8.0000,9.0000]},
            {"veh":20,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[1],"segStart":[9.0000],"segEnd":[9.7854]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 12.93,
          "vehicles": [
            {"veh":1,"k":1,"t0":3.0000,"tf":5.3562,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[4,5,2],"segStart":[3.0000,3.7854,4.5708],"segEnd":[3.7854,4.5708,5.3562]},
            {"veh":3,"k":2,"t0":8.9999,"tf":10.9999,"genTime":9.0000,"actualGenTime":8.9999,"spaces":[3,4],"segStart":[8.9999,9.9999],"segEnd":[9.9999,10.9999]},
            {"veh":4,"k":1,"t0":5.0000,"tf":7.3562,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[4,5,2],"segStart":[5.0000,5.7854,6.5708],"segEnd":[5.7854,6.5708,7.3562]},
            {"veh":5,"k":1,"t0":3.0000,"tf":3.7854,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[1],"segStart":[3.0000],"segEnd":[3.7854]},
            {"veh":7,"k":2,"t0":13.0000,"tf":13.7854,"genTime":13.0000,"actualGenTime":13.0000,"spaces":[3],"segStart":[13.0000],"segEnd":[13.7854]},
            {"veh":8,"k":2,"t0":12.5708,"tf":13.3562,"genTime":11.3562,"actualGenTime":11.3562,"spaces":[2],"segStart":[12.5708],"segEnd":[13.3562]},
            {"veh":9,"k":1,"t0":13.1416,"tf":15.1416,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[1,2],"segStart":[13.1416,14.1416],"segEnd":[14.1416,15.1416]},
            {"veh":11,"k":1,"t0":7.0000,"tf":9.3562,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[4,5,2],"segStart":[7.0000,7.7854,8.5708],"segEnd":[7.7854,8.5708,9.3562]},
            {"veh":12,"k":2,"t0":7.7854,"tf":8.5708,"genTime":7.7854,"actualGenTime":7.7854,"spaces":[3],"segStart":[7.7854],"segEnd":[8.5708]},
            {"veh":14,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[4],"segStart":[9.0000],"segEnd":[9.7854]},
            {"veh":15,"k":1,"t0":11.7854,"tf":14.1416,"genTime":11.0000,"actualGenTime":11.0000,"spaces":[4,5,2],"segStart":[11.7854,12.5708,13.3562],"segEnd":[12.5708,13.3562,14.1416]},
            {"veh":17,"k":2,"t0":15.0000,"tf":17.3562,"genTime":15.0000,"actualGenTime":15.0000,"spaces":[3,5,1],"segStart":[15.0000,15.7854,16.5708],"segEnd":[15.7854,16.5708,17.3562]},
            {"veh":19,"k":1,"t0":9.7854,"tf":11.7854,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[1,2],"segStart":[9.7854,10.7854],"segEnd":[10.7854,11.7854]},
            {"veh":20,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[1],"segStart":[9.0000],"segEnd":[9.7854]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 12.93,
          "vehicles": [
            {"veh":1,"k":1,"t0":3.0000,"tf":5.3562,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[4,5,2],"segStart":[3.0000,3.7854,4.5708],"segEnd":[3.7854,4.5708,5.3562]},
            {"veh":3,"k":2,"t0":13.7854,"tf":15.7854,"genTime":9.0000,"actualGenTime":8.9999,"spaces":[3,4],"segStart":[13.7854,14.7854],"segEnd":[14.7854,15.7854]},
            {"veh":4,"k":1,"t0":5.0000,"tf":7.3562,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[4,5,2],"segStart":[5.0000,5.7854,6.5708],"segEnd":[5.7854,6.5708,7.3562]},
            {"veh":5,"k":1,"t0":3.0000,"tf":3.7854,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[1],"segStart":[3.0000],"segEnd":[3.7854]},
            {"veh":7,"k":2,"t0":13.0000,"tf":13.7854,"genTime":13.0000,"actualGenTime":13.0000,"spaces":[3],"segStart":[13.0000],"segEnd":[13.7854]},
            {"veh":8,"k":2,"t0":12.1416,"tf":12.9270,"genTime":11.3562,"actualGenTime":11.3562,"spaces":[2],"segStart":[12.1416],"segEnd":[12.9270]},
            {"veh":9,"k":1,"t0":8.0000,"tf":10.0000,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[1,2],"segStart":[8.0000,9.0000],"segEnd":[9.0000,10.0000]},
            {"veh":11,"k":1,"t0":9.7854,"tf":12.1416,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[4,5,2],"segStart":[9.7854,10.5708,11.3562],"segEnd":[10.5708,11.3562,12.1416]},
            {"veh":12,"k":2,"t0":7.7854,"tf":8.5708,"genTime":7.7854,"actualGenTime":7.7854,"spaces":[3],"segStart":[7.7854],"segEnd":[8.5708]},
            {"veh":14,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[4],"segStart":[9.0000],"segEnd":[9.7854]},
            {"veh":15,"k":1,"t0":12.5708,"tf":14.9270,"genTime":11.0000,"actualGenTime":11.0000,"spaces":[4,5,2],"segStart":[12.5708,13.3562,14.1416],"segEnd":[13.3562,14.1416,14.9270]},
            {"veh":17,"k":2,"t0":15.0000,"tf":17.3562,"genTime":15.0000,"actualGenTime":15.0000,"spaces":[3,5,1],"segStart":[15.0000,15.7854,16.5708],"segEnd":[15.7854,16.5708,17.3562]},
            {"veh":19,"k":1,"t0":7.0000,"tf":9.0000,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[1,2],"segStart":[7.0000,8.0000],"segEnd":[8.0000,9.0000]},
            {"veh":20,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[1],"segStart":[9.0000],"segEnd":[9.7854]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 13.14,
          "vehicles": [
            {"veh":1,"k":1,"t0":3.0000,"tf":5.3562,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[4,5,2],"segStart":[3.0000,3.7854,4.5708],"segEnd":[3.7854,4.5708,5.3562]},
            {"veh":3,"k":2,"t0":8.9999,"tf":10.9999,"genTime":9.0000,"actualGenTime":8.9999,"spaces":[3,4],"segStart":[8.9999,9.9999],"segEnd":[9.9999,10.9999]},
            {"veh":4,"k":1,"t0":5.0000,"tf":7.3562,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[4,5,2],"segStart":[5.0000,5.7854,6.5708],"segEnd":[5.7854,6.5708,7.3562]},
            {"veh":5,"k":1,"t0":3.0000,"tf":3.7854,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[1],"segStart":[3.0000],"segEnd":[3.7854]},
            {"veh":7,"k":2,"t0":13.0000,"tf":13.7854,"genTime":13.0000,"actualGenTime":13.0000,"spaces":[3],"segStart":[13.0000],"segEnd":[13.7854]},
            {"veh":8,"k":2,"t0":12.5708,"tf":13.3562,"genTime":11.3562,"actualGenTime":11.3562,"spaces":[2],"segStart":[12.5708],"segEnd":[13.3562]},
            {"veh":9,"k":1,"t0":12.3562,"tf":14.3562,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[1,2],"segStart":[12.3562,13.3562],"segEnd":[13.3562,14.3562]},
            {"veh":11,"k":1,"t0":7.0000,"tf":9.3562,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[4,5,2],"segStart":[7.0000,7.7854,8.5708],"segEnd":[7.7854,8.5708,9.3562]},
            {"veh":12,"k":2,"t0":7.7854,"tf":8.5708,"genTime":7.7854,"actualGenTime":7.7854,"spaces":[3],"segStart":[7.7854],"segEnd":[8.5708]},
            {"veh":14,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[4],"segStart":[9.0000],"segEnd":[9.7854]},
            {"veh":15,"k":1,"t0":12.7854,"tf":15.1416,"genTime":11.0000,"actualGenTime":11.0000,"spaces":[4,5,2],"segStart":[12.7854,13.5708,14.3562],"segEnd":[13.5708,14.3562,15.1416]},
            {"veh":17,"k":2,"t0":15.0000,"tf":17.3562,"genTime":15.0000,"actualGenTime":15.0000,"spaces":[3,5,1],"segStart":[15.0000,15.7854,16.5708],"segEnd":[15.7854,16.5708,17.3562]},
            {"veh":19,"k":1,"t0":9.7854,"tf":11.7854,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[1,2],"segStart":[9.7854,10.7854],"segEnd":[10.7854,11.7854]},
            {"veh":20,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[1],"segStart":[9.0000],"segEnd":[9.7854]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 13.14,
          "vehicles": [
            {"veh":1,"k":1,"t0":3.0000,"tf":5.3562,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[4,5,2],"segStart":[3.0000,3.7854,4.5708],"segEnd":[3.7854,4.5708,5.3562]},
            {"veh":3,"k":2,"t0":8.9999,"tf":10.9999,"genTime":9.0000,"actualGenTime":8.9999,"spaces":[3,4],"segStart":[8.9999,9.9999],"segEnd":[9.9999,10.9999]},
            {"veh":4,"k":1,"t0":5.0000,"tf":7.3562,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[4,5,2],"segStart":[5.0000,5.7854,6.5708],"segEnd":[5.7854,6.5708,7.3562]},
            {"veh":5,"k":1,"t0":3.0000,"tf":3.7854,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[1],"segStart":[3.0000],"segEnd":[3.7854]},
            {"veh":7,"k":2,"t0":13.0000,"tf":13.7854,"genTime":13.0000,"actualGenTime":13.0000,"spaces":[3],"segStart":[13.0000],"segEnd":[13.7854]},
            {"veh":8,"k":2,"t0":14.3562,"tf":15.1416,"genTime":11.3562,"actualGenTime":11.3562,"spaces":[2],"segStart":[14.3562],"segEnd":[15.1416]},
            {"veh":9,"k":1,"t0":12.3562,"tf":14.3562,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[1,2],"segStart":[12.3562,13.3562],"segEnd":[13.3562,14.3562]},
            {"veh":11,"k":1,"t0":7.0000,"tf":9.3562,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[4,5,2],"segStart":[7.0000,7.7854,8.5708],"segEnd":[7.7854,8.5708,9.3562]},
            {"veh":12,"k":2,"t0":7.7854,"tf":8.5708,"genTime":7.7854,"actualGenTime":7.7854,"spaces":[3],"segStart":[7.7854],"segEnd":[8.5708]},
            {"veh":14,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[4],"segStart":[9.0000],"segEnd":[9.7854]},
            {"veh":15,"k":1,"t0":11.0000,"tf":13.3562,"genTime":11.0000,"actualGenTime":11.0000,"spaces":[4,5,2],"segStart":[11.0000,11.7854,12.5708],"segEnd":[11.7854,12.5708,13.3562]},
            {"veh":17,"k":2,"t0":15.0000,"tf":17.3562,"genTime":15.0000,"actualGenTime":15.0000,"spaces":[3,5,1],"segStart":[15.0000,15.7854,16.5708],"segEnd":[15.7854,16.5708,17.3562]},
            {"veh":19,"k":1,"t0":9.7854,"tf":11.7854,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[1,2],"segStart":[9.7854,10.7854],"segEnd":[10.7854,11.7854]},
            {"veh":20,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[1],"segStart":[9.0000],"segEnd":[9.7854]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 13.71,
          "vehicles": [
            {"veh":1,"k":1,"t0":3.0000,"tf":5.3562,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[4,5,2],"segStart":[3.0000,3.7854,4.5708],"segEnd":[3.7854,4.5708,5.3562]},
            {"veh":3,"k":2,"t0":8.9999,"tf":10.9999,"genTime":9.0000,"actualGenTime":8.9999,"spaces":[3,4],"segStart":[8.9999,9.9999],"segEnd":[9.9999,10.9999]},
            {"veh":4,"k":1,"t0":5.0000,"tf":7.3562,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[4,5,2],"segStart":[5.0000,5.7854,6.5708],"segEnd":[5.7854,6.5708,7.3562]},
            {"veh":5,"k":1,"t0":3.0000,"tf":3.7854,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[1],"segStart":[3.0000],"segEnd":[3.7854]},
            {"veh":7,"k":2,"t0":13.0000,"tf":13.7854,"genTime":13.0000,"actualGenTime":13.0000,"spaces":[3],"segStart":[13.0000],"segEnd":[13.7854]},
            {"veh":8,"k":2,"t0":11.3562,"tf":12.1416,"genTime":11.3562,"actualGenTime":11.3562,"spaces":[2],"segStart":[11.3562],"segEnd":[12.1416]},
            {"veh":9,"k":1,"t0":13.3562,"tf":15.3562,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[1,2],"segStart":[13.3562,14.3562],"segEnd":[14.3562,15.3562]},
            {"veh":11,"k":1,"t0":7.0000,"tf":9.3562,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[4,5,2],"segStart":[7.0000,7.7854,8.5708],"segEnd":[7.7854,8.5708,9.3562]},
            {"veh":12,"k":2,"t0":7.7854,"tf":8.5708,"genTime":7.7854,"actualGenTime":7.7854,"spaces":[3],"segStart":[7.7854],"segEnd":[8.5708]},
            {"veh":14,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[4],"segStart":[9.0000],"segEnd":[9.7854]},
            {"veh":15,"k":1,"t0":11.0000,"tf":13.3562,"genTime":11.0000,"actualGenTime":11.0000,"spaces":[4,5,2],"segStart":[11.0000,11.7854,12.5708],"segEnd":[11.7854,12.5708,13.3562]},
            {"veh":17,"k":2,"t0":15.0000,"tf":17.3562,"genTime":15.0000,"actualGenTime":15.0000,"spaces":[3,5,1],"segStart":[15.0000,15.7854,16.5708],"segEnd":[15.7854,16.5708,17.3562]},
            {"veh":19,"k":1,"t0":12.3562,"tf":14.3562,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[1,2],"segStart":[12.3562,13.3562],"segEnd":[13.3562,14.3562]},
            {"veh":20,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[1],"segStart":[9.0000],"segEnd":[9.7854]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 14.43,
          "vehicles": [
            {"veh":1,"k":1,"t0":3.0000,"tf":5.3562,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[4,5,2],"segStart":[3.0000,3.7854,4.5708],"segEnd":[3.7854,4.5708,5.3562]},
            {"veh":3,"k":2,"t0":8.9999,"tf":10.9999,"genTime":9.0000,"actualGenTime":8.9999,"spaces":[3,4],"segStart":[8.9999,9.9999],"segEnd":[9.9999,10.9999]},
            {"veh":4,"k":1,"t0":5.0000,"tf":7.3562,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[4,5,2],"segStart":[5.0000,5.7854,6.5708],"segEnd":[5.7854,6.5708,7.3562]},
            {"veh":5,"k":1,"t0":3.0000,"tf":3.7854,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[1],"segStart":[3.0000],"segEnd":[3.7854]},
            {"veh":7,"k":2,"t0":13.0000,"tf":13.7854,"genTime":13.0000,"actualGenTime":13.0000,"spaces":[3],"segStart":[13.0000],"segEnd":[13.7854]},
            {"veh":8,"k":2,"t0":14.7854,"tf":15.5708,"genTime":11.3562,"actualGenTime":11.3562,"spaces":[2],"segStart":[14.7854],"segEnd":[15.5708]},
            {"veh":9,"k":1,"t0":12.7854,"tf":14.7854,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[1,2],"segStart":[12.7854,13.7854],"segEnd":[13.7854,14.7854]},
            {"veh":11,"k":1,"t0":7.0000,"tf":9.3562,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[4,5,2],"segStart":[7.0000,7.7854,8.5708],"segEnd":[7.7854,8.5708,9.3562]},
            {"veh":12,"k":2,"t0":7.7854,"tf":8.5708,"genTime":7.7854,"actualGenTime":7.7854,"spaces":[3],"segStart":[7.7854],"segEnd":[8.5708]},
            {"veh":14,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[4],"segStart":[9.0000],"segEnd":[9.7854]},
            {"veh":15,"k":1,"t0":11.4292,"tf":13.7854,"genTime":11.0000,"actualGenTime":11.0000,"spaces":[4,5,2],"segStart":[11.4292,12.2146,13.0000],"segEnd":[12.2146,13.0000,13.7854]},
            {"veh":17,"k":2,"t0":15.0000,"tf":17.3562,"genTime":15.0000,"actualGenTime":15.0000,"spaces":[3,5,1],"segStart":[15.0000,15.7854,16.5708],"segEnd":[15.7854,16.5708,17.3562]},
            {"veh":19,"k":1,"t0":9.7854,"tf":11.7854,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[1,2],"segStart":[9.7854,10.7854],"segEnd":[10.7854,11.7854]},
            {"veh":20,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[1],"segStart":[9.0000],"segEnd":[9.7854]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 14.64,
          "vehicles": [
            {"veh":1,"k":1,"t0":3.0000,"tf":5.3562,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[4,5,2],"segStart":[3.0000,3.7854,4.5708],"segEnd":[3.7854,4.5708,5.3562]},
            {"veh":3,"k":2,"t0":8.9999,"tf":10.9999,"genTime":9.0000,"actualGenTime":8.9999,"spaces":[3,4],"segStart":[8.9999,9.9999],"segEnd":[9.9999,10.9999]},
            {"veh":4,"k":1,"t0":5.0000,"tf":7.3562,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[4,5,2],"segStart":[5.0000,5.7854,6.5708],"segEnd":[5.7854,6.5708,7.3562]},
            {"veh":5,"k":1,"t0":3.0000,"tf":3.7854,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[1],"segStart":[3.0000],"segEnd":[3.7854]},
            {"veh":7,"k":2,"t0":13.0000,"tf":13.7854,"genTime":13.0000,"actualGenTime":13.0000,"spaces":[3],"segStart":[13.0000],"segEnd":[13.7854]},
            {"veh":8,"k":2,"t0":14.0000,"tf":14.7854,"genTime":11.3562,"actualGenTime":11.3562,"spaces":[2],"segStart":[14.0000],"segEnd":[14.7854]},
            {"veh":9,"k":1,"t0":12.0000,"tf":14.0000,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[1,2],"segStart":[12.0000,13.0000],"segEnd":[13.0000,14.0000]},
            {"veh":11,"k":1,"t0":7.0000,"tf":9.3562,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[4,5,2],"segStart":[7.0000,7.7854,8.5708],"segEnd":[7.7854,8.5708,9.3562]},
            {"veh":12,"k":2,"t0":7.7854,"tf":8.5708,"genTime":7.7854,"actualGenTime":7.7854,"spaces":[3],"segStart":[7.7854],"segEnd":[8.5708]},
            {"veh":14,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[4],"segStart":[9.0000],"segEnd":[9.7854]},
            {"veh":15,"k":1,"t0":13.2146,"tf":15.5708,"genTime":11.0000,"actualGenTime":11.0000,"spaces":[4,5,2],"segStart":[13.2146,14.0000,14.7854],"segEnd":[14.0000,14.7854,15.5708]},
            {"veh":17,"k":2,"t0":15.0000,"tf":17.3562,"genTime":15.0000,"actualGenTime":15.0000,"spaces":[3,5,1],"segStart":[15.0000,15.7854,16.5708],"segEnd":[15.7854,16.5708,17.3562]},
            {"veh":19,"k":1,"t0":9.7854,"tf":11.7854,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[1,2],"segStart":[9.7854,10.7854],"segEnd":[10.7854,11.7854]},
            {"veh":20,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[1],"segStart":[9.0000],"segEnd":[9.7854]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":26,"tw":22.142,"f":-0.00,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 0.00,
          "vehicles": [
            {"veh":2,"k":1,"t0":3.0000,"tf":5.0000,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[1,2],"segStart":[3.0000,4.0000],"segEnd":[4.0000,5.0000]},
            {"veh":5,"k":2,"t0":7.7854,"tf":10.1416,"genTime":7.7854,"actualGenTime":7.7854,"spaces":[4,5,2],"segStart":[7.7854,8.5708,9.3562],"segEnd":[8.5708,9.3562,10.1416]},
            {"veh":6,"k":3,"t0":16.1416,"tf":18.4978,"genTime":16.1416,"actualGenTime":16.1416,"spaces":[3,5,1],"segStart":[16.1416,16.9270,17.7124],"segEnd":[16.9270,17.7124,18.4978]},
            {"veh":8,"k":1,"t0":5.0000,"tf":7.3562,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[1,5,3],"segStart":[5.0000,5.7854,6.5708],"segEnd":[5.7854,6.5708,7.3562]},
            {"veh":10,"k":1,"t0":3.0000,"tf":3.7854,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[2],"segStart":[3.0000],"segEnd":[3.7854]},
            {"veh":13,"k":1,"t0":5.0001,"tf":5.7855,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[2],"segStart":[5.0001],"segEnd":[5.7855]},
            {"veh":16,"k":2,"t0":9.0000,"tf":11.3562,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[3,5,1],"segStart":[9.0000,9.7854,10.5708],"segEnd":[9.7854,10.5708,11.3562]},
            {"veh":17,"k":3,"t0":21.3562,"tf":22.1416,"genTime":21.3562,"actualGenTime":21.3562,"spaces":[4],"segStart":[21.3562],"segEnd":[22.1416]},
            {"veh":20,"k":2,"t0":13.7854,"tf":14.5708,"genTime":13.7854,"actualGenTime":13.7854,"spaces":[4],"segStart":[13.7854],"segEnd":[14.5708]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":23,"tw":17.676,"f":-0.05,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 0.00,
          "vehicles": [
            {"veh":1,"k":3,"t0":14.1416,"tf":16.4978,"genTime":14.1416,"actualGenTime":14.1416,"spaces":[4,5,2],"segStart":[14.1416,14.9270,15.7124],"segEnd":[14.9270,15.7124,16.4978]},
            {"veh":2,"k":2,"t0":8.9999,"tf":9.7853,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[1],"segStart":[8.9999],"segEnd":[9.7853]},
            {"veh":5,"k":3,"t0":14.1416,"tf":14.9270,"genTime":14.1416,"actualGenTime":14.1416,"spaces":[1],"segStart":[14.1416],"segEnd":[14.9270]},
            {"veh":6,"k":2,"t0":11.3562,"tf":12.1416,"genTime":11.3562,"actualGenTime":11.3562,"spaces":[4],"segStart":[11.3562],"segEnd":[12.1416]},
            {"veh":9,"k":3,"t0":15.6769,"tf":17.6769,"genTime":15.7104,"actualGenTime":15.6937,"spaces":[4,1],"segStart":[15.6769,16.6769],"segEnd":[16.6769,17.6769]},
            {"veh":10,"k":2,"t0":7.7854,"tf":9.7854,"genTime":7.7854,"actualGenTime":7.7854,"spaces":[1,2],"segStart":[7.7854,8.7854],"segEnd":[8.7854,9.7854]},
            {"veh":13,"k":2,"t0":9.7854,"tf":12.1416,"genTime":9.7855,"actualGenTime":9.7855,"spaces":[1,5,3],"segStart":[9.7854,10.5708,11.3562],"segEnd":[10.5708,11.3562,12.1416]},
            {"veh":16,"k":1,"t0":3.0000,"tf":5.0000,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[3,4],"segStart":[3.0000,4.0000],"segEnd":[4.0000,5.0000]},
            {"veh":18,"k":1,"t0":5.0000,"tf":5.7854,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[3],"segStart":[5.0000],"segEnd":[5.7854]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":42,"tw":19.712,"f":-0.16,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 0.00,
          "vehicles": [
            {"veh":1,"k":2,"t0":9.3562,"tf":10.1416,"genTime":9.3562,"actualGenTime":9.3562,"spaces":[1],"segStart":[9.3562],"segEnd":[10.1416]},
            {"veh":3,"k":1,"t0":3.0000,"tf":5.0000,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[3,4],"segStart":[3.0000,4.0000],"segEnd":[4.0000,5.0000]},
            {"veh":4,"k":2,"t0":11.7477,"tf":14.1039,"genTime":11.7675,"actualGenTime":11.7576,"spaces":[1,5,3],"segStart":[11.7477,12.5331,13.3185],"segEnd":[12.5331,13.3185,14.1039]},
            {"veh":6,"k":1,"t0":5.0000,"tf":7.3562,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[3,5,1],"segStart":[5.0000,5.7854,6.5708],"segEnd":[5.7854,6.5708,7.3562]},
            {"veh":7,"k":1,"t0":7.0000,"tf":9.0000,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[3,4],"segStart":[7.0000,8.0000],"segEnd":[8.0000,9.0000]},
            {"veh":8,"k":3,"t0":16.1416,"tf":18.1416,"genTime":16.1416,"actualGenTime":16.1416,"spaces":[1,2],"segStart":[16.1416,17.1416],"segEnd":[17.1416,18.1416]},
            {"veh":9,"k":2,"t0":10.9622,"tf":11.7476,"genTime":10.9853,"actualGenTime":10.9738,"spaces":[1],"segStart":[10.9622],"segEnd":[11.7476]},
            {"veh":11,"k":2,"t0":13.7583,"tf":16.1145,"genTime":13.7710,"actualGenTime":13.7647,"spaces":[1,5,3],"segStart":[13.7583,14.5437,15.3291],"segEnd":[14.5437,15.3291,16.1145]},
            {"veh":12,"k":1,"t0":3.0000,"tf":3.7854,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[4],"segStart":[3.0000],"segEnd":[3.7854]},
            {"veh":13,"k":3,"t0":16.1415,"tf":18.1415,"genTime":16.1416,"actualGenTime":16.1416,"spaces":[2,3],"segStart":[16.1415,17.1415],"segEnd":[17.1415,18.1415]},
            {"veh":15,"k":2,"t0":17.3562,"tf":19.7124,"genTime":17.3562,"actualGenTime":17.3562,"spaces":[1,5,3],"segStart":[17.3562,18.1416,18.9270],"segEnd":[18.1416,18.9270,19.7124]},
            {"veh":17,"k":1,"t0":9.0000,"tf":11.0000,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[3,4],"segStart":[9.0000,10.0000],"segEnd":[10.0000,11.0000]},
            {"veh":18,"k":2,"t0":9.7854,"tf":10.5708,"genTime":9.7854,"actualGenTime":9.7854,"spaces":[2],"segStart":[9.7854],"segEnd":[10.5708]},
            {"veh":19,"k":2,"t0":12.9728,"tf":15.3290,"genTime":12.9889,"actualGenTime":12.9808,"spaces":[1,5,3],"segStart":[12.9728,13.7582,14.5436],"segEnd":[13.7582,14.5436,15.3290]}
          ],
          "numSpaces": 5
        }
      ]
    }
  }
};
