// Interactive decision-tree data — N20_s47
// Auto-generated by export_tree_to_demo.py
window.ALL_INTERACTIVE_TREES = window.ALL_INTERACTIVE_TREES || {};
window.ALL_INTERACTIVE_TREES["N20_s47"] = {
  "numInt": 4,
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":9,"tw":6.000,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":2,"orig":11,"tw":7.000,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":3,"orig":17,"tw":8.000,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":4,"orig":20,"tw":9.000,"f":0.43,"isLeaf":false,"isRoot":false},
        {"id":5,"orig":25,"tw":9.000,"f":0.43,"isLeaf":false,"isRoot":false},
        {"id":6,"orig":29,"tw":9.785,"f":0.86,"isLeaf":false,"isRoot":false},
        {"id":7,"orig":30,"tw":9.356,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":8,"orig":31,"tw":9.356,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":9,"orig":36,"tw":9.785,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":10,"orig":37,"tw":9.785,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":11,"orig":38,"tw":9.785,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":12,"orig":46,"tw":10.000,"f":3.00,"isLeaf":false,"isRoot":false},
        {"id":13,"orig":47,"tw":10.000,"f":3.00,"isLeaf":false,"isRoot":false},
        {"id":14,"orig":62,"tw":11.000,"f":3.00,"isLeaf":false,"isRoot":false},
        {"id":15,"orig":73,"tw":11.356,"f":3.00,"isLeaf":false,"isRoot":false},
        {"id":16,"orig":74,"tw":11.356,"f":0.43,"isLeaf":false,"isRoot":false},
        {"id":17,"orig":87,"tw":11.785,"f":5.21,"isLeaf":false,"isRoot":false},
        {"id":18,"orig":89,"tw":11.785,"f":3.21,"isLeaf":false,"isRoot":false},
        {"id":19,"orig":106,"tw":11.785,"f":7.07,"isLeaf":false,"isRoot":false},
        {"id":20,"orig":108,"tw":12.142,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":21,"orig":124,"tw":11.785,"f":1.71,"isLeaf":false,"isRoot":false},
        {"id":22,"orig":127,"tw":13.000,"f":3.21,"isLeaf":false,"isRoot":false},
        {"id":23,"orig":149,"tw":13.000,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":24,"orig":153,"tw":13.785,"f":2.79,"isLeaf":false,"isRoot":false},
        {"id":25,"orig":172,"tw":13.000,"f":7.07,"isLeaf":false,"isRoot":false},
        {"id":26,"orig":199,"tw":13.000,"f":1.71,"isLeaf":false,"isRoot":false},
        {"id":27,"orig":200,"tw":13.000,"f":1.71,"isLeaf":false,"isRoot":false},
        {"id":28,"orig":294,"tw":17.356,"f":13.14,"isLeaf":true,"isRoot":false},
        {"id":29,"orig":295,"tw":17.356,"f":12.93,"isLeaf":true,"isRoot":false},
        {"id":30,"orig":296,"tw":17.356,"f":14.64,"isLeaf":true,"isRoot":false},
        {"id":31,"orig":306,"tw":17.356,"f":8.00,"isLeaf":true,"isRoot":false},
        {"id":32,"orig":311,"tw":17.356,"f":12.93,"isLeaf":true,"isRoot":false},
        {"id":33,"orig":312,"tw":17.356,"f":12.71,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [3,4],
        [4,5],
        [5,7],
        [5,8],
        [6,9],
        [6,10],
        [7,11],
        [11,12],
        [11,13],
        [9,14],
        [14,15],
        [10,16],
        [15,17],
        [16,18],
        [12,19],
        [8,20],
        [19,21],
        [20,22],
        [21,23],
        [22,24],
        [17,25],
        [25,26],
        [25,27],
        [26,28],
        [27,29],
        [18,30],
        [24,31],
        [23,32],
        [13,33]
      ],
      "optimalPath": [1,2,3,4,18],
      "optimalLeaf": 0,
      "leafPaths": [
        [1,2,3,4,5,8,20,22,24,31],
        [1,2,3,4,5,7,11,13,33],
        [6,9,14,15,17,25,27,29],
        [1,2,3,4,5,7,11,12,19,21,23,32],
        [6,9,14,15,17,25,26,28],
        [6,10,16,18,30]
      ],
      "leafGantts": [
        {
          "fCost": 8.00,
          "vehicles": [
            {"veh":1,"k":1,"t0":3.0000,"tf":5.3562,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[4,5,2],"segStart":[3.0000,3.7854,4.5708],"segEnd":[3.7854,4.5708,5.3562]},
            {"veh":3,"k":2,"t0":8.9999,"tf":10.9999,"genTime":9.0000,"actualGenTime":8.9999,"spaces":[3,4],"segStart":[8.9999,9.9999],"segEnd":[9.9999,10.9999]},
            {"veh":4,"k":1,"t0":5.0000,"tf":7.3562,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[4,5,2],"segStart":[5.0000,5.7854,6.5708],"segEnd":[5.7854,6.5708,7.3562]},
            {"veh":5,"k":1,"t0":3.0000,"tf":3.7854,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[1],"segStart":[3.0000],"segEnd":[3.7854]},
            {"veh":7,"k":2,"t0":13.0000,"tf":13.7854,"genTime":13.0000,"actualGenTime":13.0000,"spaces":[3],"segStart":[13.0000],"segEnd":[13.7854]},
            {"veh":8,"k":2,"t0":12.1416,"tf":12.9270,"genTime":11.3562,"actualGenTime":11.3562,"spaces":[2],"segStart":[12.1416],"segEnd":[12.9270]},
            {"veh":9,"k":1,"t0":10.1416,"tf":12.1416,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[1,2],"segStart":[10.1416,11.1416],"segEnd":[11.1416,12.1416]},
            {"veh":11,"k":1,"t0":7.0000,"tf":9.3562,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[4,5,2],"segStart":[7.0000,7.7854,8.5708],"segEnd":[7.7854,8.5708,9.3562]},
            {"veh":12,"k":2,"t0":7.7854,"tf":8.5708,"genTime":7.7854,"actualGenTime":7.7854,"spaces":[3],"segStart":[7.7854],"segEnd":[8.5708]},
            {"veh":14,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[4],"segStart":[9.0000],"segEnd":[9.7854]},
            {"veh":15,"k":1,"t0":11.3562,"tf":13.7124,"genTime":11.0000,"actualGenTime":11.0000,"spaces":[4,5,2],"segStart":[11.3562,12.1416,12.9270],"segEnd":[12.1416,12.9270,13.7124]},
            {"veh":17,"k":2,"t0":15.0000,"tf":17.3562,"genTime":15.0000,"actualGenTime":15.0000,"spaces":[3,5,1],"segStart":[15.0000,15.7854,16.5708],"segEnd":[15.7854,16.5708,17.3562]},
            {"veh":19,"k":1,"t0":8.3562,"tf":10.3562,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[1,2],"segStart":[8.3562,9.3562],"segEnd":[9.3562,10.3562]},
            {"veh":20,"k":1,"t0":9.3562,"tf":10.1416,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[1],"segStart":[9.3562],"segEnd":[10.1416]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 12.71,
          "vehicles": [
            {"veh":1,"k":1,"t0":3.0000,"tf":5.3562,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[4,5,2],"segStart":[3.0000,3.7854,4.5708],"segEnd":[3.7854,4.5708,5.3562]},
            {"veh":3,"k":2,"t0":12.7854,"tf":14.7854,"genTime":9.0000,"actualGenTime":8.9999,"spaces":[3,4],"segStart":[12.7854,13.7854],"segEnd":[13.7854,14.7854]},
            {"veh":4,"k":1,"t0":5.0000,"tf":7.3562,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[4,5,2],"segStart":[5.0000,5.7854,6.5708],"segEnd":[5.7854,6.5708,7.3562]},
            {"veh":5,"k":1,"t0":3.0000,"tf":3.7854,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[1],"segStart":[3.0000],"segEnd":[3.7854]},
            {"veh":7,"k":2,"t0":13.7854,"tf":14.5708,"genTime":13.0000,"actualGenTime":13.0000,"spaces":[3],"segStart":[13.7854],"segEnd":[14.5708]},
            {"veh":8,"k":2,"t0":12.1416,"tf":12.9270,"genTime":11.3562,"actualGenTime":11.3562,"spaces":[2],"segStart":[12.1416],"segEnd":[12.9270]},
            {"veh":9,"k":1,"t0":8.0000,"tf":10.0000,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[1,2],"segStart":[8.0000,9.0000],"segEnd":[9.0000,10.0000]},
            {"veh":11,"k":1,"t0":9.7854,"tf":12.1416,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[4,5,2],"segStart":[9.7854,10.5708,11.3562],"segEnd":[10.5708,11.3562,12.1416]},
            {"veh":12,"k":2,"t0":7.7854,"tf":8.5708,"genTime":7.7854,"actualGenTime":7.7854,"spaces":[3],"segStart":[7.7854],"segEnd":[8.5708]},
            {"veh":14,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[4],"segStart":[9.0000],"segEnd":[9.7854]},
            {"veh":15,"k":1,"t0":12.5708,"tf":14.9270,"genTime":11.0000,"actualGenTime":11.0000,"spaces":[4,5,2],"segStart":[12.5708,13.3562,14.1416],"segEnd":[13.3562,14.1416,14.9270]},
            {"veh":17,"k":2,"t0":15.0000,"tf":17.3562,"genTime":15.0000,"actualGenTime":15.0000,"spaces":[3,5,1],"segStart":[15.0000,15.7854,16.5708],"segEnd":[15.7854,16.5708,17.3562]},
            {"veh":19,"k":1,"t0":7.0000,"tf":9.0000,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[1,2],"segStart":[7.0000,8.0000],"segEnd":[8.0000,9.0000]},
            {"veh":20,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[1],"segStart":[9.0000],"segEnd":[9.7854]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 12.93,
          "vehicles": [
            {"veh":1,"k":1,"t0":3.0000,"tf":5.3562,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[4,5,2],"segStart":[3.0000,3.7854,4.5708],"segEnd":[3.7854,4.5708,5.3562]},
            {"veh":3,"k":2,"t0":8.9999,"tf":10.9999,"genTime":9.0000,"actualGenTime":8.9999,"spaces":[3,4],"segStart":[8.9999,9.9999],"segEnd":[9.9999,10.9999]},
            {"veh":4,"k":1,"t0":5.0000,"tf":7.3562,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[4,5,2],"segStart":[5.0000,5.7854,6.5708],"segEnd":[5.7854,6.5708,7.3562]},
            {"veh":5,"k":1,"t0":3.0000,"tf":3.7854,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[1],"segStart":[3.0000],"segEnd":[3.7854]},
            {"veh":7,"k":2,"t0":13.0000,"tf":13.7854,"genTime":13.0000,"actualGenTime":13.0000,"spaces":[3],"segStart":[13.0000],"segEnd":[13.7854]},
            {"veh":8,"k":2,"t0":12.5708,"tf":13.3562,"genTime":11.3562,"actualGenTime":11.3562,"spaces":[2],"segStart":[12.5708],"segEnd":[13.3562]},
            {"veh":9,"k":1,"t0":13.1416,"tf":15.1416,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[1,2],"segStart":[13.1416,14.1416],"segEnd":[14.1416,15.1416]},
            {"veh":11,"k":1,"t0":7.0000,"tf":9.3562,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[4,5,2],"segStart":[7.0000,7.7854,8.5708],"segEnd":[7.7854,8.5708,9.3562]},
            {"veh":12,"k":2,"t0":7.7854,"tf":8.5708,"genTime":7.7854,"actualGenTime":7.7854,"spaces":[3],"segStart":[7.7854],"segEnd":[8.5708]},
            {"veh":14,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[4],"segStart":[9.0000],"segEnd":[9.7854]},
            {"veh":15,"k":1,"t0":11.7854,"tf":14.1416,"genTime":11.0000,"actualGenTime":11.0000,"spaces":[4,5,2],"segStart":[11.7854,12.5708,13.3562],"segEnd":[12.5708,13.3562,14.1416]},
            {"veh":17,"k":2,"t0":15.0000,"tf":17.3562,"genTime":15.0000,"actualGenTime":15.0000,"spaces":[3,5,1],"segStart":[15.0000,15.7854,16.5708],"segEnd":[15.7854,16.5708,17.3562]},
            {"veh":19,"k":1,"t0":9.7854,"tf":11.7854,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[1,2],"segStart":[9.7854,10.7854],"segEnd":[10.7854,11.7854]},
            {"veh":20,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[1],"segStart":[9.0000],"segEnd":[9.7854]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 12.93,
          "vehicles": [
            {"veh":1,"k":1,"t0":3.0000,"tf":5.3562,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[4,5,2],"segStart":[3.0000,3.7854,4.5708],"segEnd":[3.7854,4.5708,5.3562]},
            {"veh":3,"k":2,"t0":13.7854,"tf":15.7854,"genTime":9.0000,"actualGenTime":8.9999,"spaces":[3,4],"segStart":[13.7854,14.7854],"segEnd":[14.7854,15.7854]},
            {"veh":4,"k":1,"t0":5.0000,"tf":7.3562,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[4,5,2],"segStart":[5.0000,5.7854,6.5708],"segEnd":[5.7854,6.5708,7.3562]},
            {"veh":5,"k":1,"t0":3.0000,"tf":3.7854,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[1],"segStart":[3.0000],"segEnd":[3.7854]},
            {"veh":7,"k":2,"t0":13.0000,"tf":13.7854,"genTime":13.0000,"actualGenTime":13.0000,"spaces":[3],"segStart":[13.0000],"segEnd":[13.7854]},
            {"veh":8,"k":2,"t0":12.1416,"tf":12.9270,"genTime":11.3562,"actualGenTime":11.3562,"spaces":[2],"segStart":[12.1416],"segEnd":[12.9270]},
            {"veh":9,"k":1,"t0":8.0000,"tf":10.0000,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[1,2],"segStart":[8.0000,9.0000],"segEnd":[9.0000,10.0000]},
            {"veh":11,"k":1,"t0":9.7854,"tf":12.1416,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[4,5,2],"segStart":[9.7854,10.5708,11.3562],"segEnd":[10.5708,11.3562,12.1416]},
            {"veh":12,"k":2,"t0":7.7854,"tf":8.5708,"genTime":7.7854,"actualGenTime":7.7854,"spaces":[3],"segStart":[7.7854],"segEnd":[8.5708]},
            {"veh":14,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[4],"segStart":[9.0000],"segEnd":[9.7854]},
            {"veh":15,"k":1,"t0":12.5708,"tf":14.9270,"genTime":11.0000,"actualGenTime":11.0000,"spaces":[4,5,2],"segStart":[12.5708,13.3562,14.1416],"segEnd":[13.3562,14.1416,14.9270]},
            {"veh":17,"k":2,"t0":15.0000,"tf":17.3562,"genTime":15.0000,"actualGenTime":15.0000,"spaces":[3,5,1],"segStart":[15.0000,15.7854,16.5708],"segEnd":[15.7854,16.5708,17.3562]},
            {"veh":19,"k":1,"t0":7.0000,"tf":9.0000,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[1,2],"segStart":[7.0000,8.0000],"segEnd":[8.0000,9.0000]},
            {"veh":20,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[1],"segStart":[9.0000],"segEnd":[9.7854]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 13.14,
          "vehicles": [
            {"veh":1,"k":1,"t0":3.0000,"tf":5.3562,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[4,5,2],"segStart":[3.0000,3.7854,4.5708],"segEnd":[3.7854,4.5708,5.3562]},
            {"veh":3,"k":2,"t0":8.9999,"tf":10.9999,"genTime":9.0000,"actualGenTime":8.9999,"spaces":[3,4],"segStart":[8.9999,9.9999],"segEnd":[9.9999,10.9999]},
            {"veh":4,"k":1,"t0":5.0000,"tf":7.3562,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[4,5,2],"segStart":[5.0000,5.7854,6.5708],"segEnd":[5.7854,6.5708,7.3562]},
            {"veh":5,"k":1,"t0":3.0000,"tf":3.7854,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[1],"segStart":[3.0000],"segEnd":[3.7854]},
            {"veh":7,"k":2,"t0":13.0000,"tf":13.7854,"genTime":13.0000,"actualGenTime":13.0000,"spaces":[3],"segStart":[13.0000],"segEnd":[13.7854]},
            {"veh":8,"k":2,"t0":12.5708,"tf":13.3562,"genTime":11.3562,"actualGenTime":11.3562,"spaces":[2],"segStart":[12.5708],"segEnd":[13.3562]},
            {"veh":9,"k":1,"t0":12.3562,"tf":14.3562,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[1,2],"segStart":[12.3562,13.3562],"segEnd":[13.3562,14.3562]},
            {"veh":11,"k":1,"t0":7.0000,"tf":9.3562,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[4,5,2],"segStart":[7.0000,7.7854,8.5708],"segEnd":[7.7854,8.5708,9.3562]},
            {"veh":12,"k":2,"t0":7.7854,"tf":8.5708,"genTime":7.7854,"actualGenTime":7.7854,"spaces":[3],"segStart":[7.7854],"segEnd":[8.5708]},
            {"veh":14,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[4],"segStart":[9.0000],"segEnd":[9.7854]},
            {"veh":15,"k":1,"t0":12.7854,"tf":15.1416,"genTime":11.0000,"actualGenTime":11.0000,"spaces":[4,5,2],"segStart":[12.7854,13.5708,14.3562],"segEnd":[13.5708,14.3562,15.1416]},
            {"veh":17,"k":2,"t0":15.0000,"tf":17.3562,"genTime":15.0000,"actualGenTime":15.0000,"spaces":[3,5,1],"segStart":[15.0000,15.7854,16.5708],"segEnd":[15.7854,16.5708,17.3562]},
            {"veh":19,"k":1,"t0":9.7854,"tf":11.7854,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[1,2],"segStart":[9.7854,10.7854],"segEnd":[10.7854,11.7854]},
            {"veh":20,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[1],"segStart":[9.0000],"segEnd":[9.7854]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 14.64,
          "vehicles": [
            {"veh":1,"k":1,"t0":3.0000,"tf":5.3562,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[4,5,2],"segStart":[3.0000,3.7854,4.5708],"segEnd":[3.7854,4.5708,5.3562]},
            {"veh":3,"k":2,"t0":8.9999,"tf":10.9999,"genTime":9.0000,"actualGenTime":8.9999,"spaces":[3,4],"segStart":[8.9999,9.9999],"segEnd":[9.9999,10.9999]},
            {"veh":4,"k":1,"t0":5.0000,"tf":7.3562,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[4,5,2],"segStart":[5.0000,5.7854,6.5708],"segEnd":[5.7854,6.5708,7.3562]},
            {"veh":5,"k":1,"t0":3.0000,"tf":3.7854,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[1],"segStart":[3.0000],"segEnd":[3.7854]},
            {"veh":7,"k":2,"t0":13.0000,"tf":13.7854,"genTime":13.0000,"actualGenTime":13.0000,"spaces":[3],"segStart":[13.0000],"segEnd":[13.7854]},
            {"veh":8,"k":2,"t0":14.0000,"tf":14.7854,"genTime":11.3562,"actualGenTime":11.3562,"spaces":[2],"segStart":[14.0000],"segEnd":[14.7854]},
            {"veh":9,"k":1,"t0":12.0000,"tf":14.0000,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[1,2],"segStart":[12.0000,13.0000],"segEnd":[13.0000,14.0000]},
            {"veh":11,"k":1,"t0":7.0000,"tf":9.3562,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[4,5,2],"segStart":[7.0000,7.7854,8.5708],"segEnd":[7.7854,8.5708,9.3562]},
            {"veh":12,"k":2,"t0":7.7854,"tf":8.5708,"genTime":7.7854,"actualGenTime":7.7854,"spaces":[3],"segStart":[7.7854],"segEnd":[8.5708]},
            {"veh":14,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[4],"segStart":[9.0000],"segEnd":[9.7854]},
            {"veh":15,"k":1,"t0":13.2146,"tf":15.5708,"genTime":11.0000,"actualGenTime":11.0000,"spaces":[4,5,2],"segStart":[13.2146,14.0000,14.7854],"segEnd":[14.0000,14.7854,15.5708]},
            {"veh":17,"k":2,"t0":15.0000,"tf":17.3562,"genTime":15.0000,"actualGenTime":15.0000,"spaces":[3,5,1],"segStart":[15.0000,15.7854,16.5708],"segEnd":[15.7854,16.5708,17.3562]},
            {"veh":19,"k":1,"t0":9.7854,"tf":11.7854,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[1,2],"segStart":[9.7854,10.7854],"segEnd":[10.7854,11.7854]},
            {"veh":20,"k":1,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[1],"segStart":[9.0000],"segEnd":[9.7854]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":27,"tw":22.142,"f":-0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":27,"tw":22.142,"f":-0.00,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": -0.00,
          "vehicles": [
            {"veh":2,"k":1,"t0":3.0000,"tf":5.0000,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[1,2],"segStart":[3.0000,4.0000],"segEnd":[4.0000,5.0000]},
            {"veh":5,"k":2,"t0":7.7854,"tf":10.1416,"genTime":7.7854,"actualGenTime":7.7854,"spaces":[4,5,2],"segStart":[7.7854,8.5708,9.3562],"segEnd":[8.5708,9.3562,10.1416]},
            {"veh":6,"k":3,"t0":16.1416,"tf":18.4978,"genTime":16.1416,"actualGenTime":16.1416,"spaces":[3,5,1],"segStart":[16.1416,16.9270,17.7124],"segEnd":[16.9270,17.7124,18.4978]},
            {"veh":8,"k":1,"t0":5.0000,"tf":7.3562,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[1,5,3],"segStart":[5.0000,5.7854,6.5708],"segEnd":[5.7854,6.5708,7.3562]},
            {"veh":10,"k":1,"t0":3.0000,"tf":3.7854,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[2],"segStart":[3.0000],"segEnd":[3.7854]},
            {"veh":13,"k":1,"t0":5.0000,"tf":5.7854,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[2],"segStart":[5.0000],"segEnd":[5.7854]},
            {"veh":16,"k":2,"t0":9.0000,"tf":11.3562,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[3,5,1],"segStart":[9.0000,9.7854,10.5708],"segEnd":[9.7854,10.5708,11.3562]},
            {"veh":17,"k":3,"t0":21.3562,"tf":22.1416,"genTime":21.3562,"actualGenTime":21.3562,"spaces":[4],"segStart":[21.3562],"segEnd":[22.1416]},
            {"veh":20,"k":2,"t0":13.7854,"tf":14.5708,"genTime":13.7854,"actualGenTime":13.7854,"spaces":[4],"segStart":[13.7854],"segEnd":[14.5708]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":24,"tw":17.676,"f":-0.05,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":24,"tw":17.676,"f":-0.05,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": -0.05,
          "vehicles": [
            {"veh":1,"k":3,"t0":14.1416,"tf":16.4978,"genTime":14.1416,"actualGenTime":14.1416,"spaces":[4,5,2],"segStart":[14.1416,14.9270,15.7124],"segEnd":[14.9270,15.7124,16.4978]},
            {"veh":2,"k":2,"t0":9.0000,"tf":9.7854,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[1],"segStart":[9.0000],"segEnd":[9.7854]},
            {"veh":5,"k":3,"t0":14.1416,"tf":14.9270,"genTime":14.1416,"actualGenTime":14.1416,"spaces":[1],"segStart":[14.1416],"segEnd":[14.9270]},
            {"veh":6,"k":2,"t0":11.3562,"tf":12.1416,"genTime":11.3562,"actualGenTime":11.3562,"spaces":[4],"segStart":[11.3562],"segEnd":[12.1416]},
            {"veh":9,"k":3,"t0":15.6757,"tf":17.6757,"genTime":15.7104,"actualGenTime":15.6937,"spaces":[4,1],"segStart":[15.6757,16.6757],"segEnd":[16.6757,17.6757]},
            {"veh":10,"k":2,"t0":7.7854,"tf":9.7854,"genTime":7.7854,"actualGenTime":7.7854,"spaces":[1,2],"segStart":[7.7854,8.7854],"segEnd":[8.7854,9.7854]},
            {"veh":13,"k":2,"t0":9.7855,"tf":12.1417,"genTime":9.7855,"actualGenTime":9.7855,"spaces":[1,5,3],"segStart":[9.7855,10.5709,11.3563],"segEnd":[10.5709,11.3563,12.1417]},
            {"veh":16,"k":1,"t0":3.0000,"tf":5.0000,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[3,4],"segStart":[3.0000,4.0000],"segEnd":[4.0000,5.0000]},
            {"veh":18,"k":1,"t0":5.0000,"tf":5.7854,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[3],"segStart":[5.0000],"segEnd":[5.7854]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":43,"tw":19.712,"f":-0.16,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":43,"tw":19.712,"f":-0.16,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": -0.16,
          "vehicles": [
            {"veh":1,"k":2,"t0":9.3562,"tf":10.1416,"genTime":9.3562,"actualGenTime":9.3562,"spaces":[1],"segStart":[9.3562],"segEnd":[10.1416]},
            {"veh":3,"k":1,"t0":3.0000,"tf":5.0000,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[3,4],"segStart":[3.0000,4.0000],"segEnd":[4.0000,5.0000]},
            {"veh":4,"k":2,"t0":11.7434,"tf":14.0996,"genTime":11.7675,"actualGenTime":11.7576,"spaces":[1,5,3],"segStart":[11.7434,12.5288,13.3142],"segEnd":[12.5288,13.3142,14.0996]},
            {"veh":6,"k":1,"t0":5.0000,"tf":7.3562,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[3,5,1],"segStart":[5.0000,5.7854,6.5708],"segEnd":[5.7854,6.5708,7.3562]},
            {"veh":7,"k":1,"t0":7.0000,"tf":9.0000,"genTime":7.0000,"actualGenTime":7.0000,"spaces":[3,4],"segStart":[7.0000,8.0000],"segEnd":[8.0000,9.0000]},
            {"veh":8,"k":3,"t0":16.1416,"tf":18.1416,"genTime":16.1416,"actualGenTime":16.1416,"spaces":[1,2],"segStart":[16.1416,17.1416],"segEnd":[17.1416,18.1416]},
            {"veh":9,"k":2,"t0":10.9579,"tf":11.7433,"genTime":10.9853,"actualGenTime":10.9738,"spaces":[1],"segStart":[10.9579],"segEnd":[11.7433]},
            {"veh":11,"k":2,"t0":13.7470,"tf":16.1031,"genTime":13.7710,"actualGenTime":13.7647,"spaces":[1,5,3],"segStart":[13.7470,14.5324,15.3177],"segEnd":[14.5324,15.3177,16.1031]},
            {"veh":12,"k":1,"t0":3.0000,"tf":3.7854,"genTime":3.0000,"actualGenTime":3.0000,"spaces":[4],"segStart":[3.0000],"segEnd":[3.7854]},
            {"veh":13,"k":3,"t0":16.1416,"tf":18.1416,"genTime":16.1416,"actualGenTime":16.1416,"spaces":[2,3],"segStart":[16.1416,17.1416],"segEnd":[17.1416,18.1416]},
            {"veh":15,"k":2,"t0":17.3562,"tf":19.7124,"genTime":17.3562,"actualGenTime":17.3562,"spaces":[1,5,3],"segStart":[17.3562,18.1416,18.9270],"segEnd":[18.1416,18.9270,19.7124]},
            {"veh":17,"k":1,"t0":9.0000,"tf":11.0000,"genTime":9.0000,"actualGenTime":9.0000,"spaces":[3,4],"segStart":[9.0000,10.0000],"segEnd":[10.0000,11.0000]},
            {"veh":18,"k":2,"t0":9.7854,"tf":10.5708,"genTime":9.7854,"actualGenTime":9.7854,"spaces":[2],"segStart":[9.7854],"segEnd":[10.5708]},
            {"veh":19,"k":2,"t0":12.9615,"tf":15.3177,"genTime":12.9889,"actualGenTime":12.9808,"spaces":[1,5,3],"segStart":[12.9615,13.7469,14.5323],"segEnd":[13.7469,14.5323,15.3177]}
          ],
          "numSpaces": 5
        }
      ]
    }
  }
};
