// Interactive decision-tree data — 20r_S1
// Auto-generated by export_interactive_tree.m
window.ALL_INTERACTIVE_TREES = window.ALL_INTERACTIVE_TREES || {};
window.ALL_INTERACTIVE_TREES["20r_S1"] = {
  "numInt": 4,
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":39,"tw":29.467,"f":3.85,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 3.85,
          "vehicles": [
            {"veh":4,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[1.0000,2.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":5,"k":1,"t0":5.0000,"tf":7.0000,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[1.0000,2.0000],"segStart":[5.0000,6.0000],"segEnd":[6.0000,7.0000]},
            {"veh":6,"k":1,"t0":8.0000,"tf":8.7854,"genTime":8.0000,"actualGenTime":8.0000,"spaces":[1.0000],"segStart":[8.0000],"segEnd":[8.7854]},
            {"veh":8,"k":2,"t0":11.1403,"tf":13.4965,"genTime":10.7855,"actualGenTime":10.9629,"spaces":[2.0000,5.0000,4.0000],"segStart":[11.1403,11.9257,12.7111],"segEnd":[11.9257,12.7111,13.4965]},
            {"veh":9,"k":2,"t0":13.3562,"tf":15.7124,"genTime":13.3562,"actualGenTime":13.3562,"spaces":[2.0000,5.0000,4.0000],"segStart":[13.3562,14.1416,14.9270],"segEnd":[14.1416,14.9270,15.7124]},
            {"veh":10,"k":2,"t0":7.5695,"tf":9.5695,"genTime":7.0000,"actualGenTime":7.2847,"spaces":[3.0000,4.0000],"segStart":[7.5695,8.5695],"segEnd":[8.5695,9.5695]},
            {"veh":12,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[4.0000,1.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":13,"k":1,"t0":7.7841,"tf":10.1403,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[4.0000,5.0000,2.0000],"segStart":[7.7841,8.5695,9.3549],"segEnd":[8.5695,9.3549,10.1403]},
            {"veh":15,"k":2,"t0":10.1403,"tf":12.1403,"genTime":10.0000,"actualGenTime":10.0701,"spaces":[2.0000,3.0000],"segStart":[10.1403,11.1403],"segEnd":[11.1403,12.1403]},
            {"veh":17,"k":2,"t0":5.7841,"tf":7.7841,"genTime":5.7846,"actualGenTime":5.7842,"spaces":[3.0000,4.0000],"segStart":[5.7841,6.7841],"segEnd":[6.7841,7.7841]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":33,"tw":29.220,"f":0.79,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 0.79,
          "vehicles": [
            {"veh":2,"k":2,"t0":13.1085,"tf":15.1085,"genTime":13.1117,"actualGenTime":13.1121,"spaces":[3.0000,4.0000],"segStart":[13.1085,14.1085],"segEnd":[14.1085,15.1085]},
            {"veh":6,"k":2,"t0":11.7854,"tf":12.5708,"genTime":11.7854,"actualGenTime":11.7854,"spaces":[4.0000],"segStart":[11.7854],"segEnd":[12.5708]},
            {"veh":7,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[1.0000,2.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":8,"k":1,"t0":5.4292,"tf":7.7854,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[1.0000,5.0000,3.0000],"segStart":[5.4292,6.2146,7.0000],"segEnd":[6.2146,7.0000,7.7854]},
            {"veh":9,"k":1,"t0":8.0000,"tf":10.3562,"genTime":8.0000,"actualGenTime":8.0000,"spaces":[1.0000,5.0000,3.0000],"segStart":[8.0000,8.7854,9.5708],"segEnd":[8.7854,9.5708,10.3562]},
            {"veh":12,"k":2,"t0":6.9997,"tf":7.7851,"genTime":6.9997,"actualGenTime":6.9996,"spaces":[4.0000],"segStart":[6.9997],"segEnd":[7.7851]},
            {"veh":14,"k":1,"t0":2.0000,"tf":2.7854,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[2.0000],"segStart":[2.0000],"segEnd":[2.7854]},
            {"veh":15,"k":1,"t0":5.0000,"tf":7.0000,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[2.0000,3.0000],"segStart":[5.0000,6.0000],"segEnd":[6.0000,7.0000]},
            {"veh":16,"k":1,"t0":8.0000,"tf":8.7854,"genTime":8.0000,"actualGenTime":8.0000,"spaces":[2.0000],"segStart":[8.0000],"segEnd":[8.7854]},
            {"veh":20,"k":2,"t0":10.3562,"tf":12.7124,"genTime":10.0000,"actualGenTime":10.1781,"spaces":[3.0000,5.0000,1.0000],"segStart":[10.3562,11.1416,11.9270],"segEnd":[11.1416,11.9270,12.7124]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":37,"tw":27.896,"f":5.06,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 5.06,
          "vehicles": [
            {"veh":1,"k":1,"t0":2.0000,"tf":2.7854,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[2.0000],"segStart":[2.0000],"segEnd":[2.7854]},
            {"veh":2,"k":1,"t0":7.7599,"tf":10.1161,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[2.0000,5.0000,4.0000],"segStart":[7.7599,8.5453,9.3307],"segEnd":[8.5453,9.3307,10.1161]},
            {"veh":3,"k":1,"t0":8.5453,"tf":10.5453,"genTime":8.0000,"actualGenTime":8.0000,"spaces":[2.0000,3.0000],"segStart":[8.5453,9.5453],"segEnd":[9.5453,10.5453]},
            {"veh":7,"k":2,"t0":8.5453,"tf":10.5453,"genTime":7.0000,"actualGenTime":7.7700,"spaces":[1.0000,2.0000],"segStart":[8.5453,9.5453],"segEnd":[9.5453,10.5453]},
            {"veh":11,"k":2,"t0":10.9015,"tf":13.2577,"genTime":10.7855,"actualGenTime":10.8408,"spaces":[4.0000,5.0000,2.0000],"segStart":[10.9015,11.6869,12.4723],"segEnd":[11.6869,12.4723,13.2577]},
            {"veh":14,"k":2,"t0":5.7599,"tf":7.7599,"genTime":5.7699,"actualGenTime":5.7621,"spaces":[1.0000,2.0000],"segStart":[5.7599,6.7599],"segEnd":[6.7599,7.7599]},
            {"veh":16,"k":2,"t0":11.7854,"tf":14.1416,"genTime":11.7854,"actualGenTime":11.7854,"spaces":[1.0000,5.0000,3.0000],"segStart":[11.7854,12.5708,13.3562],"segEnd":[12.5708,13.3562,14.1416]},
            {"veh":18,"k":2,"t0":10.1161,"tf":12.4723,"genTime":10.0000,"actualGenTime":10.0553,"spaces":[4.0000,5.0000,2.0000],"segStart":[10.1161,10.9015,11.6869],"segEnd":[10.9015,11.6869,12.4723]},
            {"veh":19,"k":1,"t0":2.0000,"tf":2.7854,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000],"segStart":[2.0000],"segEnd":[2.7854]},
            {"veh":20,"k":1,"t0":5.0000,"tf":7.0000,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[3.0000,4.0000],"segStart":[5.0000,6.0000],"segEnd":[6.0000,7.0000]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":36,"tw":33.253,"f":1.22,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 1.22,
          "vehicles": [
            {"veh":3,"k":2,"t0":13.5397,"tf":14.3251,"genTime":13.5423,"actualGenTime":13.5432,"spaces":[2.0000],"segStart":[13.5397],"segEnd":[14.3251]},
            {"veh":4,"k":2,"t0":7.7854,"tf":10.1416,"genTime":7.0000,"actualGenTime":7.3928,"spaces":[1.0000,5.0000,3.0000],"segStart":[7.7854,8.5708,9.3562],"segEnd":[8.5708,9.3562,10.1416]},
            {"veh":5,"k":2,"t0":10.0000,"tf":12.3562,"genTime":10.0000,"actualGenTime":10.0000,"spaces":[1.0000,5.0000,3.0000],"segStart":[10.0000,10.7854,11.5708],"segEnd":[10.7854,11.5708,12.3562]},
            {"veh":10,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000,4.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":11,"k":1,"t0":5.4292,"tf":7.7854,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[3.0000,5.0000,1.0000],"segStart":[5.4292,6.2146,7.0000],"segEnd":[6.2146,7.0000,7.7854]},
            {"veh":13,"k":2,"t0":13.1390,"tf":15.4952,"genTime":13.1395,"actualGenTime":13.1393,"spaces":[1.0000,5.0000,3.0000],"segStart":[13.1390,13.9244,14.7098],"segEnd":[13.9244,14.7098,15.4952]},
            {"veh":16,"k":3,"t0":17.1416,"tf":19.1416,"genTime":17.1415,"actualGenTime":17.1415,"spaces":[2.0000,3.0000],"segStart":[17.1416,18.1416],"segEnd":[18.1416,19.1416]},
            {"veh":17,"k":1,"t0":2.0000,"tf":2.7854,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[4.0000],"segStart":[2.0000],"segEnd":[2.7854]},
            {"veh":18,"k":1,"t0":5.0000,"tf":7.0000,"genTime":5.0000,"actualGenTime":5.0000,"spaces":[4.0000,1.0000],"segStart":[5.0000,6.0000],"segEnd":[6.0000,7.0000]},
            {"veh":19,"k":2,"t0":5.7854,"tf":6.5708,"genTime":5.7854,"actualGenTime":5.7854,"spaces":[2.0000],"segStart":[5.7854],"segEnd":[6.5708]}
          ],
          "numSpaces": 5
        }
      ]
    }
  }
};
