// Interactive decision-tree data — 10r_S2
// Auto-generated by export_interactive_tree.m
window.ALL_INTERACTIVE_TREES = window.ALL_INTERACTIVE_TREES || {};
window.ALL_INTERACTIVE_TREES["10r_S2"] = {
  "numInt": 4,
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":20,"tw":24.111,"f":-0.00,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": -0.00,
          "vehicles": [
            {"veh":2,"k":1,"t0":2.0000,"tf":2.7854,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[1.0000],"segStart":[2.0000],"segEnd":[2.7854]},
            {"veh":3,"k":2,"t0":4.7854,"tf":6.7854,"genTime":4.7853,"actualGenTime":4.7854,"spaces":[3.0000,4.0000],"segStart":[4.7854,5.7854],"segEnd":[5.7854,6.7854]},
            {"veh":6,"k":2,"t0":6.3561,"tf":8.7123,"genTime":6.3561,"actualGenTime":6.3562,"spaces":[2.0000,5.0000,4.0000],"segStart":[6.3561,7.1415,7.9269],"segEnd":[7.1415,7.9269,8.7123]},
            {"veh":8,"k":1,"t0":2.0000,"tf":4.3562,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[4.0000,5.0000,2.0000],"segStart":[2.0000,2.7854,3.5708],"segEnd":[2.7854,3.5708,4.3562]},
            {"veh":10,"k":2,"t0":7.9999,"tf":10.3561,"genTime":7.9999,"actualGenTime":7.9999,"spaces":[3.0000,5.0000,1.0000],"segStart":[7.9999,8.7853,9.5707],"segEnd":[8.7853,9.5707,10.3561]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":23,"tw":28.467,"f":-0.00,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": -0.00,
          "vehicles": [
            {"veh":2,"k":2,"t0":4.7853,"tf":6.7853,"genTime":4.7853,"actualGenTime":4.7854,"spaces":[4.0000,1.0000],"segStart":[4.7853,5.7853],"segEnd":[5.7853,6.7853]},
            {"veh":5,"k":2,"t0":8.3562,"tf":10.7124,"genTime":8.3562,"actualGenTime":8.3562,"spaces":[3.0000,5.0000,1.0000],"segStart":[8.3562,9.1416,9.9270],"segEnd":[9.1416,9.9270,10.7124]},
            {"veh":6,"k":1,"t0":2.0000,"tf":4.3562,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[1.0000,5.0000,3.0000],"segStart":[2.0000,2.7854,3.5708],"segEnd":[2.7854,3.5708,4.3562]},
            {"veh":7,"k":1,"t0":4.0000,"tf":6.0000,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[1.0000,2.0000],"segStart":[4.0000,5.0000],"segEnd":[5.0000,6.0000]},
            {"veh":10,"k":3,"t0":12.3561,"tf":14.3561,"genTime":12.3561,"actualGenTime":12.3561,"spaces":[4.0000,1.0000],"segStart":[12.3561,13.3561],"segEnd":[13.3561,14.3561]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":10,"tw":6.356,"f":0.00,"isLeaf":false,"isRoot":false},
        {"id":3,"orig":11,"tw":6.356,"f":0.00,"isLeaf":false,"isRoot":false},
        {"id":4,"orig":12,"tw":7.356,"f":0.00,"isLeaf":false,"isRoot":false},
        {"id":5,"orig":15,"tw":8.178,"f":0.00,"isLeaf":false,"isRoot":false},
        {"id":6,"orig":16,"tw":8.964,"f":0.18,"isLeaf":false,"isRoot":false},
        {"id":7,"orig":17,"tw":8.356,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":8,"orig":23,"tw":24.289,"f":0.36,"isLeaf":true,"isRoot":false},
        {"id":9,"orig":24,"tw":8.178,"f":1.79,"isLeaf":false,"isRoot":false},
        {"id":10,"orig":25,"tw":8.964,"f":1.96,"isLeaf":false,"isRoot":false},
        {"id":11,"orig":26,"tw":8.356,"f":1.79,"isLeaf":false,"isRoot":false},
        {"id":12,"orig":31,"tw":24.289,"f":1.79,"isLeaf":true,"isRoot":false},
        {"id":13,"orig":37,"tw":24.289,"f":2.14,"isLeaf":true,"isRoot":false},
        {"id":14,"orig":41,"tw":24.289,"f":3.75,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [3,5],
        [5,6],
        [5,7],
        [7,8],
        [4,9],
        [9,10],
        [9,11],
        [6,12],
        [11,13],
        [10,14]
      ],
      "optimalPath": [1,2,3,5,7,8],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2,3,5,7,8],
        [1,2,3,5,6,12],
        [1,2,4,9,11,13],
        [1,2,4,9,10,14]
      ],
      "leafGantts": [
        {
          "fCost": 0.36,
          "vehicles": [
            {"veh":1,"k":1,"t0":2.0000,"tf":4.3562,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000,5.0000,1.0000],"segStart":[2.0000,2.7854,3.5708],"segEnd":[2.7854,3.5708,4.3562]},
            {"veh":4,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[2.0000,3.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":5,"k":1,"t0":4.0000,"tf":6.3562,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[2.0000,5.0000,4.0000],"segStart":[4.0000,4.7854,5.5708],"segEnd":[4.7854,5.5708,6.3562]},
            {"veh":7,"k":2,"t0":8.3562,"tf":9.1416,"genTime":8.0000,"actualGenTime":8.1782,"spaces":[1.0000],"segStart":[8.3562],"segEnd":[9.1416]},
            {"veh":9,"k":2,"t0":6.3562,"tf":8.3562,"genTime":6.3560,"actualGenTime":6.3561,"spaces":[4.0000,1.0000],"segStart":[6.3562,7.3562],"segEnd":[7.3562,8.3562]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 1.79,
          "vehicles": [
            {"veh":1,"k":1,"t0":2.0000,"tf":4.3562,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000,5.0000,1.0000],"segStart":[2.0000,2.7854,3.5708],"segEnd":[2.7854,3.5708,4.3562]},
            {"veh":4,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[2.0000,3.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":5,"k":1,"t0":4.0000,"tf":6.3562,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[2.0000,5.0000,4.0000],"segStart":[4.0000,4.7854,5.5708],"segEnd":[4.7854,5.5708,6.3562]},
            {"veh":7,"k":2,"t0":8.1782,"tf":8.9636,"genTime":8.0000,"actualGenTime":8.1782,"spaces":[1.0000],"segStart":[8.1782],"segEnd":[8.9636]},
            {"veh":9,"k":2,"t0":7.9636,"tf":9.9636,"genTime":6.3560,"actualGenTime":6.3561,"spaces":[4.0000,1.0000],"segStart":[7.9636,8.9636],"segEnd":[8.9636,9.9636]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 2.14,
          "vehicles": [
            {"veh":1,"k":1,"t0":2.0000,"tf":4.3562,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000,5.0000,1.0000],"segStart":[2.0000,2.7854,3.5708],"segEnd":[2.7854,3.5708,4.3562]},
            {"veh":4,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[2.0000,3.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":5,"k":1,"t0":5.7853,"tf":8.1415,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[2.0000,5.0000,4.0000],"segStart":[5.7853,6.5707,7.3561],"segEnd":[6.5707,7.3561,8.1415]},
            {"veh":7,"k":2,"t0":8.3561,"tf":9.1415,"genTime":8.0000,"actualGenTime":8.1782,"spaces":[1.0000],"segStart":[8.3561],"segEnd":[9.1415]},
            {"veh":9,"k":2,"t0":6.3561,"tf":8.3561,"genTime":6.3560,"actualGenTime":6.3561,"spaces":[4.0000,1.0000],"segStart":[6.3561,7.3561],"segEnd":[7.3561,8.3561]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 3.75,
          "vehicles": [
            {"veh":1,"k":1,"t0":2.0000,"tf":4.3562,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000,5.0000,1.0000],"segStart":[2.0000,2.7854,3.5708],"segEnd":[2.7854,3.5708,4.3562]},
            {"veh":4,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[2.0000,3.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":5,"k":1,"t0":5.7853,"tf":8.1415,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[2.0000,5.0000,4.0000],"segStart":[5.7853,6.5707,7.3561],"segEnd":[6.5707,7.3561,8.1415]},
            {"veh":7,"k":2,"t0":8.1782,"tf":8.9636,"genTime":8.0000,"actualGenTime":8.1782,"spaces":[1.0000],"segStart":[8.1782],"segEnd":[8.9636]},
            {"veh":9,"k":2,"t0":8.1415,"tf":10.1415,"genTime":6.3560,"actualGenTime":6.3561,"spaces":[4.0000,1.0000],"segStart":[8.1415,9.1415],"segEnd":[9.1415,10.1415]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":17,"tw":22.467,"f":-0.00,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": -0.00,
          "vehicles": [
            {"veh":3,"k":1,"t0":2.0000,"tf":2.7854,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[4.0000],"segStart":[2.0000],"segEnd":[2.7854]},
            {"veh":4,"k":2,"t0":5.9998,"tf":6.7852,"genTime":5.9997,"actualGenTime":5.9998,"spaces":[2.0000],"segStart":[5.9998],"segEnd":[6.7852]},
            {"veh":8,"k":2,"t0":6.3562,"tf":8.3562,"genTime":6.3561,"actualGenTime":6.3562,"spaces":[1.0000,2.0000],"segStart":[6.3562,7.3562],"segEnd":[7.3562,8.3562]},
            {"veh":9,"k":1,"t0":2.0000,"tf":4.3562,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000,5.0000,1.0000],"segStart":[2.0000,2.7854,3.5708],"segEnd":[2.7854,3.5708,4.3562]},
            {"veh":10,"k":1,"t0":4.0000,"tf":6.0000,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[3.0000,4.0000],"segStart":[4.0000,5.0000],"segEnd":[5.0000,6.0000]}
          ],
          "numSpaces": 5
        }
      ]
    }
  }
};
