// Interactive decision-tree data — 10r_S5
// Auto-generated by export_interactive_tree.m
window.ALL_INTERACTIVE_TREES = window.ALL_INTERACTIVE_TREES || {};
window.ALL_INTERACTIVE_TREES["10r_S5"] = {
  "numInt": 4,
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":15,"tw":27.218,"f":-0.02,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": -0.02,
          "vehicles": [
            {"veh":1,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[1.0000,2.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":2,"k":1,"t0":4.0000,"tf":4.7854,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[1.0000],"segStart":[4.0000],"segEnd":[4.7854]},
            {"veh":3,"k":3,"t0":11.1071,"tf":13.1071,"genTime":11.1168,"actualGenTime":11.1122,"spaces":[3.0000,4.0000],"segStart":[11.1071,12.1071],"segEnd":[12.1071,13.1071]},
            {"veh":5,"k":2,"t0":6.0000,"tf":8.0000,"genTime":6.0000,"actualGenTime":6.0000,"spaces":[3.0000,4.0000],"segStart":[6.0000,7.0000],"segEnd":[7.0000,8.0000]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":24,"tw":24.467,"f":0.57,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 0.57,
          "vehicles": [
            {"veh":2,"k":2,"t0":7.3565,"tf":9.3565,"genTime":6.7854,"actualGenTime":7.0704,"spaces":[4.0000,1.0000],"segStart":[7.3565,8.3565],"segEnd":[8.3565,9.3565]},
            {"veh":4,"k":2,"t0":8.3562,"tf":10.7124,"genTime":8.3561,"actualGenTime":8.3562,"spaces":[3.0000,5.0000,1.0000],"segStart":[8.3562,9.1416,9.9270],"segEnd":[9.1416,9.9270,10.7124]},
            {"veh":7,"k":2,"t0":6.0003,"tf":8.3565,"genTime":5.9993,"actualGenTime":5.9992,"spaces":[3.0000,5.0000,1.0000],"segStart":[6.0003,6.7857,7.5711],"segEnd":[6.7857,7.5711,8.3565]},
            {"veh":8,"k":1,"t0":2.0000,"tf":4.3562,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[2.0000,5.0000,4.0000],"segStart":[2.0000,2.7854,3.5708],"segEnd":[2.7854,3.5708,4.3562]},
            {"veh":9,"k":1,"t0":4.0000,"tf":4.7854,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[2.0000],"segStart":[4.0000],"segEnd":[4.7854]},
            {"veh":10,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[1.0000,2.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":20,"tw":23.013,"f":1.04,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 1.04,
          "vehicles": [
            {"veh":3,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[2.0000,3.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":4,"k":1,"t0":4.0000,"tf":6.3562,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[2.0000,5.0000,4.0000],"segStart":[4.0000,4.7854,5.5708],"segEnd":[4.7854,5.5708,6.3562]},
            {"veh":6,"k":2,"t0":6.8000,"tf":8.8000,"genTime":6.0000,"actualGenTime":6.4011,"spaces":[4.0000,1.0000],"segStart":[6.8000,7.8000],"segEnd":[7.8000,8.8000]},
            {"veh":7,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000,4.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":9,"k":2,"t0":7.0146,"tf":7.8000,"genTime":6.7855,"actualGenTime":6.9011,"spaces":[1.0000],"segStart":[7.0146],"segEnd":[7.8000]},
            {"veh":10,"k":2,"t0":6.0146,"tf":8.0146,"genTime":6.0090,"actualGenTime":6.0128,"spaces":[1.0000,2.0000],"segStart":[6.0146,7.0146],"segEnd":[7.0146,8.0146]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":14,"tw":22.496,"f":0.76,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 0.76,
          "vehicles": [
            {"veh":1,"k":2,"t0":5.9878,"tf":8.3440,"genTime":5.9927,"actualGenTime":5.9894,"spaces":[1.0000,5.0000,3.0000],"segStart":[5.9878,6.7732,7.5586],"segEnd":[6.7732,7.5586,8.3440]},
            {"veh":3,"k":2,"t0":6.7732,"tf":9.1294,"genTime":6.0001,"actualGenTime":6.3859,"spaces":[2.0000,5.0000,4.0000],"segStart":[6.7732,7.5586,8.3440],"segEnd":[7.5586,8.3440,9.1294]},
            {"veh":5,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000,4.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":6,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[4.0000,1.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]}
          ],
          "numSpaces": 5
        }
      ]
    }
  }
};
