// Interactive decision-tree data — 8r_S1
// Auto-generated by export_interactive_tree.m
window.ALL_INTERACTIVE_TREES = window.ALL_INTERACTIVE_TREES || {};
window.ALL_INTERACTIVE_TREES["8r_S1"] = {
  "numInt": 4,
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":16,"tw":22.111,"f":-0.00,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": -0.00,
          "vehicles": [
            {"veh":2,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[1.0000,2.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":3,"k":1,"t0":4.0000,"tf":4.7854,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[1.0000],"segStart":[4.0000],"segEnd":[4.7854]},
            {"veh":5,"k":2,"t0":5.9999,"tf":8.3561,"genTime":5.9999,"actualGenTime":6.0000,"spaces":[2.0000,5.0000,4.0000],"segStart":[5.9999,6.7853,7.5707],"segEnd":[6.7853,7.5707,8.3561]},
            {"veh":6,"k":2,"t0":4.7853,"tf":6.7853,"genTime":4.7853,"actualGenTime":4.7854,"spaces":[3.0000,4.0000],"segStart":[4.7853,5.7853],"segEnd":[5.7853,6.7853]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":14,"tw":23.339,"f":0.09,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 0.09,
          "vehicles": [
            {"veh":3,"k":2,"t0":6.7862,"tf":9.1424,"genTime":6.7844,"actualGenTime":6.7840,"spaces":[4.0000,5.0000,2.0000],"segStart":[6.7862,7.5716,8.3570],"segEnd":[7.5716,8.3570,9.1424]},
            {"veh":4,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[1.0000,2.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":5,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[2.0000,3.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":7,"k":2,"t0":7.2285,"tf":9.2285,"genTime":7.1937,"actualGenTime":7.2158,"spaces":[3.0000,4.0000],"segStart":[7.2285,8.2285],"segEnd":[8.2285,9.2285]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":3,"tw":2.785,"f":0.00,"isLeaf":false,"isRoot":false},
        {"id":3,"orig":4,"tw":3.571,"f":0.00,"isLeaf":false,"isRoot":false},
        {"id":4,"orig":5,"tw":3.571,"f":0.00,"isLeaf":false,"isRoot":false},
        {"id":5,"orig":22,"tw":27.249,"f":0.78,"isLeaf":true,"isRoot":false},
        {"id":6,"orig":31,"tw":27.249,"f":0.78,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [3,5],
        [4,6]
      ],
      "optimalPath": [1,2,3,5],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2,3,5],
        [1,2,4,6]
      ],
      "leafGantts": [
        {
          "fCost": 0.78,
          "vehicles": [
            {"veh":1,"k":1,"t0":2.0000,"tf":4.3562,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000,5.0000,1.0000],"segStart":[2.0000,2.7854,3.5708],"segEnd":[2.7854,3.5708,4.3562]},
            {"veh":3,"k":3,"t0":11.1385,"tf":11.9239,"genTime":11.1372,"actualGenTime":11.1368,"spaces":[1.0000],"segStart":[11.1385],"segEnd":[11.9239]},
            {"veh":4,"k":2,"t0":6.0000,"tf":6.7854,"genTime":6.0000,"actualGenTime":6.0000,"spaces":[1.0000],"segStart":[6.0000],"segEnd":[6.7854]},
            {"veh":7,"k":1,"t0":2.7854,"tf":5.1416,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[2.0000,5.0000,4.0000],"segStart":[2.7854,3.5708,4.3562],"segEnd":[3.5708,4.3562,5.1416]},
            {"veh":8,"k":2,"t0":6.3562,"tf":8.3562,"genTime":6.3561,"actualGenTime":6.3562,"spaces":[4.0000,1.0000],"segStart":[6.3562,7.3562],"segEnd":[7.3562,8.3562]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 0.78,
          "vehicles": [
            {"veh":1,"k":1,"t0":2.7854,"tf":5.1416,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000,5.0000,1.0000],"segStart":[2.7854,3.5708,4.3562],"segEnd":[3.5708,4.3562,5.1416]},
            {"veh":3,"k":3,"t0":11.1385,"tf":11.9239,"genTime":11.1372,"actualGenTime":11.1368,"spaces":[1.0000],"segStart":[11.1385],"segEnd":[11.9239]},
            {"veh":4,"k":2,"t0":6.0000,"tf":6.7854,"genTime":6.0000,"actualGenTime":6.0000,"spaces":[1.0000],"segStart":[6.0000],"segEnd":[6.7854]},
            {"veh":7,"k":1,"t0":2.0000,"tf":4.3562,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[2.0000,5.0000,4.0000],"segStart":[2.0000,2.7854,3.5708],"segEnd":[2.7854,3.5708,4.3562]},
            {"veh":8,"k":2,"t0":6.3562,"tf":8.3562,"genTime":6.3561,"actualGenTime":6.3562,"spaces":[4.0000,1.0000],"segStart":[6.3562,7.3562],"segEnd":[7.3562,8.3562]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":11,"tw":22.111,"f":-0.00,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": -0.00,
          "vehicles": [
            {"veh":2,"k":2,"t0":5.9999,"tf":8.3561,"genTime":5.9999,"actualGenTime":6.0000,"spaces":[1.0000,5.0000,3.0000],"segStart":[5.9999,6.7853,7.5707],"segEnd":[6.7853,7.5707,8.3561]},
            {"veh":6,"k":1,"t0":2.0000,"tf":2.7854,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[4.0000],"segStart":[2.0000],"segEnd":[2.7854]},
            {"veh":8,"k":1,"t0":2.0000,"tf":4.3562,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000,5.0000,1.0000],"segStart":[2.0000,2.7854,3.5708],"segEnd":[2.7854,3.5708,4.3562]}
          ],
          "numSpaces": 5
        }
      ]
    }
  }
};
