// Interactive decision-tree data — tr_15r_S1
// Auto-generated by export_interactive_tree.m
window.ALL_INTERACTIVE_TREES = window.ALL_INTERACTIVE_TREES || {};
window.ALL_INTERACTIVE_TREES["tr_15r_S1"] = {
  "numInt": 5,
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":24,"tw":41.479,"f":0.12,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 0.12,
          "vehicles": [
            {"veh":2,"k":1,"t0":13.2500,"tf":15.6062,"genTime":13.2500,"actualGenTime":13.2500,"spaces":[3.0000,5.0000,1.0000],"segStart":[13.2500,14.0354,14.8208],"segEnd":[14.0354,14.8208,15.6062]},
            {"veh":4,"k":2,"t0":22.0354,"tf":22.8208,"genTime":22.0354,"actualGenTime":22.0354,"spaces":[2.0000],"segStart":[22.0354],"segEnd":[22.8208]},
            {"veh":6,"k":2,"t0":22.2500,"tf":24.2500,"genTime":22.2500,"actualGenTime":22.2500,"spaces":[1.0000,2.0000],"segStart":[22.2500,23.2500],"segEnd":[23.2500,24.2500]},
            {"veh":7,"k":2,"t0":25.3684,"tf":27.7246,"genTime":25.3174,"actualGenTime":25.3464,"spaces":[1.0000,5.0000,3.0000],"segStart":[25.3684,26.1538,26.9392],"segEnd":[26.1538,26.9392,27.7246]},
            {"veh":13,"k":1,"t0":19.2500,"tf":20.0354,"genTime":19.2500,"actualGenTime":19.2500,"spaces":[4.0000],"segStart":[19.2500],"segEnd":[20.0354]},
            {"veh":14,"k":1,"t0":21.2500,"tf":22.0354,"genTime":21.2500,"actualGenTime":21.2500,"spaces":[4.0000],"segStart":[21.2500],"segEnd":[22.0354]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":29,"tw":43.361,"f":-0.00,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": -0.00,
          "vehicles": [
            {"veh":2,"k":2,"t0":20.6062,"tf":22.9623,"genTime":20.6062,"actualGenTime":20.6062,"spaces":[4.0000,5.0000,2.0000],"segStart":[20.6062,21.3916,22.1769],"segEnd":[21.3916,22.1769,22.9623]},
            {"veh":3,"k":1,"t0":14.2500,"tf":16.6062,"genTime":14.2500,"actualGenTime":14.2500,"spaces":[3.0000,5.0000,1.0000],"segStart":[14.2500,15.0354,15.8208],"segEnd":[15.0354,15.8208,16.6062]},
            {"veh":4,"k":1,"t0":16.2500,"tf":17.0354,"genTime":16.2500,"actualGenTime":16.2500,"spaces":[3.0000],"segStart":[16.2500],"segEnd":[17.0354]},
            {"veh":5,"k":1,"t0":18.2500,"tf":20.2500,"genTime":18.2500,"actualGenTime":18.2500,"spaces":[3.0000,4.0000],"segStart":[18.2500,19.2500],"segEnd":[19.2500,20.2500]},
            {"veh":10,"k":2,"t0":23.0354,"tf":23.8208,"genTime":23.0354,"actualGenTime":23.0354,"spaces":[2.0000],"segStart":[23.0354],"segEnd":[23.8208]},
            {"veh":11,"k":2,"t0":25.0354,"tf":25.8208,"genTime":25.0354,"actualGenTime":25.0354,"spaces":[2.0000],"segStart":[25.0354],"segEnd":[25.8208]},
            {"veh":15,"k":2,"t0":27.2500,"tf":29.6062,"genTime":27.2500,"actualGenTime":27.2500,"spaces":[2.0000,5.0000,4.0000],"segStart":[27.2500,28.0354,28.8208],"segEnd":[28.0354,28.8208,29.6062]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":4,"tw":17.250,"f":0.00,"isLeaf":false,"isRoot":false},
        {"id":3,"orig":6,"tw":18.250,"f":0.00,"isLeaf":false,"isRoot":false},
        {"id":4,"orig":26,"tw":43.146,"f":1.00,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [3,4]
      ],
      "optimalPath": [1,2,3,4],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2,3,4]
      ],
      "leafGantts": [
        {
          "fCost": 1.00,
          "vehicles": [
            {"veh":6,"k":1,"t0":15.2500,"tf":17.2500,"genTime":15.2500,"actualGenTime":15.2500,"spaces":[1.0000,2.0000],"segStart":[15.2500,16.2500],"segEnd":[16.2500,17.2500]},
            {"veh":7,"k":1,"t0":18.2500,"tf":20.2500,"genTime":17.2500,"actualGenTime":17.2500,"spaces":[1.0000,2.0000],"segStart":[18.2500,19.2500],"segEnd":[19.2500,20.2500]},
            {"veh":8,"k":1,"t0":16.2500,"tf":18.2500,"genTime":16.2500,"actualGenTime":16.2500,"spaces":[4.0000,1.0000],"segStart":[16.2500,17.2500],"segEnd":[17.2500,18.2500]},
            {"veh":9,"k":1,"t0":18.2500,"tf":20.2500,"genTime":18.2500,"actualGenTime":18.2500,"spaces":[4.0000,1.0000],"segStart":[18.2500,19.2500],"segEnd":[19.2500,20.2500]},
            {"veh":12,"k":2,"t0":25.6062,"tf":27.9623,"genTime":25.6062,"actualGenTime":25.6062,"spaces":[2.0000,5.0000,4.0000],"segStart":[25.6062,26.3916,27.1769],"segEnd":[26.3916,27.1769,27.9623]},
            {"veh":13,"k":2,"t0":25.0354,"tf":25.8208,"genTime":25.0354,"actualGenTime":25.0354,"spaces":[3.0000],"segStart":[25.0354],"segEnd":[25.8208]},
            {"veh":14,"k":2,"t0":27.0354,"tf":29.0354,"genTime":27.0354,"actualGenTime":27.0354,"spaces":[3.0000,4.0000],"segStart":[27.0354,28.0354],"segEnd":[28.0354,29.0354]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":27,"tw":50.717,"f":-0.00,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": -0.00,
          "vehicles": [
            {"veh":1,"k":1,"t0":12.2500,"tf":14.6062,"genTime":12.2500,"actualGenTime":12.2500,"spaces":[2.0000,5.0000,4.0000],"segStart":[12.2500,13.0354,13.8208],"segEnd":[13.0354,13.8208,14.6062]},
            {"veh":5,"k":2,"t0":25.2500,"tf":27.6062,"genTime":25.2500,"actualGenTime":25.2500,"spaces":[3.0000,5.0000,1.0000],"segStart":[25.2500,26.0354,26.8208],"segEnd":[26.0354,26.8208,27.6062]},
            {"veh":8,"k":2,"t0":23.2500,"tf":25.2500,"genTime":23.2500,"actualGenTime":23.2500,"spaces":[4.0000,1.0000],"segStart":[23.2500,24.2500],"segEnd":[24.2500,25.2500]},
            {"veh":9,"k":2,"t0":25.2501,"tf":26.0355,"genTime":25.2501,"actualGenTime":25.2501,"spaces":[4.0000],"segStart":[25.2501],"segEnd":[26.0355]},
            {"veh":12,"k":1,"t0":18.2500,"tf":20.6062,"genTime":18.2500,"actualGenTime":18.2500,"spaces":[1.0000,5.0000,3.0000],"segStart":[18.2500,19.0354,19.8208],"segEnd":[19.0354,19.8208,20.6062]},
            {"veh":15,"k":3,"t0":34.6061,"tf":36.9623,"genTime":34.6061,"actualGenTime":34.6061,"spaces":[3.0000,5.0000,1.0000],"segStart":[34.6061,35.3915,36.1769],"segEnd":[35.3915,36.1769,36.9623]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "5": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":16,"tw":37.717,"f":-0.00,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": -0.00,
          "vehicles": [
            {"veh":3,"k":2,"t0":21.6062,"tf":23.9624,"genTime":21.6062,"actualGenTime":21.6062,"spaces":[4.0000,5.0000,2.0000],"segStart":[21.6062,22.3916,23.1770],"segEnd":[22.3916,23.1770,23.9624]},
            {"veh":10,"k":1,"t0":17.2500,"tf":18.0354,"genTime":17.2500,"actualGenTime":17.2500,"spaces":[3.0000],"segStart":[17.2500],"segEnd":[18.0354]},
            {"veh":11,"k":1,"t0":19.2500,"tf":20.0354,"genTime":19.2500,"actualGenTime":19.2500,"spaces":[3.0000],"segStart":[19.2500],"segEnd":[20.0354]},
            {"veh":15,"k":1,"t0":20.2500,"tf":22.2500,"genTime":20.2500,"actualGenTime":20.2500,"spaces":[2.0000,3.0000],"segStart":[20.2500,21.2500],"segEnd":[21.2500,22.2500]}
          ],
          "numSpaces": 5
        }
      ]
    }
  }
};
