// Interactive decision-tree data — 10r_S8
// Auto-generated by export_interactive_tree.m
window.ALL_INTERACTIVE_TREES = window.ALL_INTERACTIVE_TREES || {};
window.ALL_INTERACTIVE_TREES["10r_S8"] = {
  "numInt": 4,
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":15,"tw":27.308,"f":0.04,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 0.04,
          "vehicles": [
            {"veh":1,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[1.0000,2.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":2,"k":1,"t0":4.0000,"tf":4.7854,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[1.0000],"segStart":[4.0000],"segEnd":[4.7854]},
            {"veh":3,"k":3,"t0":11.1973,"tf":13.1973,"genTime":11.1746,"actualGenTime":11.1833,"spaces":[3.0000,4.0000],"segStart":[11.1973,12.1973],"segEnd":[12.1973,13.1973]},
            {"veh":5,"k":2,"t0":6.0000,"tf":8.0000,"genTime":6.0000,"actualGenTime":6.0000,"spaces":[3.0000,4.0000],"segStart":[6.0000,7.0000],"segEnd":[7.0000,8.0000]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":24,"tw":24.467,"f":0.54,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 0.54,
          "vehicles": [
            {"veh":2,"k":2,"t0":7.3405,"tf":9.3405,"genTime":6.7854,"actualGenTime":7.0623,"spaces":[4.0000,1.0000],"segStart":[7.3405,8.3405],"segEnd":[8.3405,9.3405]},
            {"veh":4,"k":2,"t0":8.3562,"tf":10.7123,"genTime":8.3562,"actualGenTime":8.3562,"spaces":[3.0000,5.0000,1.0000],"segStart":[8.3562,9.1416,9.9269],"segEnd":[9.1416,9.9269,10.7123]},
            {"veh":7,"k":2,"t0":5.9843,"tf":8.3405,"genTime":5.9902,"actualGenTime":5.9865,"spaces":[3.0000,5.0000,1.0000],"segStart":[5.9843,6.7697,7.5551],"segEnd":[6.7697,7.5551,8.3405]},
            {"veh":8,"k":1,"t0":2.0000,"tf":4.3562,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[2.0000,5.0000,4.0000],"segStart":[2.0000,2.7854,3.5708],"segEnd":[2.7854,3.5708,4.3562]},
            {"veh":9,"k":1,"t0":4.0000,"tf":4.7854,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[2.0000],"segStart":[4.0000],"segEnd":[4.7854]},
            {"veh":10,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[1.0000,2.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":20,"tw":22.963,"f":0.82,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 0.82,
          "vehicles": [
            {"veh":3,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[2.0000,3.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":4,"k":1,"t0":4.0000,"tf":6.3562,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[2.0000,5.0000,4.0000],"segStart":[4.0000,4.7854,5.5708],"segEnd":[4.7854,5.5708,6.3562]},
            {"veh":6,"k":2,"t0":6.7245,"tf":8.7245,"genTime":6.0000,"actualGenTime":6.3575,"spaces":[4.0000,1.0000],"segStart":[6.7245,7.7245],"segEnd":[7.7245,8.7245]},
            {"veh":7,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000,4.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":9,"k":2,"t0":6.9391,"tf":7.7245,"genTime":6.7855,"actualGenTime":6.8575,"spaces":[1.0000],"segStart":[6.9391],"segEnd":[7.7245]},
            {"veh":10,"k":2,"t0":5.9391,"tf":7.9391,"genTime":5.9645,"actualGenTime":5.9470,"spaces":[1.0000,2.0000],"segStart":[5.9391,6.9391],"segEnd":[6.9391,7.9391]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":14,"tw":22.514,"f":0.81,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 0.81,
          "vehicles": [
            {"veh":1,"k":2,"t0":6.0144,"tf":8.3706,"genTime":6.0067,"actualGenTime":6.0106,"spaces":[1.0000,5.0000,3.0000],"segStart":[6.0144,6.7998,7.5852],"segEnd":[6.7998,7.5852,8.3706]},
            {"veh":3,"k":2,"t0":6.7998,"tf":9.1560,"genTime":6.0001,"actualGenTime":6.4001,"spaces":[2.0000,5.0000,4.0000],"segStart":[6.7998,7.5852,8.3706],"segEnd":[7.5852,8.3706,9.1560]},
            {"veh":5,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000,4.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":6,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[4.0000,1.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]}
          ],
          "numSpaces": 5
        }
      ]
    }
  }
};
