// Decision-tree data (5-int) — group=20r  scene=S2
// Auto-generated by export_tree_json_5int.m — do not edit manually.
window.ALL_TREE_DATA = window.ALL_TREE_DATA || {};
window.ALL_TREE_DATA["tr_20r_S2"] = {
  "group": "20r", "scene": "S2",
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":18,"tw":27.693,"f":-0.000,"isPath":true},
        {"id":3,"orig":19,"tw":27.747,"f":-0.000,"isPath":true},
        {"id":4,"orig":20,"tw":27.962,"f":-0.000,"isPath":false},
        {"id":5,"orig":21,"tw":28.748,"f":-0.000,"isPath":false},
        {"id":6,"orig":22,"tw":28.693,"f":0.086,"isPath":false},
        {"id":7,"orig":32,"tw":31.049,"f":1.743,"isPath":false},
        {"id":8,"orig":41,"tw":43.073,"f":0.067,"isPath":true},
        {"id":9,"orig":49,"tw":43.073,"f":2.068,"isPath":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [4,5],
        [4,6],
        [6,7],
        [3,8],
        [5,9]
      ],
      "path": [1,2,3,8]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":37,"tw":41.361,"f":-0.000,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":18,"tw":22.250,"f":-0.000,"isPath":true},
        {"id":3,"orig":19,"tw":22.606,"f":-0.000,"isPath":true},
        {"id":4,"orig":20,"tw":23.035,"f":-0.000,"isPath":false},
        {"id":5,"orig":23,"tw":23.821,"f":1.214,"isPath":false},
        {"id":6,"orig":24,"tw":23.250,"f":-0.000,"isPath":false},
        {"id":7,"orig":45,"tw":48.359,"f":0.314,"isPath":true},
        {"id":8,"orig":65,"tw":48.359,"f":1.387,"isPath":false},
        {"id":9,"orig":83,"tw":48.359,"f":2.743,"isPath":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [4,5],
        [4,6],
        [3,7],
        [6,8],
        [5,9]
      ],
      "path": [1,2,3,7]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":27,"tw":42.361,"f":-0.000,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "5": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":21,"tw":40.717,"f":-0.000,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    }
  }
};
