// Decision-tree data — group=10r  scene=S1
// Auto-generated by export_tree_json.m — do not edit manually.
window.ALL_TREE_DATA = window.ALL_TREE_DATA || {};
window.ALL_TREE_DATA["10r_S1"] = {
  "group": "10r", "scene": "S1",
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":11,"tw":13.241,"f":0.042,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":13,"tw":8.081,"f":-0.000,"isPath":true},
        {"id":3,"orig":14,"tw":8.356,"f":-0.000,"isPath":false},
        {"id":4,"orig":15,"tw":8.356,"f":-0.000,"isPath":true},
        {"id":5,"orig":23,"tw":11.498,"f":3.438,"isPath":false},
        {"id":6,"orig":25,"tw":10.712,"f":0.603,"isPath":true}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [3,5],
        [4,6]
      ],
      "path": [1,2,4,6]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":10,"tw":6.873,"f":-0.000,"isPath":true},
        {"id":3,"orig":11,"tw":7.373,"f":-0.000,"isPath":false},
        {"id":4,"orig":12,"tw":6.971,"f":-0.000,"isPath":true},
        {"id":5,"orig":13,"tw":8.373,"f":0.373,"isPath":false},
        {"id":6,"orig":14,"tw":7.659,"f":0.088,"isPath":false},
        {"id":7,"orig":15,"tw":8.373,"f":-0.000,"isPath":false},
        {"id":8,"orig":16,"tw":7.373,"f":-0.000,"isPath":true},
        {"id":9,"orig":17,"tw":9.373,"f":2.747,"isPath":false},
        {"id":10,"orig":18,"tw":9.159,"f":1.588,"isPath":false},
        {"id":11,"orig":19,"tw":7.971,"f":-0.029,"isPath":false},
        {"id":12,"orig":20,"tw":7.756,"f":0.186,"isPath":true},
        {"id":13,"orig":22,"tw":8.659,"f":0.747,"isPath":false},
        {"id":14,"orig":23,"tw":8.659,"f":0.088,"isPath":false},
        {"id":15,"orig":24,"tw":9.659,"f":3.406,"isPath":false},
        {"id":16,"orig":26,"tw":8.756,"f":0.913,"isPath":true},
        {"id":17,"orig":27,"tw":9.159,"f":1.932,"isPath":false},
        {"id":18,"orig":30,"tw":10.659,"f":3.406,"isPath":false},
        {"id":19,"orig":33,"tw":11.159,"f":5.120,"isPath":false},
        {"id":20,"orig":34,"tw":10.159,"f":5.335,"isPath":false},
        {"id":21,"orig":35,"tw":10.159,"f":5.120,"isPath":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [3,5],
        [3,6],
        [3,7],
        [4,8],
        [7,9],
        [7,10],
        [8,11],
        [8,12],
        [6,13],
        [6,14],
        [14,15],
        [12,16],
        [11,17],
        [13,18],
        [5,19],
        [9,20],
        [10,21]
      ],
      "path": [1,2,4,8,12,16]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":8,"tw":7.207,"f":0.000,"isPath":true},
        {"id":3,"orig":9,"tw":7.616,"f":0.000,"isPath":true},
        {"id":4,"orig":10,"tw":7.992,"f":0.000,"isPath":false},
        {"id":5,"orig":13,"tw":9.187,"f":0.877,"isPath":true},
        {"id":6,"orig":14,"tw":9.563,"f":1.629,"isPath":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [3,5],
        [4,6]
      ],
      "path": [1,2,3,5]
    }
  }
};
