// Decision-tree data — group=10r  scene=S9
// Auto-generated by export_tree_json.m — do not edit manually.
window.ALL_TREE_DATA = window.ALL_TREE_DATA || {};
window.ALL_TREE_DATA["10r_S9"] = {
  "group": "10r", "scene": "S9",
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":21,"tw":22.899,"f":0.005,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":5,"tw":3.571,"f":0.000,"isPath":true},
        {"id":3,"orig":6,"tw":4.000,"f":0.000,"isPath":true},
        {"id":4,"orig":7,"tw":4.356,"f":-0.000,"isPath":false},
        {"id":5,"orig":8,"tw":5.356,"f":1.356,"isPath":false},
        {"id":6,"orig":11,"tw":6.906,"f":0.429,"isPath":true},
        {"id":7,"orig":12,"tw":7.691,"f":0.549,"isPath":false},
        {"id":8,"orig":13,"tw":7.021,"f":0.429,"isPath":true},
        {"id":9,"orig":25,"tw":25.253,"f":0.685,"isPath":true},
        {"id":10,"orig":31,"tw":25.253,"f":2.241,"isPath":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [4,5],
        [3,6],
        [6,7],
        [6,8],
        [8,9],
        [7,10]
      ],
      "path": [1,2,3,6,8,9]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":15,"tw":24.467,"f":-0.000,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":10,"tw":6.178,"f":-0.000,"isPath":true},
        {"id":3,"orig":11,"tw":6.785,"f":-0.000,"isPath":false},
        {"id":4,"orig":12,"tw":6.356,"f":-0.000,"isPath":true},
        {"id":5,"orig":13,"tw":7.178,"f":-0.000,"isPath":false},
        {"id":6,"orig":14,"tw":7.571,"f":1.215,"isPath":false},
        {"id":7,"orig":22,"tw":22.289,"f":0.356,"isPath":true},
        {"id":8,"orig":24,"tw":9.571,"f":2.785,"isPath":false},
        {"id":9,"orig":29,"tw":22.289,"f":1.785,"isPath":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [3,5],
        [3,6],
        [4,7],
        [6,8],
        [5,9]
      ],
      "path": [1,2,4,7]
    }
  }
};
