// Decision-tree data — group=15r  scene=S1
// Auto-generated by export_tree_json.m — do not edit manually.
window.ALL_TREE_DATA = window.ALL_TREE_DATA || {};
window.ALL_TREE_DATA["15r_S1"] = {
  "group": "15r", "scene": "S1",
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":17,"tw":14.356,"f":-0.000,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":12,"tw":7.744,"f":-0.000,"isPath":true},
        {"id":3,"orig":13,"tw":7.939,"f":-0.062,"isPath":true},
        {"id":4,"orig":14,"tw":8.000,"f":-0.000,"isPath":false},
        {"id":5,"orig":20,"tw":11.000,"f":3.173,"isPath":false},
        {"id":6,"orig":22,"tw":10.000,"f":0.306,"isPath":true}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [4,5],
        [3,6]
      ],
      "path": [1,2,3,6]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":15,"tw":9.392,"f":-0.000,"isPath":true},
        {"id":3,"orig":16,"tw":10.392,"f":0.392,"isPath":false},
        {"id":4,"orig":17,"tw":9.786,"f":-0.000,"isPath":true},
        {"id":5,"orig":18,"tw":10.786,"f":0.786,"isPath":true},
        {"id":6,"orig":20,"tw":12.392,"f":1.999,"isPath":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [4,5],
        [3,6]
      ],
      "path": [1,2,4,5]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":19,"tw":10.356,"f":-0.000,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    }
  }
};
