// Decision-tree data — group=10r  scene=S2
// Auto-generated by export_tree_json.m — do not edit manually.
window.ALL_TREE_DATA = window.ALL_TREE_DATA || {};
window.ALL_TREE_DATA["10r_S2"] = {
  "group": "10r", "scene": "S2",
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":5,"tw":3.571,"f":0.000,"isPath":true},
        {"id":3,"orig":6,"tw":4.000,"f":0.000,"isPath":true},
        {"id":4,"orig":7,"tw":4.000,"f":0.000,"isPath":false},
        {"id":5,"orig":9,"tw":4.785,"f":0.000,"isPath":false},
        {"id":6,"orig":10,"tw":4.356,"f":-0.000,"isPath":false},
        {"id":7,"orig":11,"tw":4.785,"f":-0.000,"isPath":false},
        {"id":8,"orig":12,"tw":4.785,"f":-0.000,"isPath":false},
        {"id":9,"orig":13,"tw":5.356,"f":-0.000,"isPath":false},
        {"id":10,"orig":14,"tw":5.571,"f":0.785,"isPath":false},
        {"id":11,"orig":15,"tw":5.571,"f":-0.000,"isPath":false},
        {"id":12,"orig":16,"tw":4.785,"f":-0.000,"isPath":false},
        {"id":13,"orig":17,"tw":5.785,"f":-0.000,"isPath":false},
        {"id":14,"orig":18,"tw":6.000,"f":-0.000,"isPath":false},
        {"id":15,"orig":20,"tw":7.000,"f":-0.000,"isPath":false},
        {"id":16,"orig":21,"tw":6.356,"f":1.571,"isPath":false},
        {"id":17,"orig":32,"tw":4.785,"f":-0.000,"isPath":false},
        {"id":18,"orig":33,"tw":4.785,"f":-0.000,"isPath":false},
        {"id":19,"orig":34,"tw":5.000,"f":1.000,"isPath":false},
        {"id":20,"orig":35,"tw":5.571,"f":-0.000,"isPath":false},
        {"id":21,"orig":45,"tw":22.111,"f":0.429,"isPath":true},
        {"id":22,"orig":62,"tw":8.356,"f":5.927,"isPath":false},
        {"id":23,"orig":70,"tw":22.111,"f":2.429,"isPath":false},
        {"id":24,"orig":76,"tw":22.111,"f":2.785,"isPath":false},
        {"id":25,"orig":77,"tw":8.000,"f":7.000,"isPath":false},
        {"id":26,"orig":83,"tw":22.111,"f":3.712,"isPath":false},
        {"id":27,"orig":89,"tw":22.111,"f":4.000,"isPath":false},
        {"id":28,"orig":95,"tw":22.111,"f":4.000,"isPath":false},
        {"id":29,"orig":100,"tw":22.111,"f":4.356,"isPath":false},
        {"id":30,"orig":106,"tw":22.111,"f":4.571,"isPath":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [4,5],
        [4,6],
        [6,7],
        [6,8],
        [7,9],
        [7,10],
        [8,11],
        [8,12],
        [11,13],
        [11,14],
        [14,15],
        [14,16],
        [5,17],
        [5,18],
        [17,19],
        [17,20],
        [3,21],
        [16,22],
        [19,23],
        [12,24],
        [15,25],
        [9,26],
        [18,27],
        [20,28],
        [10,29],
        [13,30]
      ],
      "path": [1,2,3,21]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":10,"tw":7.419,"f":-0.000,"isPath":true},
        {"id":3,"orig":11,"tw":7.826,"f":-0.000,"isPath":true},
        {"id":4,"orig":12,"tw":8.419,"f":0.419,"isPath":false},
        {"id":5,"orig":15,"tw":10.419,"f":2.052,"isPath":false},
        {"id":6,"orig":19,"tw":22.937,"f":0.867,"isPath":true}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [4,5],
        [3,6]
      ],
      "path": [1,2,3,6]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":17,"tw":24.111,"f":-0.000,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":7,"tw":6.910,"f":-0.000,"isPath":true},
        {"id":3,"orig":8,"tw":7.026,"f":-0.000,"isPath":true},
        {"id":4,"orig":9,"tw":7.910,"f":-0.000,"isPath":false},
        {"id":5,"orig":13,"tw":9.910,"f":2.034,"isPath":false},
        {"id":6,"orig":19,"tw":28.467,"f":0.267,"isPath":true}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [4,5],
        [3,6]
      ],
      "path": [1,2,3,6]
    }
  }
};
