// Decision-tree data — group=10r  scene=S3_p9
// Auto-generated by export_tree_json.m — do not edit manually.
window.ALL_TREE_DATA = window.ALL_TREE_DATA || {};
window.ALL_TREE_DATA["10r_S3_p9"] = {
  "group": "10r", "scene": "S3_p9",
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":21,"tw":23.441,"f":-0.053,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":9,"tw":6.852,"f":1.356,"isPath":true},
        {"id":3,"orig":10,"tw":7.637,"f":1.422,"isPath":false},
        {"id":4,"orig":11,"tw":6.938,"f":1.356,"isPath":true},
        {"id":5,"orig":23,"tw":25.253,"f":1.446,"isPath":true},
        {"id":6,"orig":29,"tw":25.253,"f":3.059,"isPath":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [4,5],
        [3,6]
      ],
      "path": [1,2,4,5]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":15,"tw":24.467,"f":-0.000,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":10,"tw":6.178,"f":0.000,"isPath":true},
        {"id":3,"orig":11,"tw":6.785,"f":-0.000,"isPath":false},
        {"id":4,"orig":12,"tw":6.356,"f":0.000,"isPath":true},
        {"id":5,"orig":13,"tw":7.178,"f":-0.000,"isPath":false},
        {"id":6,"orig":14,"tw":7.571,"f":1.215,"isPath":false},
        {"id":7,"orig":22,"tw":22.289,"f":0.356,"isPath":true},
        {"id":8,"orig":29,"tw":22.289,"f":1.785,"isPath":false},
        {"id":9,"orig":33,"tw":22.289,"f":2.785,"isPath":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [3,5],
        [3,6],
        [4,7],
        [5,8],
        [6,9]
      ],
      "path": [1,2,4,7]
    }
  }
};
