// Decision-tree data — group=10r  scene=S8
// Auto-generated by export_tree_json.m — do not edit manually.
window.ALL_TREE_DATA = window.ALL_TREE_DATA || {};
window.ALL_TREE_DATA["10r_S8"] = {
  "group": "10r", "scene": "S8",
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":15,"tw":27.308,"f":0.036,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":13,"tw":8.061,"f":-0.000,"isPath":true},
        {"id":3,"orig":14,"tw":8.356,"f":-0.000,"isPath":false},
        {"id":4,"orig":15,"tw":8.341,"f":-0.016,"isPath":true},
        {"id":5,"orig":23,"tw":11.498,"f":3.417,"isPath":false},
        {"id":6,"orig":30,"tw":24.467,"f":0.539,"isPath":true}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [3,5],
        [4,6]
      ],
      "path": [1,2,4,6]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":8,"tw":6.352,"f":0.000,"isPath":true},
        {"id":3,"orig":9,"tw":6.356,"f":-0.000,"isPath":true},
        {"id":4,"orig":10,"tw":6.852,"f":0.000,"isPath":false},
        {"id":5,"orig":13,"tw":7.356,"f":-0.000,"isPath":true},
        {"id":6,"orig":14,"tw":7.939,"f":-0.061,"isPath":false},
        {"id":7,"orig":15,"tw":7.724,"f":0.154,"isPath":true},
        {"id":8,"orig":24,"tw":9.142,"f":1.866,"isPath":false},
        {"id":9,"orig":29,"tw":22.963,"f":0.817,"isPath":true},
        {"id":10,"orig":36,"tw":22.963,"f":4.756,"isPath":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [3,5],
        [5,6],
        [5,7],
        [6,8],
        [7,9],
        [4,10]
      ],
      "path": [1,2,3,5,7,9]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":8,"tw":7.188,"f":0.000,"isPath":true},
        {"id":3,"orig":9,"tw":7.585,"f":0.000,"isPath":true},
        {"id":4,"orig":10,"tw":7.973,"f":0.000,"isPath":false},
        {"id":5,"orig":14,"tw":9.544,"f":1.590,"isPath":false},
        {"id":6,"orig":17,"tw":22.514,"f":0.814,"isPath":true}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [4,5],
        [3,6]
      ],
      "path": [1,2,3,6]
    }
  }
};
