// Decision-tree data — group=10r  scene=S7
// Auto-generated by export_tree_json.m — do not edit manually.
window.ALL_TREE_DATA = window.ALL_TREE_DATA || {};
window.ALL_TREE_DATA["10r_S7"] = {
  "group": "10r", "scene": "S7",
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":15,"tw":29.218,"f":-0.019,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":13,"tw":9.071,"f":-0.000,"isPath":true},
        {"id":3,"orig":14,"tw":9.356,"f":-0.000,"isPath":false},
        {"id":4,"orig":15,"tw":9.356,"f":-0.000,"isPath":true},
        {"id":5,"orig":16,"tw":10.071,"f":0.286,"isPath":false},
        {"id":6,"orig":17,"tw":10.142,"f":0.785,"isPath":false},
        {"id":7,"orig":18,"tw":10.142,"f":-0.000,"isPath":false},
        {"id":8,"orig":19,"tw":9.356,"f":0.000,"isPath":true},
        {"id":9,"orig":23,"tw":10.142,"f":0.286,"isPath":false},
        {"id":10,"orig":24,"tw":10.856,"f":0.286,"isPath":false},
        {"id":11,"orig":28,"tw":12.498,"f":3.427,"isPath":false},
        {"id":12,"orig":32,"tw":12.498,"f":3.712,"isPath":false},
        {"id":13,"orig":39,"tw":25.467,"f":0.571,"isPath":true},
        {"id":14,"orig":40,"tw":10.927,"f":0.785,"isPath":false},
        {"id":15,"orig":41,"tw":11.142,"f":2.142,"isPath":false},
        {"id":16,"orig":42,"tw":11.712,"f":0.785,"isPath":false},
        {"id":17,"orig":43,"tw":12.712,"f":3.712,"isPath":false},
        {"id":18,"orig":49,"tw":25.467,"f":2.356,"isPath":false},
        {"id":19,"orig":55,"tw":25.467,"f":4.857,"isPath":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [3,5],
        [3,6],
        [4,7],
        [4,8],
        [5,9],
        [5,10],
        [9,11],
        [7,12],
        [8,13],
        [6,14],
        [14,15],
        [14,16],
        [16,17],
        [15,18],
        [10,19]
      ],
      "path": [1,2,4,8,13]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":10,"tw":7.902,"f":-0.000,"isPath":true},
        {"id":3,"orig":11,"tw":8.402,"f":-0.000,"isPath":false},
        {"id":4,"orig":12,"tw":8.015,"f":-0.000,"isPath":true},
        {"id":5,"orig":13,"tw":9.402,"f":0.402,"isPath":false},
        {"id":6,"orig":14,"tw":8.688,"f":0.117,"isPath":false},
        {"id":7,"orig":15,"tw":9.402,"f":-0.000,"isPath":false},
        {"id":8,"orig":16,"tw":8.402,"f":-0.000,"isPath":true},
        {"id":9,"orig":17,"tw":10.402,"f":2.804,"isPath":false},
        {"id":10,"orig":18,"tw":10.188,"f":1.617,"isPath":false},
        {"id":11,"orig":19,"tw":9.015,"f":0.015,"isPath":false},
        {"id":12,"orig":20,"tw":8.800,"f":0.229,"isPath":true},
        {"id":13,"orig":21,"tw":9.402,"f":0.417,"isPath":false},
        {"id":14,"orig":22,"tw":9.800,"f":1.244,"isPath":false},
        {"id":15,"orig":23,"tw":9.688,"f":0.804,"isPath":false},
        {"id":16,"orig":24,"tw":9.688,"f":0.117,"isPath":false},
        {"id":17,"orig":25,"tw":10.688,"f":3.492,"isPath":false},
        {"id":18,"orig":28,"tw":10.188,"f":2.019,"isPath":false},
        {"id":19,"orig":29,"tw":10.402,"f":0.402,"isPath":false},
        {"id":20,"orig":31,"tw":10.188,"f":2.034,"isPath":false},
        {"id":21,"orig":33,"tw":11.688,"f":3.492,"isPath":false},
        {"id":22,"orig":38,"tw":24.013,"f":1.044,"isPath":true},
        {"id":23,"orig":42,"tw":12.188,"f":5.207,"isPath":false},
        {"id":24,"orig":43,"tw":11.188,"f":5.421,"isPath":false},
        {"id":25,"orig":44,"tw":11.402,"f":5.421,"isPath":false},
        {"id":26,"orig":45,"tw":11.188,"f":5.207,"isPath":false},
        {"id":27,"orig":50,"tw":24.013,"f":3.044,"isPath":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [3,5],
        [3,6],
        [3,7],
        [4,8],
        [7,9],
        [7,10],
        [8,11],
        [8,12],
        [11,13],
        [11,14],
        [6,15],
        [6,16],
        [16,17],
        [5,18],
        [5,19],
        [13,20],
        [15,21],
        [12,22],
        [18,23],
        [9,24],
        [19,25],
        [10,26],
        [14,27]
      ],
      "path": [1,2,4,8,12,22]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":8,"tw":8.170,"f":0.000,"isPath":true},
        {"id":3,"orig":9,"tw":8.559,"f":0.000,"isPath":true},
        {"id":4,"orig":10,"tw":8.956,"f":0.000,"isPath":false},
        {"id":5,"orig":14,"tw":10.526,"f":1.555,"isPath":false},
        {"id":6,"orig":17,"tw":23.496,"f":0.761,"isPath":true}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [4,5],
        [3,6]
      ],
      "path": [1,2,3,6]
    }
  }
};
