// Decision-tree data — group=8r  scene=S1
// Auto-generated by export_tree_json.m — do not edit manually.
window.ALL_TREE_DATA = window.ALL_TREE_DATA || {};
window.ALL_TREE_DATA["8r_S1"] = {
  "group": "8r", "scene": "S1",
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":16,"tw":22.111,"f":-0.000,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":14,"tw":23.339,"f":0.088,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":3,"tw":2.785,"f":0.000,"isPath":true},
        {"id":3,"orig":4,"tw":3.571,"f":0.000,"isPath":true},
        {"id":4,"orig":5,"tw":3.571,"f":0.000,"isPath":false},
        {"id":5,"orig":22,"tw":27.249,"f":0.781,"isPath":true},
        {"id":6,"orig":31,"tw":27.249,"f":0.781,"isPath":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [3,5],
        [4,6]
      ],
      "path": [1,2,3,5]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":11,"tw":22.111,"f":-0.000,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    }
  }
};
