// Interactive decision-tree data — tr_15r_S2
// Auto-generated by export_interactive_tree.m
window.ALL_INTERACTIVE_TREES = window.ALL_INTERACTIVE_TREES || {};
window.ALL_INTERACTIVE_TREES["tr_15r_S2"] = {
  "numInt": 5,
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":3,"tw":15.250,"f":0.00,"isLeaf":false,"isRoot":false},
        {"id":3,"orig":5,"tw":16.250,"f":0.00,"isLeaf":false,"isRoot":false},
        {"id":4,"orig":32,"tw":46.361,"f":1.00,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [3,4]
      ],
      "optimalPath": [1,2,3,4],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2,3,4]
      ],
      "leafGantts": [
        {
          "fCost": 1.00,
          "vehicles": [
            {"veh":3,"k":2,"t0":21.6062,"tf":23.9624,"genTime":21.6062,"actualGenTime":21.6062,"spaces":[1.0000,5.0000,3.0000],"segStart":[21.6062,22.3916,23.1770],"segEnd":[22.3916,23.1770,23.9624]},
            {"veh":7,"k":1,"t0":15.2500,"tf":17.2500,"genTime":14.2500,"actualGenTime":14.2500,"spaces":[3.0000,4.0000],"segStart":[15.2500,16.2500],"segEnd":[16.2500,17.2500]},
            {"veh":8,"k":1,"t0":16.2500,"tf":18.6062,"genTime":16.2500,"actualGenTime":16.2500,"spaces":[3.0000,5.0000,1.0000],"segStart":[16.2500,17.0354,17.8208],"segEnd":[17.0354,17.8208,18.6062]},
            {"veh":9,"k":1,"t0":15.2500,"tf":17.2500,"genTime":15.2500,"actualGenTime":15.2500,"spaces":[4.0000,1.0000],"segStart":[15.2500,16.2500],"segEnd":[16.2500,17.2500]},
            {"veh":12,"k":2,"t0":23.2500,"tf":25.6062,"genTime":23.2500,"actualGenTime":23.2500,"spaces":[1.0000,5.0000,3.0000],"segStart":[23.2500,24.0354,24.8208],"segEnd":[24.0354,24.8208,25.6062]},
            {"veh":15,"k":3,"t0":30.2499,"tf":31.0353,"genTime":30.2500,"actualGenTime":30.2500,"spaces":[2.0000],"segStart":[30.2499],"segEnd":[31.0353]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":31,"tw":41.361,"f":-0.00,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": -0.00,
          "vehicles": [
            {"veh":4,"k":1,"t0":13.2500,"tf":15.2500,"genTime":13.2500,"actualGenTime":13.2500,"spaces":[3.0000,4.0000],"segStart":[13.2500,14.2500],"segEnd":[14.2500,15.2500]},
            {"veh":5,"k":1,"t0":15.2500,"tf":17.6062,"genTime":15.2500,"actualGenTime":15.2500,"spaces":[3.0000,5.0000,1.0000],"segStart":[15.2500,16.0354,16.8208],"segEnd":[16.0354,16.8208,17.6062]},
            {"veh":6,"k":1,"t0":17.2500,"tf":19.6062,"genTime":17.2500,"actualGenTime":17.2500,"spaces":[3.0000,5.0000,1.0000],"segStart":[17.2500,18.0354,18.8208],"segEnd":[18.0354,18.8208,19.6062]},
            {"veh":8,"k":2,"t0":21.6063,"tf":23.9625,"genTime":21.6063,"actualGenTime":21.6063,"spaces":[4.0000,5.0000,2.0000],"segStart":[21.6063,22.3917,23.1771],"segEnd":[22.3917,23.1771,23.9625]},
            {"veh":9,"k":2,"t0":20.2503,"tf":22.6065,"genTime":20.2501,"actualGenTime":20.2501,"spaces":[4.0000,5.0000,2.0000],"segStart":[20.2503,21.0357,21.8211],"segEnd":[21.0357,21.8211,22.6065]},
            {"veh":11,"k":2,"t0":21.0351,"tf":21.8205,"genTime":21.0351,"actualGenTime":21.0352,"spaces":[2.0000],"segStart":[21.0351],"segEnd":[21.8205]},
            {"veh":15,"k":2,"t0":25.2499,"tf":27.2499,"genTime":25.2500,"actualGenTime":25.2500,"spaces":[2.0000,3.0000],"segStart":[25.2499,26.2499],"segEnd":[26.2499,27.2499]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":33,"tw":42.361,"f":0.07,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 0.07,
          "vehicles": [
            {"veh":1,"k":1,"t0":12.2500,"tf":13.0354,"genTime":12.2500,"actualGenTime":12.2500,"spaces":[4.0000],"segStart":[12.2500],"segEnd":[13.0354]},
            {"veh":2,"k":1,"t0":14.2500,"tf":16.2500,"genTime":14.2500,"actualGenTime":14.2500,"spaces":[4.0000,1.0000],"segStart":[14.2500,15.2500],"segEnd":[15.2500,16.2500]},
            {"veh":3,"k":1,"t0":16.2500,"tf":18.6062,"genTime":16.2500,"actualGenTime":16.2500,"spaces":[4.0000,5.0000,2.0000],"segStart":[16.2500,17.0354,17.8208],"segEnd":[17.0354,17.8208,18.6062]},
            {"veh":7,"k":2,"t0":20.3224,"tf":21.1078,"genTime":20.2825,"actualGenTime":20.2980,"spaces":[3.0000],"segStart":[20.3224],"segEnd":[21.1078]},
            {"veh":10,"k":2,"t0":21.6062,"tf":23.6062,"genTime":21.6062,"actualGenTime":21.6062,"spaces":[2.0000,3.0000],"segStart":[21.6062,22.6062],"segEnd":[22.6062,23.6062]},
            {"veh":12,"k":1,"t0":18.2500,"tf":20.2500,"genTime":18.2500,"actualGenTime":18.2500,"spaces":[1.0000,2.0000],"segStart":[18.2500,19.2500],"segEnd":[19.2500,20.2500]},
            {"veh":13,"k":2,"t0":24.2500,"tf":26.6062,"genTime":24.2500,"actualGenTime":24.2500,"spaces":[2.0000,5.0000,4.0000],"segStart":[24.2500,25.0354,25.8208],"segEnd":[25.0354,25.8208,26.6062]},
            {"veh":14,"k":2,"t0":26.2500,"tf":28.6062,"genTime":26.2500,"actualGenTime":26.2500,"spaces":[2.0000,5.0000,4.0000],"segStart":[26.2500,27.0354,27.8208],"segEnd":[27.0354,27.8208,28.6062]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":9,"tw":19.668,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":3,"orig":10,"tw":20.077,"f":0.04,"isLeaf":false,"isRoot":false},
        {"id":4,"orig":11,"tw":20.250,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":5,"orig":12,"tw":21.035,"f":1.00,"isLeaf":false,"isRoot":false},
        {"id":6,"orig":13,"tw":20.668,"f":0.42,"isLeaf":false,"isRoot":false},
        {"id":7,"orig":25,"tw":37.361,"f":0.87,"isLeaf":true,"isRoot":false},
        {"id":8,"orig":26,"tw":21.250,"f":1.00,"isLeaf":false,"isRoot":false},
        {"id":9,"orig":27,"tw":21.250,"f":1.00,"isLeaf":false,"isRoot":false},
        {"id":10,"orig":28,"tw":22.035,"f":1.00,"isLeaf":false,"isRoot":false},
        {"id":11,"orig":29,"tw":22.250,"f":2.00,"isLeaf":false,"isRoot":false},
        {"id":12,"orig":31,"tw":23.035,"f":3.79,"isLeaf":false,"isRoot":false},
        {"id":13,"orig":32,"tw":22.250,"f":1.00,"isLeaf":false,"isRoot":false},
        {"id":14,"orig":33,"tw":23.250,"f":4.00,"isLeaf":true,"isRoot":false},
        {"id":15,"orig":41,"tw":37.361,"f":1.84,"isLeaf":true,"isRoot":false},
        {"id":16,"orig":42,"tw":23.250,"f":2.00,"isLeaf":false,"isRoot":false},
        {"id":17,"orig":43,"tw":23.250,"f":2.00,"isLeaf":false,"isRoot":false},
        {"id":18,"orig":44,"tw":24.250,"f":7.00,"isLeaf":true,"isRoot":false},
        {"id":19,"orig":46,"tw":25.250,"f":7.00,"isLeaf":true,"isRoot":false},
        {"id":20,"orig":50,"tw":25.035,"f":8.36,"isLeaf":true,"isRoot":false},
        {"id":21,"orig":55,"tw":37.361,"f":6.79,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [4,5],
        [4,6],
        [3,7],
        [5,8],
        [5,9],
        [8,10],
        [8,11],
        [10,12],
        [10,13],
        [9,14],
        [6,15],
        [11,16],
        [11,17],
        [16,18],
        [17,19],
        [12,20],
        [13,21]
      ],
      "optimalPath": [1,2,3,7],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2,3,7],
        [1,2,4,5,9,14],
        [1,2,4,6,15],
        [1,2,4,5,8,11,16,18],
        [1,2,4,5,8,11,17,19],
        [1,2,4,5,8,10,12,20],
        [1,2,4,5,8,10,13,21]
      ],
      "leafGantts": [
        {
          "fCost": 0.87,
          "vehicles": [
            {"veh":2,"k":2,"t0":19.2914,"tf":20.0768,"genTime":19.2852,"actualGenTime":19.2969,"spaces":[4.0000],"segStart":[19.2914],"segEnd":[20.0768]},
            {"veh":4,"k":2,"t0":19.0768,"tf":21.0768,"genTime":18.2500,"actualGenTime":18.6720,"spaces":[3.0000,4.0000],"segStart":[19.0768,20.0768],"segEnd":[20.0768,21.0768]},
            {"veh":10,"k":1,"t0":16.2500,"tf":18.6062,"genTime":16.2500,"actualGenTime":16.2500,"spaces":[1.0000,5.0000,3.0000],"segStart":[16.2500,17.0354,17.8208],"segEnd":[17.0354,17.8208,18.6062]},
            {"veh":13,"k":1,"t0":19.2500,"tf":21.2500,"genTime":19.2500,"actualGenTime":19.2500,"spaces":[2.0000,3.0000],"segStart":[19.2500,20.2500],"segEnd":[20.2500,21.2500]},
            {"veh":14,"k":1,"t0":21.2500,"tf":23.2500,"genTime":21.2500,"actualGenTime":21.2500,"spaces":[2.0000,3.0000],"segStart":[21.2500,22.2500],"segEnd":[22.2500,23.2500]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 4.00,
          "vehicles": [
            {"veh":2,"k":2,"t0":20.2500,"tf":21.0354,"genTime":19.2852,"actualGenTime":19.2969,"spaces":[4.0000],"segStart":[20.2500],"segEnd":[21.0354]},
            {"veh":4,"k":2,"t0":21.2500,"tf":23.2500,"genTime":18.2500,"actualGenTime":18.6720,"spaces":[3.0000,4.0000],"segStart":[21.2500,22.2500],"segEnd":[22.2500,23.2500]},
            {"veh":10,"k":1,"t0":16.2500,"tf":18.6062,"genTime":16.2500,"actualGenTime":16.2500,"spaces":[1.0000,5.0000,3.0000],"segStart":[16.2500,17.0354,17.8208],"segEnd":[17.0354,17.8208,18.6062]},
            {"veh":13,"k":1,"t0":19.2500,"tf":21.2500,"genTime":19.2500,"actualGenTime":19.2500,"spaces":[2.0000,3.0000],"segStart":[19.2500,20.2500],"segEnd":[20.2500,21.2500]},
            {"veh":14,"k":1,"t0":21.2500,"tf":23.2500,"genTime":21.2500,"actualGenTime":21.2500,"spaces":[2.0000,3.0000],"segStart":[21.2500,22.2500],"segEnd":[22.2500,23.2500]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 1.84,
          "vehicles": [
            {"veh":2,"k":2,"t0":20.6685,"tf":21.4539,"genTime":19.2852,"actualGenTime":19.2969,"spaces":[4.0000],"segStart":[20.6685],"segEnd":[21.4539]},
            {"veh":4,"k":2,"t0":18.6685,"tf":20.6685,"genTime":18.2500,"actualGenTime":18.6720,"spaces":[3.0000,4.0000],"segStart":[18.6685,19.6685],"segEnd":[19.6685,20.6685]},
            {"veh":10,"k":1,"t0":16.2500,"tf":18.6062,"genTime":16.2500,"actualGenTime":16.2500,"spaces":[1.0000,5.0000,3.0000],"segStart":[16.2500,17.0354,17.8208],"segEnd":[17.0354,17.8208,18.6062]},
            {"veh":13,"k":1,"t0":19.2500,"tf":21.2500,"genTime":19.2500,"actualGenTime":19.2500,"spaces":[2.0000,3.0000],"segStart":[19.2500,20.2500],"segEnd":[20.2500,21.2500]},
            {"veh":14,"k":1,"t0":21.2500,"tf":23.2500,"genTime":21.2500,"actualGenTime":21.2500,"spaces":[2.0000,3.0000],"segStart":[21.2500,22.2500],"segEnd":[22.2500,23.2500]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 7.00,
          "vehicles": [
            {"veh":2,"k":2,"t0":20.2500,"tf":21.0354,"genTime":19.2852,"actualGenTime":19.2969,"spaces":[4.0000],"segStart":[20.2500],"segEnd":[21.0354]},
            {"veh":4,"k":2,"t0":22.2500,"tf":24.2500,"genTime":18.2500,"actualGenTime":18.6720,"spaces":[3.0000,4.0000],"segStart":[22.2500,23.2500],"segEnd":[23.2500,24.2500]},
            {"veh":10,"k":1,"t0":16.2500,"tf":18.6062,"genTime":16.2500,"actualGenTime":16.2500,"spaces":[1.0000,5.0000,3.0000],"segStart":[16.2500,17.0354,17.8208],"segEnd":[17.0354,17.8208,18.6062]},
            {"veh":13,"k":1,"t0":20.2500,"tf":22.2500,"genTime":19.2500,"actualGenTime":19.2500,"spaces":[2.0000,3.0000],"segStart":[20.2500,21.2500],"segEnd":[21.2500,22.2500]},
            {"veh":14,"k":1,"t0":22.2500,"tf":24.2500,"genTime":21.2500,"actualGenTime":21.2500,"spaces":[2.0000,3.0000],"segStart":[22.2500,23.2500],"segEnd":[23.2500,24.2500]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 7.00,
          "vehicles": [
            {"veh":2,"k":2,"t0":20.2500,"tf":21.0354,"genTime":19.2852,"actualGenTime":19.2969,"spaces":[4.0000],"segStart":[20.2500],"segEnd":[21.0354]},
            {"veh":4,"k":2,"t0":23.2500,"tf":25.2500,"genTime":18.2500,"actualGenTime":18.6720,"spaces":[3.0000,4.0000],"segStart":[23.2500,24.2500],"segEnd":[24.2500,25.2500]},
            {"veh":10,"k":1,"t0":16.2500,"tf":18.6062,"genTime":16.2500,"actualGenTime":16.2500,"spaces":[1.0000,5.0000,3.0000],"segStart":[16.2500,17.0354,17.8208],"segEnd":[17.0354,17.8208,18.6062]},
            {"veh":13,"k":1,"t0":20.2500,"tf":22.2500,"genTime":19.2500,"actualGenTime":19.2500,"spaces":[2.0000,3.0000],"segStart":[20.2500,21.2500],"segEnd":[21.2500,22.2500]},
            {"veh":14,"k":1,"t0":21.2500,"tf":23.2500,"genTime":21.2500,"actualGenTime":21.2500,"spaces":[2.0000,3.0000],"segStart":[21.2500,22.2500],"segEnd":[22.2500,23.2500]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 8.36,
          "vehicles": [
            {"veh":2,"k":2,"t0":20.2500,"tf":21.0354,"genTime":19.2852,"actualGenTime":19.2969,"spaces":[4.0000],"segStart":[20.2500],"segEnd":[21.0354]},
            {"veh":4,"k":2,"t0":21.0354,"tf":23.0354,"genTime":18.2500,"actualGenTime":18.6720,"spaces":[3.0000,4.0000],"segStart":[21.0354,22.0354],"segEnd":[22.0354,23.0354]},
            {"veh":10,"k":1,"t0":16.2500,"tf":18.6062,"genTime":16.2500,"actualGenTime":16.2500,"spaces":[1.0000,5.0000,3.0000],"segStart":[16.2500,17.0354,17.8208],"segEnd":[17.0354,17.8208,18.6062]},
            {"veh":13,"k":1,"t0":22.0354,"tf":24.0354,"genTime":19.2500,"actualGenTime":19.2500,"spaces":[2.0000,3.0000],"segStart":[22.0354,23.0354],"segEnd":[23.0354,24.0354]},
            {"veh":14,"k":1,"t0":23.0354,"tf":25.0354,"genTime":21.2500,"actualGenTime":21.2500,"spaces":[2.0000,3.0000],"segStart":[23.0354,24.0354],"segEnd":[24.0354,25.0354]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 6.79,
          "vehicles": [
            {"veh":2,"k":2,"t0":20.2500,"tf":21.0354,"genTime":19.2852,"actualGenTime":19.2969,"spaces":[4.0000],"segStart":[20.2500],"segEnd":[21.0354]},
            {"veh":4,"k":2,"t0":21.0354,"tf":23.0354,"genTime":18.2500,"actualGenTime":18.6720,"spaces":[3.0000,4.0000],"segStart":[21.0354,22.0354],"segEnd":[22.0354,23.0354]},
            {"veh":10,"k":1,"t0":16.2500,"tf":18.6062,"genTime":16.2500,"actualGenTime":16.2500,"spaces":[1.0000,5.0000,3.0000],"segStart":[16.2500,17.0354,17.8208],"segEnd":[17.0354,17.8208,18.6062]},
            {"veh":13,"k":1,"t0":22.2500,"tf":24.2500,"genTime":19.2500,"actualGenTime":19.2500,"spaces":[2.0000,3.0000],"segStart":[22.2500,23.2500],"segEnd":[23.2500,24.2500]},
            {"veh":14,"k":1,"t0":21.2500,"tf":23.2500,"genTime":21.2500,"actualGenTime":21.2500,"spaces":[2.0000,3.0000],"segStart":[21.2500,22.2500],"segEnd":[22.2500,23.2500]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "5": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":16,"tw":38.717,"f":-0.00,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": -0.00,
          "vehicles": [
            {"veh":5,"k":2,"t0":20.6062,"tf":22.6062,"genTime":20.6062,"actualGenTime":20.6062,"spaces":[4.0000,1.0000],"segStart":[20.6062,21.6062],"segEnd":[21.6062,22.6062]},
            {"veh":6,"k":2,"t0":22.6062,"tf":24.9624,"genTime":22.6062,"actualGenTime":22.6062,"spaces":[4.0000,5.0000,2.0000],"segStart":[22.6062,23.3916,24.1770],"segEnd":[23.3916,24.1770,24.9624]},
            {"veh":11,"k":1,"t0":17.2500,"tf":18.0354,"genTime":17.2500,"actualGenTime":17.2500,"spaces":[3.0000],"segStart":[17.2500],"segEnd":[18.0354]},
            {"veh":15,"k":1,"t0":20.2500,"tf":22.2500,"genTime":20.2500,"actualGenTime":20.2500,"spaces":[2.0000,3.0000],"segStart":[20.2500,21.2500],"segEnd":[21.2500,22.2500]}
          ],
          "numSpaces": 5
        }
      ]
    }
  }
};
