// Interactive decision-tree data — 15r_S2
// Auto-generated by export_interactive_tree.m
window.ALL_INTERACTIVE_TREES = window.ALL_INTERACTIVE_TREES || {};
window.ALL_INTERACTIVE_TREES["15r_S2"] = {
  "numInt": 4,
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":26,"tw":36.111,"f":0.00,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 0.00,
          "vehicles": [
            {"veh":4,"k":1,"t0":6.0000,"tf":6.7854,"genTime":6.0000,"actualGenTime":6.0000,"spaces":[1.0000],"segStart":[6.0000],"segEnd":[6.7854]},
            {"veh":5,"k":1,"t0":10.0000,"tf":12.0000,"genTime":10.0000,"actualGenTime":10.0000,"spaces":[1.0000,2.0000],"segStart":[10.0000,11.0000],"segEnd":[11.0000,12.0000]},
            {"veh":7,"k":2,"t0":16.0000,"tf":18.0000,"genTime":15.9992,"actualGenTime":15.9996,"spaces":[3.0000,4.0000],"segStart":[16.0000,17.0000],"segEnd":[17.0000,18.0000]},
            {"veh":8,"k":2,"t0":12.7854,"tf":14.7854,"genTime":12.7846,"actualGenTime":12.7850,"spaces":[3.0000,4.0000],"segStart":[12.7854,13.7854],"segEnd":[13.7854,14.7854]},
            {"veh":11,"k":2,"t0":20.0000,"tf":22.3562,"genTime":19.9990,"actualGenTime":19.9995,"spaces":[2.0000,5.0000,4.0000],"segStart":[20.0000,20.7854,21.5708],"segEnd":[20.7854,21.5708,22.3562]},
            {"veh":14,"k":1,"t0":16.0000,"tf":18.3562,"genTime":16.0000,"actualGenTime":16.0000,"spaces":[4.0000,5.0000,2.0000],"segStart":[16.0000,16.7854,17.5708],"segEnd":[16.7854,17.5708,18.3562]},
            {"veh":15,"k":1,"t0":20.0000,"tf":22.0000,"genTime":20.0000,"actualGenTime":20.0000,"spaces":[4.0000,1.0000],"segStart":[20.0000,21.0000],"segEnd":[21.0000,22.0000]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":29,"tw":40.111,"f":0.00,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 0.00,
          "vehicles": [
            {"veh":1,"k":1,"t0":2.0000,"tf":2.7854,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[1.0000],"segStart":[2.0000],"segEnd":[2.7854]},
            {"veh":2,"k":1,"t0":6.0000,"tf":8.0000,"genTime":6.0000,"actualGenTime":6.0000,"spaces":[1.0000,2.0000],"segStart":[6.0000,7.0000],"segEnd":[7.0000,8.0000]},
            {"veh":4,"k":2,"t0":8.7854,"tf":9.5708,"genTime":8.7844,"actualGenTime":8.7849,"spaces":[4.0000],"segStart":[8.7854],"segEnd":[9.5708]},
            {"veh":10,"k":1,"t0":12.0000,"tf":12.7854,"genTime":12.0000,"actualGenTime":12.0000,"spaces":[2.0000],"segStart":[12.0000],"segEnd":[12.7854]},
            {"veh":11,"k":1,"t0":16.0000,"tf":18.0000,"genTime":16.0000,"actualGenTime":16.0000,"spaces":[2.0000,3.0000],"segStart":[16.0000,17.0000],"segEnd":[17.0000,18.0000]},
            {"veh":12,"k":2,"t0":18.0000,"tf":20.0000,"genTime":17.9989,"actualGenTime":17.9996,"spaces":[3.0000,4.0000],"segStart":[18.0000,19.0000],"segEnd":[19.0000,20.0000]},
            {"veh":13,"k":2,"t0":22.0000,"tf":24.0000,"genTime":21.9989,"actualGenTime":21.9993,"spaces":[3.0000,4.0000],"segStart":[22.0000,23.0000],"segEnd":[23.0000,24.0000]},
            {"veh":15,"k":2,"t0":24.0000,"tf":26.3562,"genTime":23.9990,"actualGenTime":23.9997,"spaces":[4.0000,5.0000,2.0000],"segStart":[24.0000,24.7854,25.5708],"segEnd":[24.7854,25.5708,26.3562]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":29,"tw":44.467,"f":0.00,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 0.00,
          "vehicles": [
            {"veh":2,"k":2,"t0":10.0000,"tf":12.0000,"genTime":9.9989,"actualGenTime":9.9995,"spaces":[1.0000,2.0000],"segStart":[10.0000,11.0000],"segEnd":[11.0000,12.0000]},
            {"veh":3,"k":1,"t0":4.0000,"tf":6.0000,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[2.0000,3.0000],"segStart":[4.0000,5.0000],"segEnd":[5.0000,6.0000]},
            {"veh":6,"k":2,"t0":12.3562,"tf":14.7124,"genTime":12.3554,"actualGenTime":12.3558,"spaces":[4.0000,5.0000,2.0000],"segStart":[12.3562,13.1416,13.9270],"segEnd":[13.1416,13.9270,14.7124]},
            {"veh":9,"k":2,"t0":18.0000,"tf":20.0000,"genTime":17.9992,"actualGenTime":17.9991,"spaces":[4.0000,1.0000],"segStart":[18.0000,19.0000],"segEnd":[19.0000,20.0000]},
            {"veh":10,"k":2,"t0":14.7854,"tf":15.5708,"genTime":14.7843,"actualGenTime":14.7848,"spaces":[1.0000],"segStart":[14.7854],"segEnd":[15.5708]},
            {"veh":12,"k":1,"t0":14.0000,"tf":16.0000,"genTime":14.0000,"actualGenTime":14.0000,"spaces":[3.0000,4.0000],"segStart":[14.0000,15.0000],"segEnd":[15.0000,16.0000]},
            {"veh":13,"k":1,"t0":18.0000,"tf":20.0000,"genTime":18.0000,"actualGenTime":18.0000,"spaces":[3.0000,4.0000],"segStart":[18.0000,19.0000],"segEnd":[19.0000,20.0000]},
            {"veh":15,"k":3,"t0":28.3562,"tf":30.3562,"genTime":28.3551,"actualGenTime":28.3556,"spaces":[1.0000,2.0000],"segStart":[28.3562,29.3562],"segEnd":[29.3562,30.3562]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":22,"tw":36.467,"f":0.00,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": 0.00,
          "vehicles": [
            {"veh":3,"k":2,"t0":8.0000,"tf":10.0000,"genTime":7.9992,"actualGenTime":7.9996,"spaces":[2.0000,3.0000],"segStart":[8.0000,9.0000],"segEnd":[9.0000,10.0000]},
            {"veh":5,"k":2,"t0":14.0000,"tf":16.0000,"genTime":13.9992,"actualGenTime":13.9992,"spaces":[1.0000,2.0000],"segStart":[14.0000,15.0000],"segEnd":[15.0000,16.0000]},
            {"veh":6,"k":1,"t0":8.0000,"tf":10.3562,"genTime":8.0000,"actualGenTime":8.0000,"spaces":[3.0000,5.0000,1.0000],"segStart":[8.0000,8.7854,9.5708],"segEnd":[8.7854,9.5708,10.3562]},
            {"veh":7,"k":1,"t0":12.0000,"tf":14.0000,"genTime":12.0000,"actualGenTime":12.0000,"spaces":[3.0000,4.0000],"segStart":[12.0000,13.0000],"segEnd":[13.0000,14.0000]},
            {"veh":8,"k":1,"t0":10.0000,"tf":10.7854,"genTime":10.0000,"actualGenTime":10.0000,"spaces":[4.0000],"segStart":[10.0000],"segEnd":[10.7854]},
            {"veh":9,"k":1,"t0":14.0000,"tf":16.0000,"genTime":14.0000,"actualGenTime":14.0000,"spaces":[4.0000,1.0000],"segStart":[14.0000,15.0000],"segEnd":[15.0000,16.0000]},
            {"veh":14,"k":2,"t0":20.3562,"tf":22.7124,"genTime":20.3554,"actualGenTime":20.3558,"spaces":[1.0000,5.0000,3.0000],"segStart":[20.3562,21.1416,21.9270],"segEnd":[21.1416,21.9270,22.7124]}
          ],
          "numSpaces": 5
        }
      ]
    }
  }
};
