// Interactive decision-tree data — 15r_S1
// Auto-generated by export_interactive_tree.m
window.ALL_INTERACTIVE_TREES = window.ALL_INTERACTIVE_TREES || {};
window.ALL_INTERACTIVE_TREES["15r_S1"] = {
  "numInt": 4,
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":27,"tw":27.382,"f":-0.01,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": -0.01,
          "vehicles": [
            {"veh":4,"k":3,"t0":11.2712,"tf":12.0566,"genTime":11.2854,"actualGenTime":11.2830,"spaces":[3.0000],"segStart":[11.2712],"segEnd":[12.0566]},
            {"veh":5,"k":1,"t0":2.0000,"tf":2.7854,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[1.0000],"segStart":[2.0000],"segEnd":[2.7854]},
            {"veh":6,"k":2,"t0":5.9998,"tf":6.7852,"genTime":5.9999,"actualGenTime":5.9998,"spaces":[3.0000],"segStart":[5.9998],"segEnd":[6.7852]},
            {"veh":7,"k":2,"t0":8.0000,"tf":10.0000,"genTime":7.9999,"actualGenTime":8.0000,"spaces":[3.0000,4.0000],"segStart":[8.0000,9.0000],"segEnd":[9.0000,10.0000]},
            {"veh":9,"k":2,"t0":8.3562,"tf":10.3562,"genTime":8.3561,"actualGenTime":8.3562,"spaces":[2.0000,3.0000],"segStart":[8.3562,9.3562],"segEnd":[9.3562,10.3562]},
            {"veh":12,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[4.0000,1.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":13,"k":1,"t0":4.0000,"tf":6.0000,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[4.0000,1.0000],"segStart":[4.0000,5.0000],"segEnd":[5.0000,6.0000]},
            {"veh":15,"k":2,"t0":6.7856,"tf":8.7856,"genTime":6.7855,"actualGenTime":6.7856,"spaces":[3.0000,4.0000],"segStart":[6.7856,7.7856],"segEnd":[7.7856,8.7856]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":22,"tw":24.111,"f":-0.00,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2]
      ],
      "optimalPath": [1,2],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2]
      ],
      "leafGantts": [
        {
          "fCost": -0.00,
          "vehicles": [
            {"veh":1,"k":1,"t0":2.0000,"tf":4.3562,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[2.0000,5.0000,4.0000],"segStart":[2.0000,2.7854,3.5708],"segEnd":[2.7854,3.5708,4.3562]},
            {"veh":2,"k":1,"t0":4.0000,"tf":4.7854,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[2.0000],"segStart":[4.0000],"segEnd":[4.7854]},
            {"veh":5,"k":2,"t0":4.7854,"tf":6.7854,"genTime":4.7853,"actualGenTime":4.7854,"spaces":[4.0000,1.0000],"segStart":[4.7854,5.7854],"segEnd":[5.7854,6.7854]},
            {"veh":8,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[1.0000,2.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":9,"k":1,"t0":4.0000,"tf":6.3562,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[1.0000,5.0000,3.0000],"segStart":[4.0000,4.7854,5.5708],"segEnd":[4.7854,5.5708,6.3562]},
            {"veh":12,"k":2,"t0":6.0000,"tf":6.7854,"genTime":5.9999,"actualGenTime":6.0000,"spaces":[4.0000],"segStart":[6.0000],"segEnd":[6.7854]},
            {"veh":13,"k":2,"t0":8.0000,"tf":10.0000,"genTime":7.9999,"actualGenTime":8.0000,"spaces":[4.0000,1.0000],"segStart":[8.0000,9.0000],"segEnd":[9.0000,10.0000]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":14,"tw":7.801,"f":0.00,"isLeaf":false,"isRoot":false},
        {"id":3,"orig":15,"tw":8.024,"f":0.02,"isLeaf":false,"isRoot":false},
        {"id":4,"orig":16,"tw":8.301,"f":0.00,"isLeaf":false,"isRoot":false},
        {"id":5,"orig":17,"tw":9.301,"f":0.52,"isLeaf":false,"isRoot":false},
        {"id":6,"orig":18,"tw":8.587,"f":0.23,"isLeaf":false,"isRoot":false},
        {"id":7,"orig":19,"tw":8.301,"f":0.02,"isLeaf":false,"isRoot":false},
        {"id":8,"orig":20,"tw":9.301,"f":0.54,"isLeaf":false,"isRoot":false},
        {"id":9,"orig":21,"tw":8.810,"f":0.48,"isLeaf":false,"isRoot":false},
        {"id":10,"orig":22,"tw":9.587,"f":0.23,"isLeaf":false,"isRoot":false},
        {"id":11,"orig":23,"tw":9.301,"f":0.23,"isLeaf":false,"isRoot":false},
        {"id":12,"orig":27,"tw":10.301,"f":2.82,"isLeaf":false,"isRoot":false},
        {"id":13,"orig":28,"tw":10.087,"f":2.25,"isLeaf":false,"isRoot":false},
        {"id":14,"orig":34,"tw":23.412,"f":1.50,"isLeaf":true,"isRoot":false},
        {"id":15,"orig":41,"tw":23.412,"f":2.27,"isLeaf":true,"isRoot":false},
        {"id":16,"orig":48,"tw":23.412,"f":5.05,"isLeaf":true,"isRoot":false},
        {"id":17,"orig":53,"tw":23.412,"f":5.33,"isLeaf":true,"isRoot":false},
        {"id":18,"orig":58,"tw":23.412,"f":5.55,"isLeaf":true,"isRoot":false},
        {"id":19,"orig":63,"tw":23.412,"f":5.62,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [4,5],
        [4,6],
        [3,7],
        [7,8],
        [7,9],
        [6,10],
        [6,11],
        [5,12],
        [5,13],
        [9,14],
        [8,15],
        [11,16],
        [13,17],
        [12,18],
        [10,19]
      ],
      "optimalPath": [1,2,3,7,9,14],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2,3,7,9,14],
        [1,2,3,7,8,15],
        [1,2,4,6,11,16],
        [1,2,4,5,13,17],
        [1,2,4,5,12,18],
        [1,2,4,6,10,19]
      ],
      "leafGantts": [
        {
          "fCost": 1.50,
          "vehicles": [
            {"veh":2,"k":2,"t0":7.8096,"tf":9.8096,"genTime":6.7855,"actualGenTime":7.2982,"spaces":[1.0000,2.0000],"segStart":[7.8096,8.8096],"segEnd":[8.8096,9.8096]},
            {"veh":3,"k":1,"t0":2.0000,"tf":2.7854,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000],"segStart":[2.0000],"segEnd":[2.7854]},
            {"veh":4,"k":1,"t0":4.0000,"tf":4.7854,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[3.0000],"segStart":[4.0000],"segEnd":[4.7854]},
            {"veh":8,"k":2,"t0":6.0242,"tf":8.0242,"genTime":6.0134,"actualGenTime":6.0194,"spaces":[1.0000,2.0000],"segStart":[6.0242,7.0242],"segEnd":[7.0242,8.0242]},
            {"veh":10,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[2.0000,3.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":11,"k":1,"t0":4.0000,"tf":6.0000,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[2.0000,3.0000],"segStart":[4.0000,5.0000],"segEnd":[5.0000,6.0000]},
            {"veh":14,"k":2,"t0":6.4534,"tf":8.8096,"genTime":6.0000,"actualGenTime":6.2273,"spaces":[4.0000,5.0000,2.0000],"segStart":[6.4534,7.2388,8.0242],"segEnd":[7.2388,8.0242,8.8096]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 2.27,
          "vehicles": [
            {"veh":2,"k":2,"t0":7.3013,"tf":9.3013,"genTime":6.7855,"actualGenTime":7.2982,"spaces":[1.0000,2.0000],"segStart":[7.3013,8.3013],"segEnd":[8.3013,9.3013]},
            {"veh":3,"k":1,"t0":2.0000,"tf":2.7854,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000],"segStart":[2.0000],"segEnd":[2.7854]},
            {"veh":4,"k":1,"t0":4.0000,"tf":4.7854,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[3.0000],"segStart":[4.0000],"segEnd":[4.7854]},
            {"veh":8,"k":2,"t0":6.0242,"tf":8.0242,"genTime":6.0134,"actualGenTime":6.0194,"spaces":[1.0000,2.0000],"segStart":[6.0242,7.0242],"segEnd":[7.0242,8.0242]},
            {"veh":10,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[2.0000,3.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":11,"k":1,"t0":4.0000,"tf":6.0000,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[2.0000,3.0000],"segStart":[4.0000,5.0000],"segEnd":[5.0000,6.0000]},
            {"veh":14,"k":2,"t0":7.7305,"tf":10.0867,"genTime":6.0000,"actualGenTime":6.2273,"spaces":[4.0000,5.0000,2.0000],"segStart":[7.7305,8.5159,9.3013],"segEnd":[8.5159,9.3013,10.0867]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 5.05,
          "vehicles": [
            {"veh":2,"k":2,"t0":9.3013,"tf":11.3013,"genTime":6.7855,"actualGenTime":7.2982,"spaces":[1.0000,2.0000],"segStart":[9.3013,10.3013],"segEnd":[10.3013,11.3013]},
            {"veh":3,"k":1,"t0":2.0000,"tf":2.7854,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000],"segStart":[2.0000],"segEnd":[2.7854]},
            {"veh":4,"k":1,"t0":4.0000,"tf":4.7854,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[3.0000],"segStart":[4.0000],"segEnd":[4.7854]},
            {"veh":8,"k":2,"t0":8.3013,"tf":10.3013,"genTime":6.0134,"actualGenTime":6.0194,"spaces":[1.0000,2.0000],"segStart":[8.3013,9.3013],"segEnd":[9.3013,10.3013]},
            {"veh":10,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[2.0000,3.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":11,"k":1,"t0":4.0000,"tf":6.0000,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[2.0000,3.0000],"segStart":[4.0000,5.0000],"segEnd":[5.0000,6.0000]},
            {"veh":14,"k":2,"t0":6.2304,"tf":8.5866,"genTime":6.0000,"actualGenTime":6.2273,"spaces":[4.0000,5.0000,2.0000],"segStart":[6.2304,7.0158,7.8012],"segEnd":[7.0158,7.8012,8.5866]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 5.33,
          "vehicles": [
            {"veh":2,"k":2,"t0":7.3013,"tf":9.3013,"genTime":6.7855,"actualGenTime":7.2982,"spaces":[1.0000,2.0000],"segStart":[7.3013,8.3013],"segEnd":[8.3013,9.3013]},
            {"veh":3,"k":1,"t0":2.0000,"tf":2.7854,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000],"segStart":[2.0000],"segEnd":[2.7854]},
            {"veh":4,"k":1,"t0":4.0000,"tf":4.7854,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[3.0000],"segStart":[4.0000],"segEnd":[4.7854]},
            {"veh":8,"k":2,"t0":9.0867,"tf":11.0867,"genTime":6.0134,"actualGenTime":6.0194,"spaces":[1.0000,2.0000],"segStart":[9.0867,10.0867],"segEnd":[10.0867,11.0867]},
            {"veh":10,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[2.0000,3.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":11,"k":1,"t0":4.0000,"tf":6.0000,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[2.0000,3.0000],"segStart":[4.0000,5.0000],"segEnd":[5.0000,6.0000]},
            {"veh":14,"k":2,"t0":7.7305,"tf":10.0867,"genTime":6.0000,"actualGenTime":6.2273,"spaces":[4.0000,5.0000,2.0000],"segStart":[7.7305,8.5159,9.3013],"segEnd":[8.5159,9.3013,10.0867]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 5.55,
          "vehicles": [
            {"veh":2,"k":2,"t0":7.3013,"tf":9.3013,"genTime":6.7855,"actualGenTime":7.2982,"spaces":[1.0000,2.0000],"segStart":[7.3013,8.3013],"segEnd":[8.3013,9.3013]},
            {"veh":3,"k":1,"t0":2.0000,"tf":2.7854,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000],"segStart":[2.0000],"segEnd":[2.7854]},
            {"veh":4,"k":1,"t0":4.0000,"tf":4.7854,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[3.0000],"segStart":[4.0000],"segEnd":[4.7854]},
            {"veh":8,"k":2,"t0":8.3013,"tf":10.3013,"genTime":6.0134,"actualGenTime":6.0194,"spaces":[1.0000,2.0000],"segStart":[8.3013,9.3013],"segEnd":[9.3013,10.3013]},
            {"veh":10,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[2.0000,3.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":11,"k":1,"t0":4.0000,"tf":6.0000,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[2.0000,3.0000],"segStart":[4.0000,5.0000],"segEnd":[5.0000,6.0000]},
            {"veh":14,"k":2,"t0":8.7305,"tf":11.0867,"genTime":6.0000,"actualGenTime":6.2273,"spaces":[4.0000,5.0000,2.0000],"segStart":[8.7305,9.5159,10.3013],"segEnd":[9.5159,10.3013,11.0867]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 5.62,
          "vehicles": [
            {"veh":2,"k":2,"t0":8.5866,"tf":10.5866,"genTime":6.7855,"actualGenTime":7.2982,"spaces":[1.0000,2.0000],"segStart":[8.5866,9.5866],"segEnd":[9.5866,10.5866]},
            {"veh":3,"k":1,"t0":2.0000,"tf":2.7854,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000],"segStart":[2.0000],"segEnd":[2.7854]},
            {"veh":4,"k":1,"t0":4.0000,"tf":4.7854,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[3.0000],"segStart":[4.0000],"segEnd":[4.7854]},
            {"veh":8,"k":2,"t0":9.5866,"tf":11.5866,"genTime":6.0134,"actualGenTime":6.0194,"spaces":[1.0000,2.0000],"segStart":[9.5866,10.5866],"segEnd":[10.5866,11.5866]},
            {"veh":10,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[2.0000,3.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":11,"k":1,"t0":4.0000,"tf":6.0000,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[2.0000,3.0000],"segStart":[4.0000,5.0000],"segEnd":[5.0000,6.0000]},
            {"veh":14,"k":2,"t0":6.2304,"tf":8.5866,"genTime":6.0000,"actualGenTime":6.2273,"spaces":[4.0000,5.0000,2.0000],"segStart":[6.2304,7.0158,7.8012],"segEnd":[7.0158,7.8012,8.5866]}
          ],
          "numSpaces": 5
        }
      ]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.00,"isLeaf":false,"isRoot":true},
        {"id":2,"orig":11,"tw":6.857,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":3,"orig":12,"tw":7.642,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":4,"orig":13,"tw":6.946,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":5,"orig":14,"tw":8.000,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":6,"orig":16,"tw":8.428,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":7,"orig":17,"tw":8.428,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":8,"orig":23,"tw":8.642,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":9,"orig":24,"tw":9.213,"f":0.50,"isLeaf":false,"isRoot":false},
        {"id":10,"orig":25,"tw":9.213,"f":0.07,"isLeaf":false,"isRoot":false},
        {"id":11,"orig":26,"tw":8.785,"f":-0.00,"isLeaf":false,"isRoot":false},
        {"id":12,"orig":32,"tw":9.428,"f":0.07,"isLeaf":false,"isRoot":false},
        {"id":13,"orig":33,"tw":9.998,"f":1.28,"isLeaf":false,"isRoot":false},
        {"id":14,"orig":40,"tw":24.111,"f":0.11,"isLeaf":true,"isRoot":false},
        {"id":15,"orig":52,"tw":24.111,"f":2.36,"isLeaf":true,"isRoot":false},
        {"id":16,"orig":58,"tw":24.111,"f":2.86,"isLeaf":true,"isRoot":false},
        {"id":17,"orig":64,"tw":24.111,"f":3.71,"isLeaf":true,"isRoot":false},
        {"id":18,"orig":70,"tw":24.111,"f":3.93,"isLeaf":true,"isRoot":false},
        {"id":19,"orig":76,"tw":24.111,"f":5.28,"isLeaf":true,"isRoot":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [3,5],
        [5,6],
        [5,7],
        [6,8],
        [6,9],
        [7,10],
        [7,11],
        [10,12],
        [10,13],
        [4,14],
        [8,15],
        [11,16],
        [9,17],
        [12,18],
        [13,19]
      ],
      "optimalPath": [1,2,4,14],
      "optimalLeaf": 1,
      "leafPaths": [
        [1,2,4,14],
        [1,2,3,5,6,8,15],
        [1,2,3,5,7,11,16],
        [1,2,3,5,6,9,17],
        [1,2,3,5,7,10,12,18],
        [1,2,3,5,7,10,13,19]
      ],
      "leafGantts": [
        {
          "fCost": 0.11,
          "vehicles": [
            {"veh":3,"k":2,"t0":4.7854,"tf":5.5707,"genTime":4.7854,"actualGenTime":4.7853,"spaces":[2.0000],"segStart":[4.7854],"segEnd":[5.5707]},
            {"veh":4,"k":2,"t0":6.9456,"tf":9.3018,"genTime":6.7855,"actualGenTime":6.8596,"spaces":[2.0000,5.0000,4.0000],"segStart":[6.9456,7.7310,8.5164],"segEnd":[7.7310,8.5164,9.3018]},
            {"veh":6,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000,4.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":7,"k":1,"t0":4.0000,"tf":6.0000,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[3.0000,4.0000],"segStart":[4.0000,5.0000],"segEnd":[5.0000,6.0000]},
            {"veh":10,"k":2,"t0":5.9456,"tf":7.9456,"genTime":5.9658,"actualGenTime":5.9497,"spaces":[2.0000,3.0000],"segStart":[5.9456,6.9456],"segEnd":[6.9456,7.9456]},
            {"veh":11,"k":2,"t0":8.0000,"tf":8.7854,"genTime":8.0000,"actualGenTime":8.0000,"spaces":[2.0000],"segStart":[8.0000],"segEnd":[8.7854]},
            {"veh":14,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[4.0000,1.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":15,"k":1,"t0":4.0000,"tf":4.7854,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[4.0000],"segStart":[4.0000],"segEnd":[4.7854]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 2.36,
          "vehicles": [
            {"veh":3,"k":2,"t0":4.7854,"tf":5.5707,"genTime":4.7854,"actualGenTime":4.7853,"spaces":[2.0000],"segStart":[4.7854],"segEnd":[5.5707]},
            {"veh":4,"k":2,"t0":6.8569,"tf":9.2131,"genTime":6.7855,"actualGenTime":6.8596,"spaces":[2.0000,5.0000,4.0000],"segStart":[6.8569,7.6423,8.4277],"segEnd":[7.6423,8.4277,9.2131]},
            {"veh":6,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000,4.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":7,"k":1,"t0":4.0000,"tf":6.0000,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[3.0000,4.0000],"segStart":[4.0000,5.0000],"segEnd":[5.0000,6.0000]},
            {"veh":10,"k":2,"t0":7.6423,"tf":9.6423,"genTime":5.9658,"actualGenTime":5.9497,"spaces":[2.0000,3.0000],"segStart":[7.6423,8.6423],"segEnd":[8.6423,9.6423]},
            {"veh":11,"k":2,"t0":8.6423,"tf":9.4277,"genTime":8.0000,"actualGenTime":8.0000,"spaces":[2.0000],"segStart":[8.6423],"segEnd":[9.4277]},
            {"veh":14,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[4.0000,1.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":15,"k":1,"t0":4.0000,"tf":4.7854,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[4.0000],"segStart":[4.0000],"segEnd":[4.7854]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 2.86,
          "vehicles": [
            {"veh":3,"k":2,"t0":4.7854,"tf":5.5707,"genTime":4.7854,"actualGenTime":4.7853,"spaces":[2.0000],"segStart":[4.7854],"segEnd":[5.5707]},
            {"veh":4,"k":2,"t0":6.8569,"tf":9.2131,"genTime":6.7855,"actualGenTime":6.8596,"spaces":[2.0000,5.0000,4.0000],"segStart":[6.8569,7.6423,8.4277],"segEnd":[7.6423,8.4277,9.2131]},
            {"veh":6,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000,4.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":7,"k":1,"t0":4.0000,"tf":6.0000,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[3.0000,4.0000],"segStart":[4.0000,5.0000],"segEnd":[5.0000,6.0000]},
            {"veh":10,"k":2,"t0":8.7854,"tf":10.7854,"genTime":5.9658,"actualGenTime":5.9497,"spaces":[2.0000,3.0000],"segStart":[8.7854,9.7854],"segEnd":[9.7854,10.7854]},
            {"veh":11,"k":2,"t0":8.0000,"tf":8.7854,"genTime":8.0000,"actualGenTime":8.0000,"spaces":[2.0000],"segStart":[8.0000],"segEnd":[8.7854]},
            {"veh":14,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[4.0000,1.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":15,"k":1,"t0":4.0000,"tf":4.7854,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[4.0000],"segStart":[4.0000],"segEnd":[4.7854]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 3.71,
          "vehicles": [
            {"veh":3,"k":2,"t0":4.7854,"tf":5.5707,"genTime":4.7854,"actualGenTime":4.7853,"spaces":[2.0000],"segStart":[4.7854],"segEnd":[5.5707]},
            {"veh":4,"k":2,"t0":6.8569,"tf":9.2131,"genTime":6.7855,"actualGenTime":6.8596,"spaces":[2.0000,5.0000,4.0000],"segStart":[6.8569,7.6423,8.4277],"segEnd":[7.6423,8.4277,9.2131]},
            {"veh":6,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000,4.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":7,"k":1,"t0":4.0000,"tf":6.0000,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[3.0000,4.0000],"segStart":[4.0000,5.0000],"segEnd":[5.0000,6.0000]},
            {"veh":10,"k":2,"t0":9.2131,"tf":11.2131,"genTime":5.9658,"actualGenTime":5.9497,"spaces":[2.0000,3.0000],"segStart":[9.2131,10.2131],"segEnd":[10.2131,11.2131]},
            {"veh":11,"k":2,"t0":8.4277,"tf":9.2131,"genTime":8.0000,"actualGenTime":8.0000,"spaces":[2.0000],"segStart":[8.4277],"segEnd":[9.2131]},
            {"veh":14,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[4.0000,1.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":15,"k":1,"t0":4.0000,"tf":4.7854,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[4.0000],"segStart":[4.0000],"segEnd":[4.7854]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 3.93,
          "vehicles": [
            {"veh":3,"k":2,"t0":4.7854,"tf":5.5707,"genTime":4.7854,"actualGenTime":4.7853,"spaces":[2.0000],"segStart":[4.7854],"segEnd":[5.5707]},
            {"veh":4,"k":2,"t0":6.8569,"tf":9.2131,"genTime":6.7855,"actualGenTime":6.8596,"spaces":[2.0000,5.0000,4.0000],"segStart":[6.8569,7.6423,8.4277],"segEnd":[7.6423,8.4277,9.2131]},
            {"veh":6,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000,4.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":7,"k":1,"t0":4.0000,"tf":6.0000,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[3.0000,4.0000],"segStart":[4.0000,5.0000],"segEnd":[5.0000,6.0000]},
            {"veh":10,"k":2,"t0":8.4277,"tf":10.4277,"genTime":5.9658,"actualGenTime":5.9497,"spaces":[2.0000,3.0000],"segStart":[8.4277,9.4277],"segEnd":[9.4277,10.4277]},
            {"veh":11,"k":2,"t0":9.4277,"tf":10.2131,"genTime":8.0000,"actualGenTime":8.0000,"spaces":[2.0000],"segStart":[9.4277],"segEnd":[10.2131]},
            {"veh":14,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[4.0000,1.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":15,"k":1,"t0":4.0000,"tf":4.7854,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[4.0000],"segStart":[4.0000],"segEnd":[4.7854]}
          ],
          "numSpaces": 5
        },
        {
          "fCost": 5.28,
          "vehicles": [
            {"veh":3,"k":2,"t0":4.7854,"tf":5.5707,"genTime":4.7854,"actualGenTime":4.7853,"spaces":[2.0000],"segStart":[4.7854],"segEnd":[5.5707]},
            {"veh":4,"k":2,"t0":6.8569,"tf":9.2131,"genTime":6.7855,"actualGenTime":6.8596,"spaces":[2.0000,5.0000,4.0000],"segStart":[6.8569,7.6423,8.4277],"segEnd":[7.6423,8.4277,9.2131]},
            {"veh":6,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[3.0000,4.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":7,"k":1,"t0":4.0000,"tf":6.0000,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[3.0000,4.0000],"segStart":[4.0000,5.0000],"segEnd":[5.0000,6.0000]},
            {"veh":10,"k":2,"t0":9.9985,"tf":11.9985,"genTime":5.9658,"actualGenTime":5.9497,"spaces":[2.0000,3.0000],"segStart":[9.9985,10.9985],"segEnd":[10.9985,11.9985]},
            {"veh":11,"k":2,"t0":9.2131,"tf":9.9985,"genTime":8.0000,"actualGenTime":8.0000,"spaces":[2.0000],"segStart":[9.2131],"segEnd":[9.9985]},
            {"veh":14,"k":1,"t0":2.0000,"tf":4.0000,"genTime":2.0000,"actualGenTime":2.0000,"spaces":[4.0000,1.0000],"segStart":[2.0000,3.0000],"segEnd":[3.0000,4.0000]},
            {"veh":15,"k":1,"t0":4.0000,"tf":4.7854,"genTime":4.0000,"actualGenTime":4.0000,"spaces":[4.0000],"segStart":[4.0000],"segEnd":[4.7854]}
          ],
          "numSpaces": 5
        }
      ]
    }
  }
};
