// Decision-tree data — group=10r  scene=S3_p2
// Auto-generated by export_tree_json.m — do not edit manually.
window.ALL_TREE_DATA = window.ALL_TREE_DATA || {};
window.ALL_TREE_DATA["10r_S3_p2"] = {
  "group": "10r", "scene": "S3_p2",
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":20,"tw":22.896,"f":-0.001,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":5,"tw":3.571,"f":0.000,"isPath":true},
        {"id":3,"orig":6,"tw":4.000,"f":0.000,"isPath":true},
        {"id":4,"orig":7,"tw":4.356,"f":0.000,"isPath":false},
        {"id":5,"orig":11,"tw":6.893,"f":0.429,"isPath":true},
        {"id":6,"orig":12,"tw":7.679,"f":0.537,"isPath":false},
        {"id":7,"orig":13,"tw":7.001,"f":0.429,"isPath":true},
        {"id":8,"orig":25,"tw":25.253,"f":0.645,"isPath":true},
        {"id":9,"orig":27,"tw":6.893,"f":1.356,"isPath":false},
        {"id":10,"orig":28,"tw":7.679,"f":1.464,"isPath":false},
        {"id":11,"orig":29,"tw":7.001,"f":1.356,"isPath":false},
        {"id":12,"orig":41,"tw":25.253,"f":1.572,"isPath":false},
        {"id":13,"orig":47,"tw":25.253,"f":2.215,"isPath":false},
        {"id":14,"orig":53,"tw":25.253,"f":3.142,"isPath":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [3,5],
        [5,6],
        [5,7],
        [7,8],
        [4,9],
        [9,10],
        [9,11],
        [11,12],
        [6,13],
        [10,14]
      ],
      "path": [1,2,3,5,7,8]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":16,"tw":25.785,"f":-0.022,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":18,"tw":22.096,"f":1.278,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    }
  }
};
