// Decision-tree data — group=15r  scene=S2
// Auto-generated by export_tree_json.m — do not edit manually.
window.ALL_TREE_DATA = window.ALL_TREE_DATA || {};
window.ALL_TREE_DATA["15r_S2"] = {
  "group": "15r", "scene": "S2",
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":26,"tw":36.111,"f":0.000,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":29,"tw":40.111,"f":0.000,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":29,"tw":44.467,"f":0.000,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":22,"tw":36.467,"f":0.000,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    }
  }
};
