// Decision-tree data — group=15r  scene=S1_p4
// Auto-generated by export_tree_json.m — do not edit manually.
window.ALL_TREE_DATA = window.ALL_TREE_DATA || {};
window.ALL_TREE_DATA["15r_S1_p4"] = {
  "group": "15r", "scene": "S1_p4",
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":27,"tw":27.284,"f":-0.034,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":22,"tw":24.111,"f":-0.000,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":14,"tw":7.801,"f":0.000,"isPath":true},
        {"id":3,"orig":15,"tw":8.024,"f":0.024,"isPath":true},
        {"id":4,"orig":16,"tw":8.301,"f":0.000,"isPath":false},
        {"id":5,"orig":17,"tw":9.301,"f":0.516,"isPath":false},
        {"id":6,"orig":18,"tw":8.587,"f":0.230,"isPath":false},
        {"id":7,"orig":19,"tw":8.301,"f":0.024,"isPath":true},
        {"id":8,"orig":20,"tw":9.301,"f":0.540,"isPath":false},
        {"id":9,"orig":21,"tw":8.810,"f":0.478,"isPath":true},
        {"id":10,"orig":22,"tw":9.587,"f":0.230,"isPath":false},
        {"id":11,"orig":23,"tw":9.301,"f":0.230,"isPath":false},
        {"id":12,"orig":27,"tw":10.301,"f":2.817,"isPath":false},
        {"id":13,"orig":28,"tw":10.087,"f":2.246,"isPath":false},
        {"id":14,"orig":34,"tw":23.412,"f":1.502,"isPath":true},
        {"id":15,"orig":41,"tw":23.412,"f":2.270,"isPath":false},
        {"id":16,"orig":48,"tw":23.412,"f":5.047,"isPath":false},
        {"id":17,"orig":53,"tw":23.412,"f":5.333,"isPath":false},
        {"id":18,"orig":58,"tw":23.412,"f":5.548,"isPath":false},
        {"id":19,"orig":63,"tw":23.412,"f":5.618,"isPath":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [4,5],
        [4,6],
        [3,7],
        [7,8],
        [7,9],
        [6,10],
        [6,11],
        [5,12],
        [5,13],
        [9,14],
        [8,15],
        [11,16],
        [13,17],
        [12,18],
        [10,19]
      ],
      "path": [1,2,3,7,9,14]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":13,"tw":8.318,"f":-0.000,"isPath":true},
        {"id":3,"orig":14,"tw":8.406,"f":-0.000,"isPath":true},
        {"id":4,"orig":15,"tw":8.406,"f":-0.000,"isPath":false},
        {"id":5,"orig":16,"tw":8.620,"f":-0.000,"isPath":true},
        {"id":6,"orig":17,"tw":9.191,"f":0.455,"isPath":false},
        {"id":7,"orig":18,"tw":9.191,"f":0.049,"isPath":false},
        {"id":8,"orig":19,"tw":9.103,"f":0.318,"isPath":false},
        {"id":9,"orig":22,"tw":9.406,"f":0.049,"isPath":false},
        {"id":10,"orig":23,"tw":9.976,"f":1.240,"isPath":false},
        {"id":11,"orig":39,"tw":24.429,"f":2.290,"isPath":true},
        {"id":12,"orig":45,"tw":24.429,"f":3.471,"isPath":false},
        {"id":13,"orig":51,"tw":24.429,"f":3.646,"isPath":false},
        {"id":14,"orig":57,"tw":24.429,"f":3.861,"isPath":false},
        {"id":15,"orig":63,"tw":24.429,"f":5.217,"isPath":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [3,5],
        [3,6],
        [4,7],
        [4,8],
        [7,9],
        [7,10],
        [5,11],
        [8,12],
        [6,13],
        [9,14],
        [10,15]
      ],
      "path": [1,2,3,5,11]
    }
  }
};
