// Decision-tree data — group=10r  scene=S2
// Auto-generated by export_tree_json.m — do not edit manually.
window.ALL_TREE_DATA = window.ALL_TREE_DATA || {};
window.ALL_TREE_DATA["10r_S2"] = {
  "group": "10r", "scene": "S2",
  "intersections": {
    "1": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":20,"tw":24.111,"f":-0.000,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "2": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":23,"tw":28.467,"f":-0.000,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    },
    "3": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":10,"tw":6.356,"f":0.000,"isPath":true},
        {"id":3,"orig":11,"tw":6.356,"f":0.000,"isPath":true},
        {"id":4,"orig":12,"tw":7.356,"f":0.000,"isPath":false},
        {"id":5,"orig":15,"tw":8.178,"f":0.000,"isPath":true},
        {"id":6,"orig":16,"tw":8.964,"f":0.178,"isPath":false},
        {"id":7,"orig":17,"tw":8.356,"f":-0.000,"isPath":true},
        {"id":8,"orig":23,"tw":24.289,"f":0.356,"isPath":true},
        {"id":9,"orig":24,"tw":8.178,"f":1.785,"isPath":false},
        {"id":10,"orig":25,"tw":8.964,"f":1.963,"isPath":false},
        {"id":11,"orig":26,"tw":8.356,"f":1.785,"isPath":false},
        {"id":12,"orig":31,"tw":24.289,"f":1.786,"isPath":false},
        {"id":13,"orig":37,"tw":24.289,"f":2.141,"isPath":false},
        {"id":14,"orig":41,"tw":24.289,"f":3.749,"isPath":false}
      ],
      "edges": [
        [1,2],
        [2,3],
        [2,4],
        [3,5],
        [5,6],
        [5,7],
        [7,8],
        [4,9],
        [9,10],
        [9,11],
        [6,12],
        [11,13],
        [10,14]
      ],
      "path": [1,2,3,5,7,8]
    },
    "4": {
      "nodes": [
        {"id":1,"orig":1,"tw":0.000,"f":0.000,"isPath":true},
        {"id":2,"orig":17,"tw":22.467,"f":-0.000,"isPath":true}
      ],
      "edges": [
        [1,2]
      ],
      "path": [1,2]
    }
  }
};
